<?php

// autoload_static.php @generated by Composer

namespace Composer\Autoload;

class ComposerStaticIniteebbfc33cb1c34c0f609fd9372328f8d
{
    public static $prefixLengthsPsr4 = array (
        'T' => 
        array (
            'Twilio\\' => 7,
        ),
    );

    public static $prefixDirsPsr4 = array (
        'Twilio\\' => 
        array (
            0 => __DIR__ . '/..' . '/twilio/sdk/Twilio',
        ),
    );

    public static function getInitializer(ClassLoader $loader)
    {
        return \Closure::bind(function () use ($loader) {
            $loader->prefixLengthsPsr4 = ComposerStaticIniteebbfc33cb1c34c0f609fd9372328f8d::$prefixLengthsPsr4;
            $loader->prefixDirsPsr4 = ComposerStaticIniteebbfc33cb1c34c0f609fd9372328f8d::$prefixDirsPsr4;

        }, null, ClassLoader::class);
    }
}
