<?php
$application = $this->getApplication();
$app_id      = $application->getId();
$migareference  = new Migareference_Model_Migareference();    
$referral_usrs  = $migareference->get_referral_users($app_id);
$agents         = $migareference->get_customer_agents($app_id);
$pre_settings = $migareference->preReportsettigns($app_id);
$default        = new Core_Model_Default();
$base_url       = $default->getBaseUrl();
?>
<script type="text/javascript" language="javascript" src="https://cdn.datatables.net/1.10.19/js/jquery.dataTables.min.js"></script>
<script type="text/javascript" language="javascript" src="https://cdn.datatables.net/buttons/1.5.2/js/dataTables.buttons.min.js"></script>
<script type="text/javascript" language="javascript" src="https://cdn.datatables.net/buttons/1.5.2/js/buttons.flash.min.js"></script>
<script type="text/javascript" language="javascript" src="https://cdnjs.cloudflare.com/ajax/libs/jszip/3.1.3/jszip.min.js"></script>
<script type="text/javascript" language="javascript" src="https://cdnjs.cloudflare.com/ajax/libs/pdfmake/0.1.36/pdfmake.min.js"></script>
<script type="text/javascript" language="javascript" src="https://cdnjs.cloudflare.com/ajax/libs/pdfmake/0.1.36/vfs_fonts.js"></script>
<script type="text/javascript" language="javascript" src="https://cdn.datatables.net/buttons/1.5.2/js/buttons.html5.min.js"></script>
<script type="text/javascript" language="javascript" src="https://cdn.datatables.net/buttons/1.5.2/js/buttons.print.min.js"></script>
<div id="pagecontainer">
    <div class="application_analytics application content" id="content">
        <h3 class="title-editor border-blue text-center"><?php echo __("Migareference Agent Stats") ?></h3>
        <div class="container-fluid subcontent content-color">        
            <ul class="nav nav-tabs" role="tablist" data-html2canvas-ignore="true">
                <li role="presentation" >
                    <a href="<?=$base_url."/migareference/generalstats/general" ?>">
                        <i class="fa fa-line-chart"></i>
                        <?php echo __("General") ?>
                    </a>
                </li>
                <li role="presentation" class="active" >
                    <a href="#">
                        <i class="fa fa-line-chart"></i>
                        <?php echo __("Agent") ?>
                    </a>
                </li>
                <li role="presentation" >
                    <a href="<?=$base_url."/migareference/referrerstats/referrer" ?>">
                        <i class="fa fa-line-chart"></i>
                        <?php echo __("Referrers") ?>
                    </a>
                </li>    
                <li style="float:right;">
                    <button class="btn color-blue" onclick="printPdf()">
                        <i class="fa fa-download"></i>
                        <?php echo __("PDF") ?>
                        <span style="display:none;" id="pdf_download_loader"><i class="fa fa-circle-o-notch fa-spin fa-fw"></i></span>
                    </button>
                </li>              
            </ul>                          
            <!-- Filter Start -->
            <div class="row">
                <div class="col-md-2">
                    <select onchange="filterType()" id="range_filter" class="input-flat" name="">
                        <option selected value="1"><?php echo __("Last 30 Days") ?></option>                            
                        <option value="2"><?php echo __("Last 3 Months") ?></option>                            
                        <option value="3"><?php echo __("Last 6 Months") ?></option>                            
                        <option value="4"><?php echo __("Current Year") ?></option>                            
                        <option value="5"><?php echo __("Last Year") ?></option>                            
                        <option value="6"><?php echo __("All") ?></option>                            
                        <option style="font-weight:600" value="100"><?php echo __("Custom Range") ?></option>                            
                    </select>
                </div>
                <div class="col-md-2">  
                    <select  id="sponsor_filter" class="input-flat" name="">
                        <?php if ($pre_settings[0]['enable_mandatory_agent_selection']==2) { ?>
                                <option value="0"><?php echo __("I dont know") ?></option>
                        <?php } ?>                                                       
                        <?php foreach ($agents as $key => $value): ?>
                        <option value="<?=$value['user_id'] ?>"><?=$value['firstname']." ".$value['lastname'] ?>
                        </option>
                        <?php endforeach; ?>
                    </select>              
                </div>
                <div class="col-md-5" id="custom_date_filter_container" style="display:none;">                
                    <div id="row_filter_metrics" class="row sb-tour">
                        <div class="col-md-2">
                            <label for="from"><?php echo __("From"); ?></label>
                        </div>
                        <div class="col-md-4">
                            <input type="text" id="from" name="from" class="input-flat sb-tour">
                        </div>
                        <div class="col-md-2">
                            <label for="to"><?php echo __("To"); ?></label>
                        </div>
                        <div class="col-md-4">
                            <input type="text" id="to" name="to" class="input-flat sb-tour">
                        </div>                    
                    </div>
                </div>                    
                <div class="col-md-1" data-html2canvas-ignore="true">
                    <button data-html2canvas-ignore="true" class="btn color-blue" onclick="loadReferrerStats()">                    
                        <?php echo __("Filter Stats") ?>                    
                    </button>
                </div>                    
            </div>        
            <!-- (All) Referers -->
            <div class="row first-row-feature" style="padding-top:0px;" >
                <h3 class="fs-titel stat-headings"></i> <?php echo __("Referrers") ?></h3>                                                  
                <div style="margin-left:49%;" id="total_referrers_loader" class="loader_metrics"><i class="fa fa-circle-o-notch fa-spin fa-3x fa-fw"></i><br/><?php echo __("Loading..."); ?></div>
                <div class="row stat-count-container">
                    <div class="col-md-1">                                    
                    </div>               
                    <div class="col-md-2">
                        <div class="stat-calculate" style="">
                            <p>
                            <?php echo __("No. Referrers") ?></p>
                            <h1 class="dfault-0" id="gen_stats_count_referrer"></h1>
                            <p style="height:20px" class="count_veriation" id="var_gen_stats_count_referrer">                                            
                            </p>
                        </div>
                    </div>                        
                    <div class="col-md-2">
                        <div class="stat-calculate" style="">
                            <p>
                            <?php echo __("5 Stars Referrers") ?></p>
                            <h1 class="dfault-0" id="gen_stats_count_5s_referrer"></h1>
                            <p style="height:20px" class="count_veriation" id="var_gen_stats_count_5s_referrer">                                             
                            </p>
                        </div>
                    </div>                        
                    <div class="col-md-2">
                        <div class="stat-calculate" style="">
                            <p>
                            <?php echo __("4 Stars Referrers") ?></p>
                            <h1 class="dfault-0" id="gen_stats_count_4s_referrer"></h1>
                            <p style="height:20px" class="count_veriation" id="var_gen_stats_count_4s_referrer">                                            
                            </p>
                        </div>
                    </div>                                                                
                    <div class="col-md-2">
                        <div class="stat-calculate" style="">
                            <p>
                            <?php echo __("3 Stars Referrers") ?></p>
                            <h1 class="dfault-0" id="gen_stats_count_3s_referrer"></h1>
                            <p style="height:20px" class="count_veriation" id="var_gen_stats_count_3s_referrer">                                            
                            </p>
                        </div>
                    </div>                                                                
                    <div class="col-md-2">
                        <div class="stat-calculate" style="background-color:#f8eabb;">
                            <p>
                            <?php echo __("4/5 Star KPI") ?></p>
                            <h1 class="dfault-0" id="gen_stats_count_referrer_45_kpi"></h1>
                            <p style="height:20px" class="count_veriation" id="var_gen_stats_count_referrer_45_kpi">                                            
                            </p>
                        </div>
                    </div>                                        
                    <div class="col-md-1">                                    
                    </div>                                                        
                </div>
                <div class="row stat-count-container">
                    <div class="col-md-4" style="overflow:hidden;padding-right:0;padding-left:0;">
                        <p style='font-weight:700;text-align:center;'>
                        <?php echo __("Best 10 Jobs") ?></p>
                        <div style="background:white;padding:0;text-align:center;" class='pie-chart-legend' id="referrer_jobs_legends"></div>
                        <div style="padding-right:20%;padding-left:20%;padding-bottom:2%;background:white;">
                            <canvas style="width:100%" id="referrer_jobs" class="content-white-bkg sb-tour"></canvas>    
                        </div>
                    </div>
                    <div class="col-md-4" style="overflow:hidden;padding-right:0;padding-left:0;">
                        <p style='font-weight:700;text-align:center;'>
                        <?php echo __("Age Group") ?></p>
                        <div style="background:white;padding:0;text-align:center;" class='pie-chart-legend' id="referrer_age_legends"></div>
                        <div style="padding-right:20%;padding-left:20%;padding-bottom:2%;background:white;">
                        <canvas style="width:100%" id="referrer_age" class="content-white-bkg sb-tour"></canvas>    
                        </div>
                    </div>
                    <div class="col-md-4" style="overflow:hidden;padding-right:0;padding-left:0;">
                        <p style='font-weight:700;text-align:center;'>
                        <?php echo __("Best 10 Regions") ?></p>
                        <div style="background:white;padding:0;text-align:center;" class='pie-chart-legend' id="referrer_region_legends"></div>
                        <div style="padding-right:20%;padding-left:20%;padding-bottom:2%;background:white;">
                        <canvas style="width:100%" id="referrer_region" class="content-white-bkg sb-tour"></canvas>    
                        </div>
                    </div>
                </div>
            </div>  
            <!-- Range Referers -->
            <div class="row first-row-feature" style="padding-top:0px;">
                <h3 class="fs-titel stat-headings"><i class="fa fa-clock-o" aria-hidden="true" style="padding-right: 7px;"></i> <?php echo __("Time Range Referrers") ?> <span class='filter-time-stamp'></span></h3>                                      
                <div class="row" style="padding-left:20px;padding-right:20px;padding-top:10px;padding-bottom:10px;">
                    <div class="col-md-12 col-xs-12" style="max-height:348px">
                        <div style="margin-left:49%;" id="total_referrers_loader" class="loader_metrics"><i class="fa fa-circle-o-notch fa-spin fa-3x fa-fw"></i><br/><?php echo __("Loading..."); ?></div>
                        <canvas style="border:1px solid #dedddd"  id="total_referrers" class="content-white-bkg sb-tour" width="400" height="340"></canvas>
                    </div>
                </div>
                <div class="row stat-count-container">
                    <div class="col-md-1">                                    
                    </div>               
                    <div class="col-md-2">
                        <div class="stat-calculate" style="">
                            <p><i class="fa fa-clock-o" aria-hidden="true" style="padding-right: 7px;"></i>
                            <?php echo __("No. Referrers") ?></p>
                            <h1 class="dfault-0" id="gen_stats_count_range_referrer"></h1>
                            <p class="count_veriation" id="var_gen_stats_count_range_referrer">                                            
                            </p>
                        </div>
                    </div>                        
                    <div class="col-md-2">
                        <div class="stat-calculate" style="">
                            <p><i class="fa fa-clock-o" aria-hidden="true" style="padding-right: 7px;"></i>
                            <?php echo __("5 Stars Referrers") ?></p>
                            <h1 class="dfault-0" id="gen_stats_count_range_5s_referrer"></h1>
                            <p class="count_veriation" id="var_gen_stats_count_range_5s_referrer">                                             
                            </p>
                        </div>
                    </div>                        
                    <div class="col-md-2">
                        <div class="stat-calculate" style="">
                            <p><i class="fa fa-clock-o" aria-hidden="true" style="padding-right: 7px;"></i>
                            <?php echo __("4 Stars Referrers") ?></p>
                            <h1 class="dfault-0" id="gen_stats_count_range_4s_referrer"></h1>
                            <p class="count_veriation" id="var_gen_stats_count_range_4s_referrer">                                            
                            </p>
                        </div>
                    </div>                                                                
                    <div class="col-md-2">
                        <div class="stat-calculate" style="">
                            <p><i class="fa fa-clock-o" aria-hidden="true" style="padding-right: 7px;"></i>
                            <?php echo __("3 Stars Referrers") ?></p>
                            <h1 class="dfault-0" id="gen_stats_count_range_3s_referrer"></h1>
                            <p class="count_veriation" id="var_gen_stats_count_range_3s_referrer">                                            
                            </p>
                        </div>
                    </div>                                                                
                    <div class="col-md-2">
                        <div class="stat-calculate" style="background-color:#f8eabb;">
                            <p><i class="fa fa-clock-o" aria-hidden="true" style="padding-right: 7px;"></i>
                            <?php echo __("4/5 Star KPI") ?></p>
                            <h1 class="dfault-0" id="gen_stats_count_range_referrer_45_kpi"></h1>
                            <p class="count_veriation" id="var_gen_stats_count_range_referrer_45_kpi">                                            
                            </p>
                        </div>
                    </div>                                        
                    <div class="col-md-1">                                    
                    </div>                                                        
                </div>
                <div class="row stat-count-container">
                    <div class="col-md-4" style="overflow:hidden;padding-right:0;padding-left:0;">
                        <p style='font-weight:700;text-align:center;'><i class="fa fa-clock-o" aria-hidden="true" style="padding-right: 7px;"></i>
                        <?php echo __("Best 10 Jobs") ?></p>
                        <div style="background:white;padding:0;text-align:center;" class='pie-chart-legend' id="range_referrer_jobs_legends"></div>
                        <div style="padding-right:20%;padding-left:20%;padding-bottom:2%;background:white;">
                            <canvas style="width:100%" id="range_referrer_jobs" class="content-white-bkg sb-tour"></canvas>    
                        </div>
                    </div>
                    <div class="col-md-4" style="overflow:hidden;padding-right:0;padding-left:0;">
                        <p style='font-weight:700;text-align:center;'><i class="fa fa-clock-o" aria-hidden="true" style="padding-right: 7px;"></i>
                        <?php echo __("Age Group") ?></p>
                        <div style="background:white;padding:0;text-align:center;" class='pie-chart-legend' id="range_referrer_age_legends"></div>
                        <div style="padding-right:20%;padding-left:20%;padding-bottom:2%;background:white;">
                        <canvas style="width:100%" id="range_referrer_age" class="content-white-bkg sb-tour"></canvas>    
                        </div>
                    </div>
                    <div class="col-md-4" style="overflow:hidden;padding-right:0;padding-left:0;">
                        <p style='font-weight:700;text-align:center;'><i class="fa fa-clock-o" aria-hidden="true" style="padding-right: 7px;"></i>
                        <?php echo __("Best 10 Regions") ?></p>
                        <div style="background:white;padding:0;text-align:center;" class='pie-chart-legend' id="range_referrer_region_legends"></div>
                        <div style="padding-right:20%;padding-left:20%;padding-bottom:2%;background:white;">
                        <canvas style="width:100%" id="range_referrer_region" class="content-white-bkg sb-tour"></canvas>    
                        </div>
                    </div>
                </div>
            </div>  
            <!-- All Reports -->
            <div class="row first-row-feature" style="padding-top:0px;">
                <h3 class="fs-titel stat-headings"><?php echo __("Reports Statistics") ?></h3>
                <div class="row" style="padding-left:20px;padding-right:20px;padding-top:10px;padding-bottom:10px;">
                    <div class="col-md-12 col-xs-12" style="max-height:348px">
                        <div style="margin-left:49%;" id="total_reports_loader" class="loader_metrics"><i class="fa fa-circle-o-notch fa-spin fa-3x fa-fw"></i><br/><?php echo __("Loading..."); ?></div>
                        <canvas style="border:1px solid #dedddd"  id="total_reports" class="content-white-bkg sb-tour" width="400" height="340"></canvas>
                    </div>
                </div>
                <div class="row stat-count-container">
                    <div class="col-md-1">                                    
                    </div>               
                    <div class="col-md-2">
                        <div class="stat-calculate" style="">
                            <p><?php echo __("No. of Reports") ?></p>
                            <h1 class="dfault-0" id="ref_stat_count_total_reports_all"></h1>
                            <p class="default-hide count_veriation">
                                Variation 
                                <span class="default-hide stats-possitive"> <i class="fa fa-arrow-up" aria-hidden="true"></i></span>
                                <span class="default-hide stats-negative"> <i class="fa fa-arrow-down" aria-hidden="true"></i></span>                                   
                            </p>
                        </div>
                    </div>                        
                    <div class="col-md-2">
                        <div class="stat-calculate" style="">
                            <p><?php echo __("No. Deal Closed") ?></p>
                            <h1 class="dfault-0" id="ref_stat_count_total_reports_success"></h1>
                            <p class="default-hide count_veriation">
                                Variation 
                                <span class="default-hide "> <i class="fa fa-arrow-up" aria-hidden="true"></i></span>
                                <span class="default-hide "> <i class="fa fa-arrow-down" aria-hidden="true"></i></span>                                    
                            </p>
                        </div>
                    </div>                        
                    <div class="col-md-2">
                        <div class="stat-calculate" style="background-color:#f8eabb;">
                            <p><?php echo __("Incubation Days") ?></p>
                            <h1 class="dfault-0" id="ref_stat_count_total_reports_incubation"></h1>
                            <p class="default-hide count_veriation">                                            
                            </p>
                        </div>
                    </div>                        
                    <div class="col-md-2">
                        <div class="stat-calculate" style="">
                            <p id="ref_stat_count_total_reports_commission_label"><?php echo __("Commissions") ?></p>
                            <h1 class="dfault-0" id="ref_stat_count_total_reports_commission"></h1>
                            <p class="default-hide count_veriation">
                                Variation 
                                <span class="default-hide "> <i class="fa fa-arrow-up" aria-hidden="true"></i></span>
                                <span class="default-hide "> <i class="fa fa-arrow-down" aria-hidden="true"></i></span>                                    
                            </p>
                        </div>
                    </div>                        
                    <div class="col-md-2">
                        <div class="stat-calculate" style="background-color:#f8eabb;">
                            <p><?php echo __("Reports KPI") ?></p>
                            <h1 class="dfault-0" id="ref_stat_count_total_reports_kpi"></h1>
                            <p class="default-hide count_veriation">
                                Variation 
                                <span class="default-hide "> <i class="fa fa-arrow-up" aria-hidden="true"></i></span>
                                <span class="default-hide "> <i class="fa fa-arrow-down" aria-hidden="true"></i></span>                                    
                            </p>
                        </div>
                    </div>                        
                    <div class="col-md-1">                                    
                    </div>                                                        
                </div>
            </div>
            <!-- Range Reports -->
            <div class="row first-row-feature" style="padding-top:0px;">
                <h3 class="fs-titel stat-headings">
                    <i class="fa fa-clock-o" aria-hidden="true" style="padding-right: 7px;"></i>
                    <?php echo __("Time Range Reports Statistics") ?>
                    <span class='filter-time-stamp'></span>
                </h3>
                <div class="row" style="padding-left:20px;padding-right:20px;padding-top:10px;padding-bottom:10px;">
                    <div class="col-md-12 col-xs-12" style="max-height:348px">
                        <div style="margin-left:49%;" id="range_reports_loader" class="loader_metrics"><i class="fa fa-circle-o-notch fa-spin fa-3x fa-fw"></i><br/><?php echo __("Loading..."); ?></div>
                        <canvas style="border:1px solid #dedddd" id="range_reports" class="content-white-bkg sb-tour" width="400" height="340"></canvas>
                    </div>
                </div>
                <div class="row stat-count-container">
                    <div class="col-md-1">                                    
                    </div>               
                    <div class="col-md-2">
                        <div class="stat-calculate" style="">
                            <p><i class="fa fa-clock-o" aria-hidden="true" style="padding-right: 7px;"></i><?php echo __("No. of Reports") ?></p>
                            <h1 class="dfault-0" id="ref_stat_count_range_reports_all"></h1>
                            <p class="count_veriation" id="var_ref_stat_count_range_reports_all">                                            
                            </p>
                        </div>
                    </div>                        
                    <div class="col-md-2">
                        <div class="stat-calculate" style="">
                            <p> <i class="fa fa-clock-o" aria-hidden="true" style="padding-right: 7px;"></i><?php echo __("No. Deal Closed") ?></p>
                            <h1 class="dfault-0" id="ref_stat_count_range_reports_success"></h1>
                            <p class="count_veriation" id="var_ref_stat_count_range_reports_success">                                            
                            </p>
                        </div>
                    </div>                        
                    <div class="col-md-2">
                        <div class="stat-calculate" style="background-color:#f8eabb;">
                            <p><i class="fa fa-clock-o" aria-hidden="true" style="padding-right: 7px;"></i><?php echo __("Incubation Days") ?></p>
                            <h1 class="dfault-0" id="ref_stat_count_range_reports_incubation"></h1>
                            <p class="count_veriation" id="var_ref_stat_count_range_reports_incubation">                                            
                            </p>
                        </div>
                    </div>                        
                    <div class="col-md-2">
                        <div class="stat-calculate" style="">
                            <p id="ref_stat_count_range_reports_commission_label"><i class="fa fa-clock-o" aria-hidden="true" style="padding-right: 7px;"></i><?php echo __("Commissions") ?></p>
                            <h1 class="dfault-0" id="ref_stat_count_range_reports_commission"></h1>
                            <p class="count_veriation" id="var_ref_stat_count_range_reports_commission">
                                
                            </p>
                        </div>
                    </div>                        
                    <div class="col-md-2">
                        <div class="stat-calculate" style="background-color:#f8eabb;">
                            <p><i class="fa fa-clock-o" aria-hidden="true" style="padding-right: 7px;"></i><?php echo __("Reports KPI") ?></p>
                            <h1 class="dfault-0" id="ref_stat_count_range_reports_kpi"></h1>
                            <p class="count_veriation" id="var_ref_stat_count_range_reports_kpi">                                            
                            </p>
                        </div>
                    </div>                        
                    <div class="col-md-1">                                    
                    </div>                                                        
                </div>
            </div>                                                                     
            <!-- All Reminders -->
            <div class="row first-row-feature" style="padding-top:0px;">
                <h3 class="fs-titel stat-headings"><?php echo __("Reminders Statistics") ?></h3>
                <div class="row" style="padding-left:20px;padding-right:20px;padding-top:10px;padding-bottom:10px;">
                    <div class="col-md-12 col-xs-12" style="max-height:348px">
                        <div style="margin-left:49%;" id="total_reminders_loader" class="loader_metrics"><i class="fa fa-circle-o-notch fa-spin fa-3x fa-fw"></i><br/><?php echo __("Loading..."); ?></div>
                        <canvas style="border:1px solid #dedddd"  id="total_reminders" class="content-white-bkg sb-tour" width="400" height="340"></canvas>
                    </div>
                </div>
                <div class="row stat-count-container">                                   
                    <div class="col-md-2">
                        <div class="stat-calculate" style="">
                            <p><?php echo __("No. Reminders") ?></p>
                            <h1 class="dfault-0" id="ref_stat_count_total_reminders_all"></h1>
                            <p class="default-hide count_veriation">
                                Variation 
                                <span class="default-hide stats-possitive"> <i class="fa fa-arrow-up" aria-hidden="true"></i></span>
                                <span class="default-hide stats-negative"> <i class="fa fa-arrow-down" aria-hidden="true"></i></span>                                   
                            </p>
                        </div>
                    </div>                        
                    <div class="col-md-2">
                        <div class="stat-calculate" style="">
                            <p><?php echo __("No. Warnings") ?></p>
                            <h1 class="dfault-0" id="ref_stat_count_total_reminders_warrnings"></h1>
                            <p class="default-hide count_veriation">
                                Variation 
                                <span class="default-hide "> <i class="fa fa-arrow-up" aria-hidden="true"></i></span>
                                <span class="default-hide "> <i class="fa fa-arrow-down" aria-hidden="true"></i></span>                                    
                            </p>
                        </div>
                    </div>                        
                    <div class="col-md-2">
                        <div class="stat-calculate" style="">
                            <p><?php echo __("No. Done") ?></p>
                            <h1 class="dfault-0" id="ref_stat_count_total_reminders_done"></h1>
                            <p class="default-hide count_veriation">
                                Variation 
                                <span class="default-hide "> <i class="fa fa-arrow-up" aria-hidden="true"></i></span>
                                <span class="default-hide "> <i class="fa fa-arrow-down" aria-hidden="true"></i></span>                                    
                            </p>
                        </div>
                    </div>                        
                    <div class="col-md-2">
                        <div class="stat-calculate" style="background-color:#f8eabb;">
                            <p><?php echo __("No. Rem. Postponed") ?></p>
                            <h1 class="dfault-0" id="ref_stat_count_total_reminders_potponed"></h1>
                            <p class="default-hide count_veriation">                                            
                            </p>
                        </div>
                    </div>                        
                    <div class="col-md-2">
                        <div class="stat-calculate" style="">
                            <p id=""><?php echo __("Management Days") ?></p>
                            <h1 class="dfault-0" id="ref_stat_count_total_reminders_managment"></h1>
                            <p class="default-hide count_veriation">
                                Variation 
                                <span class="default-hide "> <i class="fa fa-arrow-up" aria-hidden="true"></i></span>
                                <span class="default-hide "> <i class="fa fa-arrow-down" aria-hidden="true"></i></span>                                    
                            </p>
                        </div>
                    </div>                        
                    <div class="col-md-2">
                        <div class="stat-calculate" style="background-color:#f8eabb;">
                            <p><?php echo __("KPI Reliability") ?></p>
                            <h1 class="dfault-0" id="ref_stat_count_total_reminders_kpi"></h1>
                            <p class="default-hide count_veriation">
                                Variation 
                                <span class="default-hide "> <i class="fa fa-arrow-up" aria-hidden="true"></i></span>
                                <span class="default-hide "> <i class="fa fa-arrow-down" aria-hidden="true"></i></span>                                    
                            </p>
                        </div>
                    </div>                                                                                                  
                </div>
            </div>
            <!-- Range Reminders -->
            <div class="row first-row-feature" style="padding-top:15px;">
                <h3 class="fs-titel stat-headings">
                    <i class="fa fa-clock-o" aria-hidden="true" style="padding-right: 7px;"></i>
                    <?php echo __("Time Range Reminder Statistics") ?>
                    <span class='filter-time-stamp'></span>
                </h3>
                <div class="row" style="padding-left:20px;padding-right:20px;padding-top:10px;padding-bottom:10px;">
                    <div class="col-md-12 col-xs-12" style="max-height:348px">
                        <div style="margin-left:49%;" id="range_reminders_loader" class="loader_metrics"><i class="fa fa-circle-o-notch fa-spin fa-3x fa-fw"></i><br/><?php echo __("Loading..."); ?></div>
                        <canvas style="border:1px solid #dedddd" id="range_reminders" class="content-white-bkg sb-tour" width="400" height="340"></canvas>
                    </div>
                </div>
                <div class="row stat-count-container">                                  
                    <div class="col-md-2">
                        <div class="stat-calculate" style="">
                            <p><i class="fa fa-clock-o" aria-hidden="true" style="padding-right: 7px;"></i><?php echo __("No. Reminders") ?></p>
                            <h1 class="dfault-0" id="ref_stat_count_range_reminders_all"></h1>
                            <p class="count_veriation" id="var_ref_stat_count_range_reminders_all">                                            
                            </p>
                        </div>
                    </div>                        
                    <div class="col-md-2">
                        <div class="stat-calculate" style="">
                            <p> <i class="fa fa-clock-o" aria-hidden="true" style="padding-right: 7px;"></i><?php echo __("No. Warnings") ?></p>
                            <h1 class="dfault-0" id="ref_stat_count_range_reminders_warrnings"></h1>
                            <p class="count_veriation" id="var_ref_stat_count_range_reminders_warrnings">                                            
                            </p>
                        </div>
                    </div>                        
                    <div class="col-md-2">
                        <div class="stat-calculate" style="">
                            <p> <i class="fa fa-clock-o" aria-hidden="true" style="padding-right: 7px;"></i><?php echo __("No. Done") ?></p>
                            <h1 class="dfault-0" id="ref_stat_count_range_reminders_done"></h1>
                            <p class="count_veriation" id="var_ref_stat_count_range_reminders_done">                                            
                            </p>
                        </div>
                    </div>                        
                    <div class="col-md-2">
                        <div class="stat-calculate" style="background-color:#f8eabb;">
                            <p><i class="fa fa-clock-o" aria-hidden="true" style="padding-right: 7px;"></i><?php echo __("No.Rem. Postponed") ?></p>
                            <h1 class="dfault-0" id="ref_stat_count_range_reminders_postponed"></h1>
                            <p class="count_veriation" id="var_ref_stat_count_range_reminders_postponed">                                            
                            </p>
                        </div>
                    </div>                        
                    <div class="col-md-2">
                        <div class="stat-calculate" style="">
                            <p id=""><i class="fa fa-clock-o" aria-hidden="true" style="padding-right: 7px;"></i><?php echo __("Management Days") ?></p>
                            <h1 class="dfault-0" id="ref_stat_count_range_reminders_management"></h1>
                            <p class="count_veriation" id="var_ref_stat_count_range_reminders_management">
                                
                            </p>
                        </div>
                    </div>                        
                    <div class="col-md-2">
                        <div class="stat-calculate" style="background-color:#f8eabb;">
                            <p><i class="fa fa-clock-o" aria-hidden="true" style="padding-right: 7px;"></i><?php echo __("KPI Reliability") ?></p>
                            <h1 class="dfault-0" id="ref_stat_count_range_reminders_kpi"></h1>
                            <p class="count_veriation" id="var_ref_stat_count_range_reminders_kpi">                                            
                            </p>
                        </div>
                    </div>                                                                        
                </div>
            </div>                                                                    
            <!-- Total Referrers (Only for agents) -->
            <div class="row first-row-feature" style="padding-top:0px;">
                <h3 class="fs-titel stat-headings">                
                    <?php echo __("Referrers Chart") ?>
                </h3>
                <div class="row" style="padding-left:20px;padding-right:20px;padding-top:10px;padding-bottom:10px;">
                    <div class="col-md-12 col-xs-12">                    
                        <table class="table table-bordered" id="total_agent_referrer_charts">
                            <thead>
                                <tr>
                                    <th><?php echo __('ID') ?></th>
                                    <th><?php echo __('Date') ?></th>
                                    <th><?php echo __('Name') ?></th>
                                    <th><?php echo __('Email') ?></th>
                                    <th><?php echo __('Phone') ?></th>
                                    <th><?php echo __('No. Reports') ?></th>                                
                                    <th><?php echo __('Success Reports') ?></th>                                
                                    <th><?php echo __('Commision') ?></th>
                                    <th><?php echo __('Incubation Days') ?></th>
                                </tr>
                            </thead>
                            <tbody id="total_agent_referrer_charts_body">
                            </tbody>
                        </table>
                    </div>
                </div>            
            </div>                                                                                                                                                  
            <!-- Range Referrers (Only for agents) -->
            <div class="row first-row-feature" style="padding-top:0px;">            
                <h3 class="fs-titel stat-headings"><i class="fa fa-clock-o" aria-hidden="true" style="padding-right: 7px;"></i> <?php echo __("Time Range Referrers Chart") ?> <span class='filter-time-stamp'></span></h3>                                      
                <div class="row" style="padding-left:20px;padding-right:20px;padding-top:10px;padding-bottom:10px;">
                    <div class="col-md-12 col-xs-12">                    
                        <table class="table table-bordered" id="range_agent_referrer_charts">
                            <thead>
                                <tr>
                                    <th><?php echo __('ID') ?></th>
                                    <th><?php echo __('Date') ?></th>
                                    <th><?php echo __('Name') ?></th>
                                    <th><?php echo __('Email') ?></th>
                                    <th><?php echo __('Phone') ?></th>
                                    <th><?php echo __('No. Reports') ?></th>                                
                                    <th><?php echo __('Success Reports') ?></th>                                
                                    <th><?php echo __('Commision') ?></th>
                                    <th><?php echo __('Incubation Days') ?></th>
                                </tr>
                            </thead>
                            <tbody id="range_agent_referrer_charts_body">
                            </tbody>
                        </table>
                    </div>
                </div>            
            </div>                                                                                                                                                  
        </div>
    </div>
</div>
<script
      type="text/javascript"
      src="https://cdn.jsdelivr.net/npm/chart.js"
    ></script>
    <script
    src="https://cdnjs.cloudflare.com/ajax/libs/pdf.js/2.6.347/pdf.min.js"
    integrity="sha512-Z8CqofpIcnJN80feS2uccz+pXWgZzeKxDsDNMD/dJ6997/LSRY+W4NmEt9acwR+Gt9OHN0kkI1CTianCwoqcjQ=="
    crossorigin="anonymous"
    referrerpolicy="no-referrer"
  ></script>
  <script
    type="text/javascript"
    src="https://cdnjs.cloudflare.com/ajax/libs/jspdf/1.5.3/jspdf.debug.js"
  ></script>
  <script
    src="https://cdnjs.cloudflare.com/ajax/libs/html2canvas/1.4.1/html2canvas.min.js"
    integrity="sha512-BNaRQnYJYiPSqHHDb58B0yaPfCu+Wgds8Gp/gU33kqBtgNS4tSPHuGibyoeqMV/TJlSKda6FXzoEyYGjTe+vXA=="
    crossorigin="anonymous"
    referrerpolicy="no-referrer"
  ></script>
<script>   
// START Date Picker
        var today = new Date();  // get current date
        var oneYearAgo = new Date();  // create new date object
        oneYearAgo.setFullYear(today.getFullYear() - 1);  // set year to previous year

        if($.datepicker.regional['<?php echo Core_Model_Language::getCurrentLanguageDatepicker(); ?>']) {
            $.datepicker.setDefaults($.datepicker.regional['<?php echo Core_Model_Language::getCurrentLanguageDatepicker(); ?>']);
        } else {
            $.datepicker.setDefaults($.datepicker.regional['en']);
        }

        $("#from").datepicker({
            changeMonth: true,
            changeYear: true,
            numberOfMonths: 3,
            minDate: oneYearAgo,
            onClose: function( selectedDate ) {
                $("#to").datepicker( "option", "minDate", selectedDate );
            }
        });

        $("#to").datepicker({
            changeMonth: true,
            changeYear: true,
            numberOfMonths: 3,
            onClose: function( selectedDate ) {
                $("#from").datepicker( "option", "maxDate", selectedDate );
            }
        });        
        $("#to").datepicker('setDate', new Date());
        $("#from").datepicker('setDate', -30);        
        function computeDateRange() {
                var start_timestamp = parseInt($.datepicker.formatDate( "@", $("#from").datepicker("getDate"))/1000);
                var end_timestamp = parseInt($.datepicker.formatDate( "@", $("#to").datepicker("getDate"))/1000);
                //We go to 23:59
                end_timestamp = end_timestamp + (60*60*24) - 60;
                date_range = {
                    "start": start_timestamp,
                    "end": end_timestamp
                };
                return date_range;

            }    
        var date_range_params='';
        function filterStats() {
        if($("#from").val() && $("#to").val()) {
            date_range_params = computeDateRange();
            if(date_range_params.start <= date_range_params.end) {                
                console.log("DOne");               
            } else {
                var page_message = new AlertMessage("<?php echo __("Start date must be lower than end date."); ?>");
                page_message.addButton(true);
                page_message.setTimer(false);
                page_message.isError(true);
                page_message.show();
            }
        } else {
            var page_message = new AlertMessage("<?php echo __("You have to chose a start and an end date."); ?>");
            page_message.addButton(true);
            page_message.setTimer(false);
            page_message.isError(true);
            page_message.show();
        }
    }
        // END Date Picker
        $(".default-hide").hide();            
        var total_referrers_ctx = $("#total_referrers");
        var total_reports_ctx   = $("#total_reports");
        var range_reports_ctx   = $("#range_reports");
        var total_reminders_ctx = $("#total_reminders");
        var range_reminders_ctx = $("#range_reminders");
        var no_data="<p style='font-weight:700;padding:10px;'>No Data Found!</p>";
        var prev_total_ref_labels = [];
        // Bar Chart Configrations        
        var datasetMeta=[
                {
                    label: 'Current',
                    backgroundColor: "#fbb862",
                    borderColor: "#f59b56",
                    borderWidth: 1,
                    hoverBackgroundColor: "#f59b56",
                    hoverBorderColor: "#fbb862",
                    data: []
                },
                {
                    label: 'Previous',
                    backgroundColor: "#64ad73",
                    borderColor: "#3d9a70",
                    borderWidth: 1,
                    hoverBackgroundColor: "#3d9a70",
                    hoverBorderColor: "#64ad73",
                    data: []
                }
            ]; 
                   
        var lineChartConfig={
                type: 'line',
                data: {
                        labels: [],
                        datasets: datasetMeta
                    },
                options: {
                        "responsive":true,
                        maintainAspectRatio: false,
                        scales: {
                            y: {
                                min: 0,
                                ticks:{
                                    precision:0
                                }                        
                            }
                        },
                        plugins:{
                        tooltip: {
                            callbacks: {
                                title: function(context) {                                
                                if (context[0].datasetIndex===1) {
                                    return prev_total_ref_labels[context[0].dataIndex];
                                }
                                }
                            }
                        }
                    }
                }
        };                                             
        // END line Chart Configrations
        // Bar Chart Configrations
        var barChartOptions={
                "responsive":true,
                maintainAspectRatio: false,
                scales: {
                    y: {
                        min: 0,
                        ticks:{
                            precision:0
                        }                        
                    }
                }
            };                
        var datasetMeta=[
                {
                    label: '<?php echo __("Total Reports"); ?>',
                    backgroundColor: "#fbb862",
                    borderColor: "#f59b56",
                    borderWidth: 1,
                    hoverBackgroundColor: "#f59b56",
                    hoverBorderColor: "#fbb862",
                    data: []
                },
                {
                    label: '<?php echo __("Deal Closed"); ?>',
                    backgroundColor: "#64ad73",
                    borderColor: "#3d9a70",
                    borderWidth: 1,
                    hoverBackgroundColor: "#3d9a70",
                    hoverBorderColor: "#64ad73",
                    data: []
                }
            ]; 
               var totalDatasetMetaRem=[
                {
                    label: '<?php echo __("Total Reminders"); ?>',
                    backgroundColor: "#fbb862",
                    borderColor: "#f59b56",
                    borderWidth: 1,
                    hoverBackgroundColor: "#f59b56",
                    hoverBorderColor: "#fbb862",
                    data: []
                },
                {
                    label: '<?php echo __("Rem. Postponed"); ?>',
                    backgroundColor: "#64ad73",
                    borderColor: "#3d9a70",
                    borderWidth: 1,
                    hoverBackgroundColor: "#3d9a70",
                    hoverBorderColor: "#64ad73",
                    data: []
                },
                {
                    label: '<?php echo __("Total Warnings"); ?>',
                    backgroundColor: "#f44336",
                    borderColor: "#c31407",
                    borderWidth: 1,
                    hoverBackgroundColor: "#c31407",
                    hoverBorderColor: "#f44336",
                    data: []
                }
            ];        
        var rangeDatasetMetaRem=[
                {
                    label: '<?php echo __("Total Reminders"); ?>',
                    backgroundColor: "#fbb862",
                    borderColor: "#f59b56",
                    borderWidth: 1,
                    hoverBackgroundColor: "#f59b56",
                    hoverBorderColor: "#fbb862",
                    data: []
                },
                {
                    label: '<?php echo __("Rem. Postponed"); ?>',
                    backgroundColor: "#64ad73",
                    borderColor: "#3d9a70",
                    borderWidth: 1,
                    hoverBackgroundColor: "#3d9a70",
                    hoverBorderColor: "#64ad73",
                    data: []
                },
                {
                    label: '<?php echo __("Total Warnings"); ?>',
                    backgroundColor: "#f44336",
                    borderColor: "#c31407",
                    borderWidth: 1,
                    hoverBackgroundColor: "#c31407",
                    hoverBorderColor: "#f44336",
                    data: []
                }
            ];               
        var barChartConfig0={
                type: 'bar',
                data: {
                        labels: [],
                        datasets: datasetMeta
                    },
                options: barChartOptions
        };                                             
        var barChartConfig1={
                type: 'bar',
                data: {
                        labels: [],
                        datasets: datasetMeta
                    },
                options: barChartOptions
        };                                             
        var barChartConfig2={
                type: 'bar',
                data: {
                        labels: [],
                        datasets: totalDatasetMetaRem
                    },
                options: barChartOptions
        };                                             
        var barChartConfig3={
                type: 'bar',
                data: {
                        labels: [],
                        datasets: rangeDatasetMetaRem
                    },
                options: barChartOptions
        };                                             
        // END bar Chart Configrations
        // START PIE Chart Configrations
        var pieColorPlate=[
                            '#f44336',
                            '#e91e63',
                            '#3f51b5',
                            '#2196f3',
                            '#9c27b0',
                            '#009688',
                            '#cddc39',
                            '#ffeb3b',
                            '#ff5722',
                            '#9e9e9e'
                        ];
        var pieConfig0={
            type: 'pie',
            data: {
                    labels: [],
                    datasets: [{  
                        label: [],                      
                        data: [],
                        backgroundColor:pieColorPlate ,
                        hoverOffset: 10
                    }]
                },
            options: {
                responsive:true,
                plugins:{
                    legend: {
                    display: false
                    }   
                }                               
            }            
        }; 
        var pieConfig1={
            type: 'pie',
            data: {
                    labels: [],
                    datasets: [{  
                        label: [],                      
                        data: [],
                        backgroundColor: pieColorPlate,
                        hoverOffset: 10
                    }]
                },
            options: {
                responsive:true,
                plugins:{
                    legend: {
                    display: false
                    }   
                }                               
            }            
        }; 
        var pieConfig2={
            type: 'pie',
            data: {
                    labels: [],
                    datasets: [{  
                        label: [],                      
                        data: [],
                        backgroundColor: pieColorPlate,
                        hoverOffset: 10
                    }]
                },
            options: {
                responsive:true,
                plugins:{
                    legend: {
                    display: false
                    }   
                }                               
            }            
        }; 
        var pieConfig3={
            type: 'pie',
            data: {
                    labels: [],
                    datasets: [{  
                        label: [],                      
                        data: [],
                        backgroundColor: pieColorPlate,
                        hoverOffset: 10
                    }]
                },
            options: {
                responsive:true,
                plugins:{
                    legend: {
                    display: false
                    }   
                }                               
            }            
        }; 
        var pieConfig4={
            type: 'pie',
            data: {
                    labels: [],
                    datasets: [{  
                        label: [],                      
                        data: [],
                        backgroundColor: pieColorPlate,
                        hoverOffset: 10
                    }]
                },
            options: {
                responsive:true,
                plugins:{
                    legend: {
                    display: false
                    }   
                }                               
            }            
        }; 
        var pieConfig5={
            type: 'pie',
            data: {
                    labels: [],
                    datasets: [{  
                        label: [],                      
                        data: [],
                        backgroundColor: pieColorPlate,
                        hoverOffset: 10
                    }]
                },
            options: {
                responsive:true,
                plugins:{
                    legend: {
                    display: false
                    }   
                }                               
            }            
        }; 
        // END PIE Chart Configrations
        // Report Range Section
        var total_referrers = new Chart(total_referrers_ctx, lineChartConfig);
        var total_ref_reports = new Chart(total_reports_ctx, barChartConfig0);
        var range_ref_reports = new Chart(range_reports_ctx, barChartConfig1);
        var total_ref_reminders = new Chart(total_reminders_ctx, barChartConfig2);
        var range_ref_reminders = new Chart(range_reminders_ctx, barChartConfig3);
        //  PIE Charts
        // (All) Jobs        
        var jobs_ctx = $("#referrer_jobs");        
        var jobs = new Chart(jobs_ctx, pieConfig0);
        // (All) age        
        var age_ctx = $("#referrer_age");        
        var age = new Chart(age_ctx, pieConfig1);                
        // // (All) region        
        var region_ctx = $("#referrer_region");        
        var region = new Chart(region_ctx, pieConfig2);
        // Range Jobs        
        var range_jobs_ctx = $("#range_referrer_jobs");        
        var range_jobs = new Chart(range_jobs_ctx, pieConfig3);
        // Range age        
        var range_age_ctx = $("#range_referrer_age");        
        var range_age = new Chart(range_age_ctx, pieConfig4);                
        // Range region        
        var range_region_ctx = $("#range_referrer_region");        
        var range_region = new Chart(range_region_ctx, pieConfig5);
        // Empty No Graph
        loadReferrerStats();  
        var is_custome_date_filter=0;
        function filterType() {
            range_filter=$("#range_filter").val();                 
            if (range_filter==100) {
                is_custome_date_filter=1;
                $("#custom_date_filter_container").show();
            }else{
                is_custome_date_filter=0;
                $("#custom_date_filter_container").hide();
            }  
        }
        function loadReferrerStats() {            
            $(".loader_metrics").show();            
            range_filter=$("#range_filter").val();                 
            agent_id=$("#sponsor_filter").val();                 
            filterStats();          
            $(".dfault-0").text(0); //Reset count values to 0                   
            $.ajax({
                method: "POST",
                dataType: 'json',
                url: "/migareference/adminstats/referrerstats",
                data: { app_id: '<?php echo $app_id; ?>', range_filter: range_filter,agent_id:agent_id,date_range_params:date_range_params,is_custome_date_filter:is_custome_date_filter}
            }).done(function( data ) {                            
                $(".filter-time-stamp").text(" ("+'<?php echo __("From") ?>'+": "+data.params.from_date+" "+'<?php echo __("To") ?>'+": "+data.params.to_date+" )");
                    // **********START SECTION 1  (Total Refrrers)*******//                    
                    if (true) { // SubSection 1.1 (Total Ref. Counts) 
                        if (data.tot_count_ref[0].all_ref!==null) {                       
                            $("#gen_stats_count_referrer").text(data.tot_count_ref[0].all_ref);                                                                
                        }
                        if (data.tot_count_ref[0].five_star!==null) {
                            $("#gen_stats_count_5s_referrer").text(data.tot_count_ref[0].five_star);                    
                        }
                        if (data.tot_count_ref[0].four_star!==null) {
                            $("#gen_stats_count_4s_referrer").text(data.tot_count_ref[0].four_star);                    
                        }
                        if (data.tot_count_ref[0].three_star!==null) {
                            $("#gen_stats_count_3s_referrer").text(data.tot_count_ref[0].three_star);                                            
                        }
                        if (data.tot_count_ref[0].kpi!==null) {
                            $("#gen_stats_count_referrer_45_kpi").text(data.tot_count_ref[0].kpi);                    
                        }
                        
                        $("#var_gen_stats_count_5s_referrer").html("").html(data.tot_count_ref[0].five_star_prc);                                                                
                        $("#var_gen_stats_count_4s_referrer").html("").html(data.tot_count_ref[0].four_star_prc);                                                                
                        $("#var_gen_stats_count_3s_referrer").html("").html(data.tot_count_ref[0].three_star_prc);                                                                
                    }
                    if (true) { // SubSection 1.2 (Total Pie Charts)                                            
                        // 1.2.1 Ref. PIE Chart (Total)->JOBS
                        var ref_labels = [];
                        var ref_values = [];                        
                        $.each(data.tot_ref_jobs, function(ind, elem) {
                            if (elem.labels!==null) {
                                ref_labels.push(elem.labels);
                                ref_values.push(elem.job_count);                            
                            }
                        });
                        jobs.data.datasets[0].data = ref_values;                        
                        jobs.data.labels = ref_labels;
                        jobs.update();   
                        if (data.tot_ref_jobs.length) {                            
                            generateLedgends("#referrer_jobs_legends",'jobscustomLegend',jobs);                                                                                                                                                                                           
                        }else{
                            $("#referrer_jobs_legends").html(no_data);                                
                        }  
                        // 1.2.2 Ref. PIE Chart (Total)->AGE                                        
                        var ref_labels = [];
                        var ref_values = [];   
                        var count_age_temp   = 0;                                                                     
                        $.each(data.tot_ref_age, function(ind, elem) {
                            if (elem.labels!==null,elem.age_count!=0) {
                                count_age_temp++;
                                ref_labels.push(elem.labels);
                                ref_values.push(elem.age_count);                            
                            }
                        });
                        age.data.datasets[0].data = ref_values;                        
                        age.data.labels = ref_labels;
                        age.update(); 
                        if (count_age_temp>0) {                            
                            generateLedgends("#referrer_age_legends",'agecustomLegend',age);                                                                           
                        }else{
                            $("#referrer_age_legends").html(no_data);                                
                        }  
                        // 1.2.3 Ref. PIE Chart (Total)->REGION                                                                
                        var ref_labels = [];
                        var ref_values = [];                        
                        $.each(data.tot_ref_region, function(ind, elem) {
                            if (elem.labels!==null) {
                                ref_labels.push(elem.labels);
                                ref_values.push(elem.country_count);                            
                            }
                        });
                        region.data.datasets[0].data = ref_values;                        
                        region.data.labels = ref_labels;
                        region.update();  
                        if (data.tot_ref_region.length) {                            
                            generateLedgends("#referrer_region_legends",'regioncustomLegend',region);                        
                        }else{
                            $("#referrer_region_legends").html(no_data);                                
                        }                                                
                    }
                    // **********END SECTION 1  (Total Refrrers)*******//
                    // **********START SECTION 2  (Range Refrrers)*******//
                    if (true) {// SubSection 2.1 (Range Line Chart)                                
                        // var total_ref_labels = [];
                        var total_ref = [];
                        prev_total_ref_labels = [];
                        var success_ref = [];
                        $.each(data.range_graph_ref, function(ind, elem) {
                            total_ref_labels.push(elem.labels);
                            prev_total_ref_labels.push(elem.prev_labels);
                            total_ref.push(elem.total_ref);
                            success_ref.push(elem.prev_ref);
                        });
                        total_referrers.data.datasets[0].data = total_ref;
                        total_referrers.data.datasets[1].data = success_ref;
                        total_referrers.data.labels           = total_ref_labels;
                        console.log("Check POint");
                        console.log(data.range_graph_ref);
                        total_referrers.update();
                    }
                    if(true) { // SubSection 2.2 (Range Referrers count)
                        if (data.range_count_ref[0].all_ref!==null) {
                            $("#gen_stats_count_range_referrer").text(data.range_count_ref[0].all_ref);                                                                
                        }            
                        $("#var_gen_stats_count_range_referrer").html("").append(data.var_range_count_ref[0].var_all_ref);
                        if (data.range_count_ref[0].five_star!==null) {
                            $("#gen_stats_count_range_5s_referrer").text(data.range_count_ref[0].five_star);                    
                        }
                        $("#var_gen_stats_count_range_5s_referrer").html("").append(data.var_range_count_ref[0].var_five_star);
                        if (data.range_count_ref[0].four_star!==null) {
                            $("#gen_stats_count_range_4s_referrer").text(data.range_count_ref[0].four_star);                    
                        }
                        $("#var_gen_stats_count_range_4s_referrer").html("").append(data.var_range_count_ref[0].var_four_star);                        
                        if (data.range_count_ref[0].three_star!==null) {
                            $("#gen_stats_count_range_3s_referrer").text(data.range_count_ref[0].three_star);                    
                        }
                        $("#var_gen_stats_count_range_3s_referrer").html("").append(data.var_range_count_ref[0].var_three_star);                        
                        
                        $("#gen_stats_count_range_referrer_45_kpi").text(data.range_count_ref[0].kpi);                    
                        $("#var_gen_stats_count_range_referrer_45_kpi").html("").append(data.var_range_count_ref[0].var_kpi);                                                                        
                    }   
                    if (true) { // SubSection 2.3 (Range Pie Charts)                                                                                            
                        // 2.3.1 Ref. PIE Chart (Range)->JOBS                                                                
                        var range_ref_labels = [];
                        var range_ref_values = [];                        
                        $.each(data.range_ref_jobs, function(ind, elem) {
                            if (elem.labels!==null) {
                                range_ref_labels.push(elem.labels);
                                range_ref_values.push(elem.job_count);                            
                            }
                        });
                        range_jobs.data.datasets[0].data = range_ref_values;                        
                        range_jobs.data.labels = range_ref_labels;
                        range_jobs.update();   
                        if (data.range_ref_jobs.length) {
                            generateLedgends("#range_referrer_jobs_legends",'rangejobscustomLegend',range_jobs);                                                                                                
                        }else{
                            $("#range_referrer_jobs_legends").html(no_data);                                
                        }
                        // 2.3.2 Ref. PIE Chart (Range)->age                                                                
                        var range_ref_labels = [];
                        var range_ref_values = [];                                                
                        var count_age_temp   = 0;                                                
                        $.each(data.range_ref_age, function(ind, elem) {
                            if (elem.labels!==null,elem.age_count!=0) {
                                count_age_temp++;
                                range_ref_labels.push(elem.labels);
                                range_ref_values.push(elem.age_count);     
                            }                       
                        });
                        range_age.data.datasets[0].data = range_ref_values;                        
                        range_age.data.labels = range_ref_labels;
                        range_age.update(); 
                        if (count_age_temp>0) {
                            generateLedgends("#range_referrer_age_legends",'rangeagecustomLegend',range_age);                                               
                        }else{                            
                            $("#range_referrer_age_legends").html(no_data);                                
                        }                        
                        // 2.3.3 Ref. PIE Chart (Range)->Region                                                                                        
                        var range_ref_labels = [];
                        var range_ref_values = [];  
                        $.each(data.range_ref_region, function(ind, elem) {
                            if (elem.labels!==null) {
                                range_ref_labels.push(elem.labels);
                                range_ref_values.push(elem.country_count);                            
                            }
                        });
                        range_region.data.datasets[0].data = range_ref_values;                        
                        range_region.data.labels = range_ref_labels;
                        range_region.update();                                                  
                        if (data.range_ref_region.length) {                          
                            generateLedgends("#range_referrer_region_legends",'rangeregioncustomLegend',range_region);                            
                        }else{                                
                            $("#range_referrer_region_legends").html(no_data);                                
                        }                            
                    }
                    // **********END SECTION 2  (Range Refrrers)*******//
                    // **********START SECTION 3  (Total Report)*******//
                    if (true) { // SubSection 3.1 (Total Reports Chart)                                
                        var total_scussess_labels = [];
                        var total_reports = [];
                        var success_reports = [];
                        $.each(data.total_graph_reports, function(ind, elem) {
                            total_scussess_labels.push(elem.labels);
                            total_reports.push(elem.total_reports);
                            success_reports.push(elem.success_reports);
                        });
                        total_ref_reports.data.datasets[0].data = total_reports;
                        total_ref_reports.data.datasets[1].data = success_reports;
                        total_ref_reports.data.labels = total_scussess_labels;
                        total_ref_reports.update();                        
                    }
                    if (true) { // SubSection 3.2 (Total Reports COUNT)                                                        
                        $("#ref_stat_count_total_reports_all").text(data.total_count_reports[0].total_reports);
                        $("#ref_stat_count_total_reports_success").text(data.total_count_reports[0].success_reports);                                            
                        $("#ref_stat_count_total_reports_incubation").text(data.total_count_reports[0].incubation);                        
                        $("#ref_stat_count_total_reports_commission_label").text(data.total_count_reports[0].earn_label);                                                
                        $("#ref_stat_count_total_reports_commission").text(data.total_count_reports[0].earn_amount);                                                                        
                        $("#ref_stat_count_total_reports_kpi").text(data.total_count_reports[0].kpi);                                                
                    }
                    // **********END SECTION 3  (Total Report)*******//                                
                    // **********START SECTION 4  (Range Report)*******//
                    if (true) { // SubSection 4.1 (Range Reports Chart)                                
                        var range_scussess_labels = [];
                        var range_reports = [];
                        var success_reports = [];
                        $.each(data.range_graph_reports, function(ind, elem) {
                            range_scussess_labels.push(elem.labels);
                            range_reports.push(elem.total_reports);
                            success_reports.push(elem.success_reports);
                        });
                        range_ref_reports.data.datasets[0].data = range_reports;
                        range_ref_reports.data.datasets[1].data = success_reports;
                        range_ref_reports.data.labels = range_scussess_labels;
                        range_ref_reports.update();                     
                    }
                    if (true) { // SubSection 4.2 (Range Reports COUNT)                                
                        $("#ref_stat_count_range_reports_all").text(data.range_count_reports[0].total_reports);                                                                
                        $("#var_ref_stat_count_range_reports_all").html("").append(data.var_range_count_reports[0].var_total_reports);

                        $("#ref_stat_count_range_reports_success").text(data.range_count_reports[0].success_reports);                    
                        $("#var_ref_stat_count_range_reports_success").html("").append(data.var_range_count_reports[0].var_success_reports);

                        $("#ref_stat_count_range_reports_incubation").text(data.range_count_reports[0].incubation);                    
                        $("#var_ref_stat_count_range_reports_incubation").html("").append(data.var_range_count_reports[0].var_incub_reports);
                        
                        $("#ref_stat_count_range_reports_commission_label").text(data.range_count_reports[0].earn_lable);                    
                        $("#ref_stat_count_range_reports_commission").text(data.range_count_reports[0].earn_amount);                    
                        $("#var_ref_stat_count_range_reports_commission").html("").append(data.var_range_count_reports[0].var_earn_reports);                        
                        
                        $("#ref_stat_count_range_reports_kpi").text(data.range_count_reports[0].kpi);                    
                        $("#var_ref_stat_count_range_reports_kpi").html("").append(data.var_range_count_reports[0].var_kpi_reports);                                                
                        
                    }
                    // **********END SECTION 4  (Range Report)*******//                                                          
                    // **********START SECTION 5  (Total Reminders)*******//
                    if (true) { // SubSection 5.1 (Total Reminders Chart)                                
                        var total_scussess_labels = [];
                        var total_reminders = [];
                        var warrnings = [];
                        var postponed = [];
                        $.each(data.total_graph_reminders, function(ind, elem) {
                            total_scussess_labels.push(elem.labels);
                            total_reminders.push(elem.total_reminders);
                            warrnings.push(elem.warrnings);
                            postponed.push(elem.postponed);
                        });
                        total_ref_reminders.data.datasets[0].data = total_reminders;
                        total_ref_reminders.data.datasets[1].data = warrnings;
                        total_ref_reminders.data.datasets[2].data = postponed;
                        total_ref_reminders.data.labels = total_scussess_labels;
                        total_ref_reminders.update();
                    }
                    if (true) { // SubSection 5.2 (Total Reminders COUNT)                                                        
                        $("#ref_stat_count_total_reminders_all").text(data.total_count_reminders[0].total_reminders);
                        $("#ref_stat_count_total_reminders_warrnings").text(data.total_count_reminders[0].warrnings);                                            
                        $("#ref_stat_count_total_reminders_done").text(data.total_count_reminders[0].done);                                            
                        $("#ref_stat_count_total_reminders_potponed").text(data.total_count_reminders[0].potponed);                                                
                        $("#ref_stat_count_total_reminders_managment").text(data.total_count_reminders[0].management);                                                                        
                        $("#ref_stat_count_total_reminders_kpi").text(data.total_count_reminders[0].kpi);                                                
                    }
                    // **********END SECTION 5  (Total Reminders)*******//                                                                                          
                    // **********START SECTION 6  (Range Reminders)*******//
                    if (true) { // SubSection 6.1 (Range Reminders Chart)                                
                        var range_scussess_labels = [];
                        var total_reminders = [];
                        var warrnings = [];
                        var postponed = [];
                        $.each(data.range_graph_reminders, function(ind, elem) {
                            range_scussess_labels.push(elem.labels);
                            total_reminders.push(elem.total_reminders);
                            warrnings.push(elem.warrnings);
                            postponed.push(elem.postponed);
                        });
                        range_ref_reminders.data.datasets[0].data = total_reminders;
                        range_ref_reminders.data.datasets[1].data = warrnings;
                        range_ref_reminders.data.datasets[2].data = postponed;
                        range_ref_reminders.data.labels = range_scussess_labels;
                        range_ref_reminders.update();
                    }
                    if (true) { // SubSection 6.2 (Range Reminders COUNT)                                
                        $("#ref_stat_count_range_reminders_all").text(data.range_count_reminders[0].total_reminders);                                                                
                        $("#var_ref_stat_count_range_reminders_all").html("").append(data.var_range_count_reminders[0].var_total_reminders);

                        $("#ref_stat_count_range_reminders_warrnings").text(data.range_count_reminders[0].warrnings);                    
                        $("#var_ref_stat_count_range_reminders_warrnings").html("").append(data.var_range_count_reminders[0].var_warrnings);

                        $("#ref_stat_count_range_reminders_done").text(data.range_count_reminders[0].done);                    
                        $("#var_ref_stat_count_range_reminders_done").html("").append(data.var_range_count_reminders[0].var_done);

                        $("#ref_stat_count_range_reminders_postponed").text(data.range_count_reminders[0].potponed);                    
                        $("#var_ref_stat_count_range_reminders_postponed").html("").append(data.var_range_count_reminders[0].var_potponed);
                        
                        $("#ref_stat_count_range_reminders_management").text(data.range_count_reminders[0].management);                                            
                        $("#var_ref_stat_count_range_reminders_management").html("").append(data.var_range_count_reminders[0].var_management);                        
                        
                        $("#ref_stat_count_range_reminders_kpi").text(data.range_count_reminders[0].kpi);                    
                        $("#var_ref_stat_count_range_reminders_kpi").html("").append(data.var_range_count_reminders[0].var_kpi);                                                
                    }
                    // **********END SECTION 6  (Range Reminders)*******//                                                                                          
                    $(".loader_metrics").hide();                    
                    // Background Print WOrk
                    const divElement = document.getElementById('pagecontainer');
                    // Get the innerHTML of the div element
                    const htmlContent = divElement.innerHTML;
                    $("#newcontent").remove();
                    // Create a new element to pass the same data
                    newElement = document.createElement('div');
                    newElement.setAttribute('id', 'newcontent');
                    newElement.style.width = '1284px';
                    newElement.style.marginLeft = '200px';
                    newElement.style.position = "absolute";
                    newElement.style.bottom = "100%";
                    newElement.innerHTML = htmlContent;
                    // Get the duplicated chart canvas and chart instance
                    duplicateChartCanvas = newElement.querySelector('#referrer_jobs');
                    duplicateChart = new Chart(duplicateChartCanvas, {
                        type: jobs.config.type,
                        data: jobs.config.data,
                        options: jobs.config.options
                    });
                    duplicateChartCanvas = newElement.querySelector('#referrer_age');
                    duplicateChart = new Chart(duplicateChartCanvas, {
                        type: age.config.type,
                        data: age.config.data,
                        options: age.config.options
                    });
                    duplicateChartCanvas = newElement.querySelector('#referrer_region');
                    duplicateChart = new Chart(duplicateChartCanvas, {
                        type: region.config.type,
                        data: region.config.data,
                        options: region.config.options
                    });
                    duplicateChartCanvas = newElement.querySelector('#range_referrer_jobs');
                    duplicateChart = new Chart(duplicateChartCanvas, {
                        type: range_jobs.config.type,
                        data: range_jobs.config.data,
                        options: range_jobs.config.options
                    });
                    duplicateChartCanvas = newElement.querySelector('#range_referrer_age');
                    duplicateChart = new Chart(duplicateChartCanvas, {
                        type: range_age.config.type,
                        data: range_age.config.data,
                        options: range_age.config.options
                    });
                    duplicateChartCanvas = newElement.querySelector('#range_referrer_region');
                    duplicateChart = new Chart(duplicateChartCanvas, {
                        type: range_region.config.type,
                        data: range_region.config.data,
                        options: range_region.config.options
                    });
                    duplicateChartCanvas = newElement.querySelector('#total_referrers');
                    duplicateChart = new Chart(duplicateChartCanvas, {
                        type: total_referrers.config.type,
                        data: total_referrers.config.data,
                        options: total_referrers.config.options
                    });
                    duplicateChartCanvas.style.height='348px';
                    duplicateChartCanvas = newElement.querySelector('#total_reports');
                    duplicateChart = new Chart(duplicateChartCanvas, {
                        type: total_ref_reports.config.type,
                        data: total_ref_reports.config.data,
                        options: total_ref_reports.config.options
                    });
                    duplicateChartCanvas.style.height='348px';
                    duplicateChartCanvas = newElement.querySelector('#range_reports');
                    duplicateChart = new Chart(duplicateChartCanvas, {
                        type: range_ref_reports.config.type,
                        data: range_ref_reports.config.data,
                        options: range_ref_reports.config.options
                    });
                    duplicateChartCanvas.style.height='348px';
                    duplicateChartCanvas = newElement.querySelector('#total_reminders');
                    duplicateChart = new Chart(duplicateChartCanvas, {
                        type: total_ref_reminders.config.type,
                        data: total_ref_reminders.config.data,
                        options: total_ref_reminders.config.options
                    });
                    duplicateChartCanvas.style.height='348px';
                    duplicateChartCanvas = newElement.querySelector('#range_reminders');
                    duplicateChart = new Chart(duplicateChartCanvas, {
                        type: range_ref_reminders.config.type,
                        data: range_ref_reminders.config.data,
                        options: range_ref_reminders.config.options
                    });
                    duplicateChartCanvas.style.height='348px';
                    from_date=$("#from").val();
                    to_date=$("#to").val();    
                    sponsor_filter=$("#sponsor_filter").val();    
                    myDropdown = newElement.querySelector('#range_filter');
                    optionWithValue100 = myDropdown.querySelector(`option[value="${range_filter}"]`);
                    myDropdown = newElement.querySelector('#sponsor_filter');
                    optionWithValue100 = myDropdown.querySelector(`option[value="${sponsor_filter}"]`);
                    optionWithValue100.selected = true;
                    fromInput = newElement.querySelector('#from');                    
                    fromInput.setAttribute('value', from_date);
                    toInput = newElement.querySelector('#to');
                    toInput.setAttribute('value', to_date);     
                    document.body.appendChild(newElement);
                    loadAgentReferrers();
                    loadRangeAgentReferrers(range_filter);
            }).error(function() {            
                $("#range_reports_loader").hide();
            });
        }      
        
        // START: Bind PIE Chart legend events
        function generateLedgends(chartBoxID,childBoxId,chrtobj) {        
        $(chartBoxID).html("");
        const chartBox = document.querySelector(chartBoxID);        
        const div = document.createElement("DIV");
        div.setAttribute("id", childBoxId);
        const ul = document.createElement("UL");        
        chrtobj.legend.legendItems.forEach((dataset, index) => {            
          const text = dataset.text;
          const datasetIndex = dataset.datasetIndex;
          const bgColor = dataset.fillStyle;
          const bColor = dataset.strokeStyle;
          const fontColor = dataset.fontColor;
          const li = document.createElement("LI");
          const spanBox = document.createElement("SPAN");
          const spanBoxx = document.createElement("P");
          ul.style.padding='5px';
          li.style.marginRight='4px';
          spanBox.style.borderColor = bColor;
          spanBox.style.backgroundColor = bgColor;
          spanBox.style.width = '12px';
          spanBox.style.borderRadius = '0px';          
          spanBoxx.style.margin = '0px';          
          const textNode = document.createTextNode(text);          
          li.onclick = (click) => {                                  
            chrtobj.toggleDataVisibility(dataset.index);            
            updateLegend(click,chrtobj);
          };
          ul.appendChild(li);
          li.appendChild(spanBoxx);          
          spanBoxx.appendChild(spanBox);          
          spanBoxx.appendChild(textNode);
        });
        function updateLegend(click,chrtobj) {
          const element = click.target.parentNode;
          element.classList.toggle("hidden-pie-label");
          chrtobj.update();
        }
        // Append in DIV
        chartBox.appendChild(div);
        div.appendChild(ul);
      }  
        //   Agent Table  //
        var dataTableLanguage = {
                "decimal": "",
                "emptyTable": "<?php echo __js("No data found") ?>",
                "info": "<?php echo __js("Showing _START_ to _END_ of _TOTAL_ entries") ?>",
                "infoEmpty": "<?php echo __js("Showing 0 to 0 of 0 entries") ?>",
                "infoFiltered": "<?php echo __js("(filtered from _MAX_ total entries)") ?>",
                "infoPostFix": "",
                "thousands": ",",
                "loadingRecords": "<?php echo __js("Loading...") ?>",
                "processing": "<?php echo __js("Processing...") ?>",
                "search": "<?php echo __js("Search: ") ?>",
                "zeroRecords": "<?php echo __js("No matching records found") ?>",
                "paginate": {
                    "first": "<?php echo __js("First") ?>",
                    "last": "<?php echo __js("Last") ?>",
                    "next": "<?php echo __js("Next") ?>",
                    "previous": "<?php echo __js("Previous") ?>"
                },
                "aria": {
                    "sortAscending": "<?php echo __js(": activate to sort column ascending") ?>",
                    "sortDescending": "<?php echo __js(": activate to sort column descending") ?>"
                }
            };            
            function loadAgentReferrers() {
                $("#total_agent_referrer_charts").DataTable().destroy();
                $('#total_agent_referrer_charts:eq(1)').DataTable().destroy();
                $('#total_agent_referrer_charts,#total_agent_referrer_charts:eq(1)').dataTable({
                order: [[5, 'desc']],
                language: dataTableLanguage,
                bLengthChange: false,
                bFilter: true,
                sPaginationType: "full_numbers",
                fnDrawCallback: function (nRow, aData, iDisplayIndex, iDisplayIndexFull) {
                    $.each(nRow.aoData, function (i, el) {
                        var tr = $(el.nTr);
                        tr.unbind('click');
                    }.bind(this));
                    $('.paginate_button').addClass('btn color-blue').attr('data-html2canvas-ignore','true');
                    $('.dataTables_filter').attr('data-html2canvas-ignore','true');
                    $('.dataTables_info').attr('data-html2canvas-ignore','true');
                },
                dom: 'Bfrtip',
                    buttons: {
                            buttons: [
                                { extend: 'csv',
                                     className: 'btn btn-lg btn-xs btn-success right-side',
                                     text: '<i class="fa fa-download" aria-hidden="true"></i> CSV', 
                                    attr:{
                                        'data-html2canvas-ignore':'true'
                                    } 
                                },                                
                              ]
                            },
                ajax : '<?php echo $this->getUrl('migareference/adminstats/agenttotalreports?app_id='.$app_id.'&range_filter='); ?>'+range_filter+'&agent_id='+agent_id,                
            });            
            }
            function loadRangeAgentReferrers(range_filter) {                
                $("#range_agent_referrer_charts").DataTable().destroy();   
                $('#range_agent_referrer_charts:eq(1)').DataTable().destroy();             
                $('#range_agent_referrer_charts,#range_agent_referrer_charts').dataTable({
                order: [[5, 'desc']],
                language: dataTableLanguage,
                bLengthChange: false,
                bFilter: true,
                sPaginationType: "full_numbers",
                fnDrawCallback: function (nRow, aData, iDisplayIndex, iDisplayIndexFull) {
                    $.each(nRow.aoData, function (i, el) {
                        var tr = $(el.nTr);
                        tr.unbind('click');
                    }.bind(this));
                    $('.paginate_button').addClass('btn color-blue').attr('data-html2canvas-ignore','true');
                    $('.dataTables_filter').attr('data-html2canvas-ignore','true');
                    $('.dataTables_info').attr('data-html2canvas-ignore','true');
                },
                dom: 'Bfrtip',
                    buttons: {
                            buttons: [
                                { extend: 'csv',
                                     className: 'btn btn-lg btn-xs btn-success right-side',
                                     text: '<i class="fa fa-download" aria-hidden="true"></i> CSV', 
                                    attr:{
                                        'data-html2canvas-ignore':'true'
                                    } 
                                },                                
                              ]
                            },
                ajax : '<?php echo $this->getUrl('migareference/adminstats/agentrangereports?app_id='.$app_id.'&range_filter='); ?>'+range_filter+'&agent_id='+agent_id+"&date_range_start="+date_range_params.start+"&date_range_end="+date_range_params.end,                
            });            
            }
    function printPdf() {     
      $("#pdf_download_loader").show();   
      const doc = new jsPDF();            
      html2canvas(newElement.querySelector("#content")).then((canvas) => {
        var imgData    = canvas.toDataURL();
        var imgWidth   = 210; 
        var pageHeight = 295;  
        var imgHeight  = canvas.height * imgWidth / canvas.width;
        var heightLeft = imgHeight;        
        var doc        = new jsPDF('p', 'mm');
        var position   = 3; // give some top padding to first page
        doc.addImage(imgData, 'JPEG', 0, position, imgWidth, imgHeight);
        heightLeft -= pageHeight;        
        while (heightLeft >= 0) {
        position = heightLeft - imgHeight; // top padding for other pages        
        doc.addPage();
        doc.addImage(imgData, 'JPEG', 0, position, imgWidth, imgHeight);
        heightLeft -= pageHeight;
        }
        doc.save('General Stats.pdf');
        $("#pdf_download_loader").hide();
      });
    }
</script>
<style>
/* Stat CSS */
.stat-calculate{
    padding-top: 8px;
    padding-bottom: 8px;
    border-radius: 7px;
    background: #f7f7f7;
    text-align: center;
    transition: transform .7s;
}
.stat-calculate:hover {      
    -webkit-transform: scale(1.2);
    -moz-transform: scale(1.2);
    -ms-transform: scale(1.2);
    -o-transform: scale(1.2);
    transform: scale(1.2);    
    background: #9797974a;
}
.stat-calculate h1{
    font-weight:700;
    margin-top:18px;
    margin-bottom:21px;
    line-height:40px;

}
.stat-calculate p{
    font-weight:700;
    /* font-size:1vw; */
    line-height:20px;
    overflow:hidden;
}
.count_veriation{
    font-size:small;
}
.count_veriation span{
    font-size:small;
    /* font-size:1vw; */
}
.var-positive {
    background: #87d82757;
    padding: 2px;
    border-radius: 10px;
    color: green;
    font-weight: 700;
}
.var-negative {
    background: #d827272e;
    padding: 2px;
    border-radius: 10px;
    color: #e91e63;
    font-weight: 700;
}
.var-nochange {
    background: #0000003d;
    padding: 2px;
    border-radius: 10px;
    font-weight: 700;
}
.stat-headings{
    color: white;
    background-color: #0099C7;
    padding: 9px;
    margin-top: 14px;
    margin-bottom: 14px;
    margin-left: 20px;
    margin-right: 20px;
}
.stat-count-container{
    border: 1px solid #d0cfcf;
    margin-left: 20px;
    margin-right: 20px;
    padding-bottom: 15px;
    padding-top: 14px;
}
/* Pie CHart */
.pie-chart-legend ul>li span{
    display: inline-block;    
    width: 12px;
    height: 12px;
    margin-right: 5px;
}
.pie-chart-legend ul>li {
    display: inline-block;  
    margin: 4px;  
}

.pie-chart-legend{
  height:115px;
  
}
.hidden-pie-label {
  text-decoration: line-through;
}
/* START Data Table  style*/
.sub_heading{
        border-bottom: 2px solid #0099c7;
        padding-bottom: 13px;
    }
    .remove_btn{
        background-color: red;
    }
    .emptydataset{
        text-align: center;
    }
table{
    background-color: white;
}
     table.dataTable {
                margin: 20px 0 10px;
                width: 100% !important;
            }

            table.dataTable th {
                text-align: left;
            }
            table.dataTable tbody tr.edit_product {
                cursor: pointer;
            }

            .dataTables_info {
                float: left;
                padding: 10px;
            }

            .dataTables_paginate {
                float: right;
            }

            .dataTables_paginate a {
                display: block;
                float: left;
                margin-left: 4px;
                padding: 6px;
            }

            .dataTables_paginate a.paginate_button_disabled {
                opacity: 0.3
            }

            .dataTable tbody tr:last-of-type {
                border-bottom: 0;
            }

            #migasms {
                overflow: auto;
            }
            #contantcontainer {
                border-radius: 0px !important;
            }
            #contentheader{
              background-color: #f3f3f3 !important;
              padding: 8px !important;
            }
            #contentfooter{
              padding: 5px !important;
            }
            .right-side{
              float: right;
              margin-right: 5px;
            }
            #delbtn{
              float: right;
            }
            #delbtner{
              float: right;
            }
/* END Data Table  style*/
#row_filter_metrics label{line-height:29px}

</style>