<?php
$application = $this->getApplication();
$app_id      = $application->getId();
$migareference  = new Migareference_Model_Migareference();    
$referrerstats  = new Migareference_Model_Referrerstats();                
$referral_usrs  = $migareference->get_referral_users($app_id);
$agents         = $migareference->get_customer_agents($app_id);
$default        = new Core_Model_Default();
$base_url       = $default->getBaseUrl();
$from_date      = date("Y-m-d", strtotime("-36 months"));
$to_date        = date('Y-m-d', strtotime(' +1 day'));
$tot_count_region = $referrerstats->countReferrerRegionsGnl($app_id,$from_date,$to_date);                                                
?>
<script type="text/javascript" language="javascript" src="https://cdn.datatables.net/1.10.19/js/jquery.dataTables.min.js"></script>
<script type="text/javascript" language="javascript" src="https://cdn.datatables.net/buttons/1.5.2/js/dataTables.buttons.min.js"></script>
<script type="text/javascript" language="javascript" src="https://cdn.datatables.net/buttons/1.5.2/js/buttons.flash.min.js"></script>
<script type="text/javascript" language="javascript" src="https://cdnjs.cloudflare.com/ajax/libs/jszip/3.1.3/jszip.min.js"></script>
<script type="text/javascript" language="javascript" src="https://cdnjs.cloudflare.com/ajax/libs/pdfmake/0.1.36/pdfmake.min.js"></script>
<script type="text/javascript" language="javascript" src="https://cdnjs.cloudflare.com/ajax/libs/pdfmake/0.1.36/vfs_fonts.js"></script>
<script type="text/javascript" language="javascript" src="https://cdn.datatables.net/buttons/1.5.2/js/buttons.html5.min.js"></script>
<script type="text/javascript" language="javascript" src="https://cdn.datatables.net/buttons/1.5.2/js/buttons.print.min.js"></script>

<div id="pagecontainer">
    <!-- Forground Start -->
    <div class="application_analytics application content" id="content">
        <h3 class="title-editor border-blue text-center"><?php echo __("Migareference General Stats") ?><span class='filter-time-stamp'></span></h3>
        <div class="container-fluid subcontent content-color">        
		<ul class="nav nav-tabs" role="tablist" data-html2canvas-ignore="true" style="margin-bottom:10px;">
				<li role="presentation" class="active">
                    <a href="<?=$base_url."/migareference/generalstats/general"?>">
                        <?php echo __("General") ?>
                    </a>
                </li>
				<li role="presentation">
					<a href="<?=$base_url."/migareference/prospectstats/prospect" ?>">
                        <?php echo __("Prospecting") ?>
                    </a>
                </li>
				<li role="presentation">
                    <a href="<?=$base_url."/migareference/reportstats/report" ?>">
                        <?php echo __("Reports") ?>
                    </a>
                </li>
				<li role="presentation" >
                    <a href="<?=$base_url."/migareference/followupstats/followup" ?>">
                        <?php echo __("Followup") ?>
                    </a>
                </li>
				<li role="presentation" >
                    <a href="<?=$base_url."/migareference/referrerstats/referrer" ?>">
                        <?php echo __("Referrers") ?>
                    </a>
                </li>
                <!-- <li role="presentation" >
                    <a href="<?=$base_url."/migareference/adminstats/admin" ?>">
                        <?php echo __("Agent") ?>
                    </a>
                </li>
                <li role="presentation" >
                    <a href="<?=$base_url."/migareference/referrerstats/referrer" ?>">
                        <?php echo __("Referrers") ?>
                    </a>
                </li>      -->
                <li style="float:right;">
                    <button class="btn color-blue" onclick="printPdf()">
                        <i class="fa fa-download"></i>
                        <?php echo __("PDF") ?>
                        <span style="display:none;" id="pdf_download_loader"><i class="fa fa-circle-o-notch fa-spin fa-fw"></i></span>
                    </button>
                </li>               
            </ul>                 
            <!-- Filter Start -->
            <div class="row">
                <div class="col-md-2" style="padding-bottom:3px;">
                    <select onChange="filterType()" id="range_filter" class="input-flat" name="">
						<option value="6"><?php echo __("ALL") ?></option> 
						<option value="8"><?php echo __("Past Week") ?></option> 
                        <option selected value="1"><?php echo __("Last 30 Days") ?></option> 
						<option value="7"><?php echo __("Past Month") ?></option>                           
                        <option value="2"><?php echo __("Last 3 Months") ?></option>                            
                        <option value="3"><?php echo __("Last 6 Months") ?></option>                            
                        <option value="4"><?php echo __("Current Year") ?></option>                            
                        <option value="5"><?php echo __("Last Year") ?></option>                                                      
                        <option style="font-weight:600" value="100"><?php echo __("Custom Range") ?></option>                            
                    </select>
                </div>            
                <div class="col-md-5" id="custom_date_filter_container" style="display:none;">                
                    <div id="row_filter_metrics" class="row sb-tour">
                        <div class="col-md-2 col-sm-6 col-xs-6">
                            <label for="from"><?php echo __("From"); ?></label>
                        </div>
                        <div class="col-md-4 col-sm-6 col-xs-6">
                            <input type="text" id="from" name="from" class="input-flat sb-tour">
                        </div>
                        <div class="col-md-2 col-sm-6 col-xs-6">
                            <label for="to"><?php echo __("To"); ?></label>
                        </div>
                        <div class="col-md-4 col-sm-6 col-xs-6">
                            <input type="text" id="to" name="to" class="input-flat sb-tour">
                        </div>                    
                    </div>
                </div>
                <div class="col-md-1">                
                    <button data-html2canvas-ignore="true" class="btn color-blue" onclick="loadReferrerStats()">                    
                        <?php echo __("Filter Stats") ?>                    
                    </button>
                </div>                              
            </div>        
            <!-- (All) Referers -->
            <div class="row first-row-feature" style="padding-top:0px;">
                <h3 class="fs-titel stat-headings"></i> <?php echo __("Referrers") ?></h3> 
				<div style="margin-left:49%;" id="total_referrers_loader" class="loader_metrics"><i class="fa fa-circle-o-notch fa-spin fa-3x fa-fw"></i><br/><?php echo __("Loading..."); ?></div>
				<div class="row stat-count-container">
                    <div class="col-md-1">                                    
                    </div>               
                    <div class="col-md-2">
                        <div class="stat-calculate" style="">
                            <p><i class="fa fa-clock-o" aria-hidden="true" style="padding-right: 1px;"></i>
                            <?php echo __("No. Referrers") ?></p>
                            <h1 class="dfault-0" id="gen_stats_count_range_referrer"></h1>
                            <p class="count_veriation" id="var_gen_stats_count_range_referrer">                                            
                            </p>
                        </div>
                    </div>                        
                    <div class="col-md-2">
                        <div class="stat-calculate" style="">
                            <p><i class="fa fa-clock-o" aria-hidden="true" style="padding-right: 1px;"></i>
                            <?php echo __("5 Stars Referrers") ?></p>
                            <h1 class="dfault-0" id="gen_stats_count_range_5s_referrer"></h1>
                            <p class="count_veriation" id="var_gen_stats_count_range_5s_referrer">                                             
                            </p>
                        </div>
                    </div>                        
                    <div class="col-md-2">
                        <div class="stat-calculate" style="">
                            <p><i class="fa fa-clock-o" aria-hidden="true" style="padding-right: 1px;"></i>
                            <?php echo __("4 Stars Referrers") ?></p>
                            <h1 class="dfault-0" id="gen_stats_count_range_4s_referrer"></h1>
                            <p class="count_veriation" id="var_gen_stats_count_range_4s_referrer">                                            
                            </p>
                        </div>
                    </div>                                                                
                    <div class="col-md-2">
                        <div class="stat-calculate" style="">
                            <p><i class="fa fa-clock-o" aria-hidden="true" style="padding-right: 1px;"></i> <?php echo __("3 Stars Referrers") ?></p>
                            <h1 class="dfault-0" id="gen_stats_count_range_3s_referrer"></h1>
                            <p class="count_veriation" id="var_gen_stats_count_range_3s_referrer">                                            
                            </p>
                        </div>
                    </div>                                                                
                    <div class="col-md-2">
                        <div class="stat-calculate" style="background-color:#f8eabb;cursor:pointer;" rel="tooltip" title="<?php echo __('Recruitment quality indicator. Good recruitment must produce at least 0.15 (15%) good Referrers.') ?>">
                            <p><i class="fa fa-clock-o" aria-hidden="true" style="padding-right: 1px;"></i>
                            <?php echo __("3/4/5 Star KPI") ?> <i class="fa fa-info-circle" aria-hidden="true" style="padding-left: 1px; color: rgb(129, 133, 137, 0.2);" ></i></p>
                            <h1 class="dfault-0" id="gen_stats_count_range_referrer_45_kpi"></h1>
                            <p class="count_veriation" id="var_gen_stats_count_range_referrer_45_kpi">                                            
                            </p>
                        </div>
                    </div>                                        
                    <div class="col-md-1">                                    
                    </div>                                                        
                </div>   
				<div class="row" style="padding-left:20px;padding-right:20px;padding-top:10px;padding-bottom:10px;">
                    <div class="col-md-12 col-xs-12" style="max-height:348px">
                        <canvas style="border:1px solid #dedddd"  id="total_referrers" class="content-white-bkg sb-tour" width="400" height="340"></canvas>
                    </div>
                </div>    
				<div class="row stat-count-container">
                    <div class="col-md-3" style="overflow:hidden;padding-right:0;padding-left:0">
                        <p style='font-weight:700;text-align:center;' ><i class="fa fa-clock-o" aria-hidden="true" style="padding-right: 1px;"></i>
                        <?php echo __("Best 10 Jobs"); ?>
                        </p>
                        <div style="background:white;padding:0;text-align:center;" class='pie-chart-legend' id="range_referrer_jobs_legends"></div>
                        <div style="padding-right:21%;padding-left:21%;padding-bottom:2%;background:white;">
                            <canvas style="width:100%" id="range_referrer_jobs" class="content-white-bkg sb-tour"></canvas>    
                        </div>
                    </div>
					<div class="col-md-3" style="overflow:hidden;padding-right:0;padding-left:0">
                        <p style='font-weight:700;text-align:center;' ><i class="fa fa-clock-o" aria-hidden="true" style="padding-right: 1px;"></i>
                        <?php echo __("Sector"); ?>
                        </p>
                        <div style="background:white;padding:0;text-align:center;" class='pie-chart-legend' id="range_referrer_sectors_legends"></div>
                        <div style="padding-right:21%;padding-left:21%;padding-bottom:2%;background:white;">
                            <canvas style="width:100%" id="range_referrer_sectors" class="content-white-bkg sb-tour"></canvas>    
                        </div>
                    </div>
                    <div class="col-md-3" style="overflow:hidden;padding-right:0;padding-left:0">
                        <p style='font-weight:700;text-align:center;'><i class="fa fa-clock-o" aria-hidden="true" style="padding-right: 1px;"></i>
                        <?php echo __("Age Group") ?></p>
                        <div style="background:white;padding:0;text-align:center;" class='pie-chart-legend' id="range_referrer_age_legends"></div>
                        <div style="padding-right:21%;padding-left:21%;padding-bottom:2%;background:white;">
                        <canvas style="width:100%" id="range_referrer_age" class="content-white-bkg sb-tour"></canvas>    
                        </div>
                    </div>
                    <div class="col-md-3" style="overflow:hidden;padding-right:0;padding-left:0">
                        <p style='font-weight:700;text-align:center;' id="range_referrer_region_label"><i class="fa fa-clock-o" aria-hidden="true" style="padding-right: 1px;"></i>
                        <?php echo __("Best 10 Regions") ?></p>
                        <div style="background:white;padding:0;text-align:center;" class='pie-chart-legend' id="range_referrer_region_legends"></div>
                        <div style="padding-right:21%;padding-left:21%;padding-bottom:2%;background:white;">
                        <canvas style="width:100%" id="range_referrer_region" class="content-white-bkg sb-tour"></canvas>    
                        </div>
                    </div>
                </div>                                          
                <!-- <div class="row stat-count-container">
                    <div class="col-md-1">                                    
                    </div>               
                    <div class="col-md-2">
                        <div class="stat-calculate" style="">
                            <p>
                            <?php echo __("No. Referrers") ?></p>
                            <h1 class="dfault-0" id="gen_stats_count_referrer"></h1>
                            <p style="height:20px" class="count_veriation" id="var_gen_stats_count_referrer">                                            
                            </p>
                        </div>
                    </div>                        
                    <div class="col-md-2">
                        <div class="stat-calculate" style="">
                            <p>
                            <?php echo __("5 Stars Referrers") ?></p>
                            <h1 class="dfault-0" id="gen_stats_count_5s_referrer"></h1>
                            <p style="height:20px" class="count_veriation" id="var_gen_stats_count_5s_referrer">                                             
                            </p>
                        </div>
                    </div>                        
                    <div class="col-md-2">
                        <div class="stat-calculate" style="">
                            <p>
                            <?php echo __("4 Stars Referrers") ?></p>
                            <h1 class="dfault-0" id="gen_stats_count_4s_referrer"></h1>
                            <p style="height:20px" class="count_veriation" id="var_gen_stats_count_4s_referrer">                                            
                            </p>
                        </div>
                    </div>                                                                
                    <div class="col-md-2">
                        <div class="stat-calculate" style="">
                            <p>
                            <?php echo __("3 Stars Referrers") ?></p>
                            <h1 class="dfault-0" id="gen_stats_count_3s_referrer"></h1>
                            <p style="height:20px" class="count_veriation" id="var_gen_stats_count_3s_referrer">                                            
                            </p>
                        </div>
                    </div>                                                                
                    <div class="col-md-2">
                        <div class="stat-calculate" style="background-color:#f8eabb;">
                            <p>
                            <?php echo __("4/5 Star KPI") ?></p>
                            <h1 class="dfault-0" id="gen_stats_count_referrer_45_kpi"></h1>
                            <p style="height:20px" class="count_veriation" id="var_gen_stats_count_referrer_45_kpi">                                                                    
                            </p>
                        </div>
                    </div>                                        
                    <div class="col-md-1">                                    
                    </div>                                                        
                </div> -->
                <!-- <div class="row stat-count-container">
                    <div class="col-md-4" style="overflow:hidden;padding-right:0;padding-left:0">
                        <p style='font-weight:700;text-align:center;'>
                        <?php echo __("Best 10 Jobs") ?></p>
                        <div style="background:white;padding:0;text-align:center;" class='pie-chart-legend' id="referrer_jobs_legends"></div>
                        <div style="padding-right:21%;padding-left:21%;padding-bottom:2%;background:white;">
                            <canvas style="width:100%" id="referrer_jobs" class="content-white-bkg sb-tour"></canvas>    
                        </div>
                    </div>
                    <div class="col-md-4" style="overflow:hidden;padding-right:0;padding-left:0">
                        <p style='font-weight:700;text-align:center;'>
                        <?php echo __("Age Group") ?></p>
                        <div style="background:white;padding:0;text-align:center;" class='pie-chart-legend' id="referrer_age_legends"></div>
                        <div style="padding-right:21%;padding-left:21%;padding-bottom:2%;background:white;">
                        <canvas style="width:100%" id="referrer_age" class="content-white-bkg sb-tour"></canvas>    
                        </div>
                    </div>
                    <div class="col-md-4" style="overflow:hidden;padding-right:0;padding-left:0">
                        <p style='font-weight:700;text-align:center;' id="referrer_region_label">
                        </p>
                        <div style="background:white;padding:0;text-align:center;" class='pie-chart-legend' id="referrer_region_legends"></div>
                        <div style="padding-right:21%;padding-left:21%;padding-bottom:2%;background:white;">
                            <canvas style="width:100%" id="referrer_region" class="content-white-bkg sb-tour"></canvas>    
                        </div>
                    </div>                
                </div> -->
            </div>  
            <!-- Range Reports -->
            <div class="row first-row-feature" >
                <h3 class="fs-titel stat-headings">
                    <i class="fa fa-clock-o" aria-hidden="true" style="padding-right: 1px;"></i>
                    <?php echo __("Report Performances Overview") ?>
                    <!-- <span class='filter-time-stamp'></span> -->
                </h3>
                <div class="row stat-count-container">
                    <div class="col-md-1">                                    
                    </div>               
                    <div class="col-md-2">
                        <div class="stat-calculate" style="">
                            <p><i class="fa fa-clock-o" aria-hidden="true" style="padding-right: 1px;"></i><?php echo __("No. Reports") ?></p>
                            <h1 class="dfault-0" id="ref_stat_count_range_reports_all"></h1>
                            <p class="count_veriation" id="var_ref_stat_count_range_reports_all">                                            
                            </p>
                        </div>
                    </div>                        
                    <div class="col-md-2">
                        <div class="stat-calculate" style="">
                            <p> <i class="fa fa-clock-o" aria-hidden="true" style="padding-right: 1px;"></i><?php echo __("No. Deal Closed") ?></p>
                            <h1 class="dfault-0" id="ref_stat_count_range_reports_success"></h1>
                            <p class="count_veriation" id="var_ref_stat_count_range_reports_success">                                            
                            </p>
                        </div>
                    </div>      
					<div class="col-md-2">
                        <div class="stat-calculate">
                            <p><i class="fa fa-clock-o" aria-hidden="true" style="padding-right: 1px;"></i><?php echo __("Deals Closed") ?></p>
                            <h1 class="dfault-0" id="ref_stat_count_range_reports_deals_closed"></h1>
                            <p class="count_veriation" id="var_ref_stat_count_range_reports_deals_closed">                                            
                            </p>
                        </div>
                    </div>                    
                    <!-- <div class="col-md-2 hide">
                        <div class="stat-calculate" style="background-color:#f8eabb;">
                            <p><i class="fa fa-clock-o" aria-hidden="true" style="padding-right: 1px;"></i><?php echo __("Incubation Days") ?></p>
                            <h1 class="dfault-0" id="ref_stat_count_range_reports_incubation"></h1>
                            <p class="count_veriation" id="var_ref_stat_count_range_reports_incubation">                                            
                            </p>
                        </div>
                    </div>     -->                    
                    <div class="col-md-2">
                        <div class="stat-calculate" style="">
                            <p id="ref_stat_count_range_reports_commission_label"><i class="fa fa-clock-o" aria-hidden="true" style="padding-right: 1px;"></i><?php echo __("Commissions Paid") ?></p>
                            <h1 class="dfault-0" id="rps_stats_total_commissions_paid"></h1>
							<p class="count_veriation" id="var_rps_stats_total_commissions_paid"></p>
                        </div>
                    </div>                        
                    <div class="col-md-2">
                        <div class="stat-calculate" style="background-color:#f8eabb;cursor:pointer;" rel="tooltip" title="<?php echo __('Report quality indicator. If the conversion into sales falls below 0.20 (20%) it means that the Referrers are not referring target people.') ?>">
                            <p><i class="fa fa-clock-o" aria-hidden="true" style="padding-right: 1px;"></i><?php echo __("Rep. Succ./Total") ?> <i class="fa fa-info-circle" aria-hidden="true" style="padding-left: 1px; color: rgb(129, 133, 137, 0.2);" ></i></p>
							<h1 class="dfault-0" id="rps_stats_total_success_reports_avg"></h1>
							<p class="count_veriation" id="var_rps_stats_total_success_reports_avg"></p>
                            <!-- <h1 class="dfault-0" id="ref_stat_count_range_reports_kpi"></h1>
                            <p class="count_veriation" id="var_ref_stat_count_range_reports_kpi">  -->                                           
                            </p>
                        </div>
                    </div>                        
                    <div class="col-md-1">                                    
                    </div>                                                        
                </div>
            </div>                                                                                                                   
            <!-- Range Agents Chart -->
            <div class="row first-row-feature" style="padding-top:0px;">
                <h3 class="fs-titel stat-headings">  
                    <i class="fa fa-clock-o" aria-hidden="true" style="padding-right: 1px;"></i>              
                    <?php echo __("Agents Chart") ?>
                    <!-- <span class='filter-time-stamp'></span> -->
                </h3>
                <div class="row" style="padding-left:20px;padding-right:20px;padding-top:10px;padding-bottom:10px;">
                    <div class="col-md-12 col-xs-12">                    
                        <table class="table table-bordered" id="range_agent_charts">
                            <thead>
                                <tr>
                                    <th><?php echo __('ID') ?></th>
                                    <th><?php echo __('Agent Name') ?></th>
                                    <th><?php echo __('No. Reports') ?></th>
                                    <th><?php echo __('Commission') ?></th>
                                    <th><?php echo __('Incubation Days') ?></th>                                
                                </tr>
                            </thead>
                            <tbody id="range_agent_charts_body">
                            </tbody>
                        </table>
                    </div>
                </div>            
            </div>    
			<!-- Range Referrers (Only for agents) -->
            <div class="row first-row-feature" style="padding-top:0px;">            
                <h3 class="fs-titel stat-headings"><i class="fa fa-clock-o" aria-hidden="true" style="padding-right: 7px;"></i> <?php echo __("Referrers Chart") ?></h3>                                      
                <div class="row" style="padding-left:20px;padding-right:20px;padding-top:10px;padding-bottom:10px;">
                    <div class="col-md-12 col-xs-12">                    
                        <table class="table table-bordered" id="range_agent_referrer_charts">
                            <thead>
                                <tr>
                                    <th><?php echo __('ID') ?></th>
                                    <th><?php echo __('Name') ?></th>
                                    <th><?php echo __('No. Reports') ?></th>                                                            
                                    <th><?php echo __('Commision') ?></th>
                                    <th><?php echo __('Incubation Days') ?></th>
                                </tr>
                            </thead>
                            <tbody id="range_agent_referrer_charts_body">
                            </tbody>
                        </table>
                    </div>
                </div>            
            </div>                                                                 
        </div>
    </div>
    <!-- Forground END -->    
</div>
<script
      type="text/javascript"
      src="https://cdn.jsdelivr.net/npm/chart.js"
    ></script>
    <script
    src="https://cdnjs.cloudflare.com/ajax/libs/pdf.js/2.6.347/pdf.min.js"
    integrity="sha512-Z8CqofpIcnJN80feS2uccz+pXWgZzeKxDsDNMD/dJ6997/LSRY+W4NmEt9acwR+Gt9OHN0kkI1CTianCwoqcjQ=="
    crossorigin="anonymous"
    referrerpolicy="no-referrer"
  ></script>
  <script
    type="text/javascript"
    src="https://cdnjs.cloudflare.com/ajax/libs/jspdf/1.5.3/jspdf.debug.js"
  ></script>
  <script
    src="https://cdnjs.cloudflare.com/ajax/libs/html2canvas/1.4.1/html2canvas.min.js"
    integrity="sha512-BNaRQnYJYiPSqHHDb58B0yaPfCu+Wgds8Gp/gU33kqBtgNS4tSPHuGibyoeqMV/TJlSKda6FXzoEyYGjTe+vXA=="
    crossorigin="anonymous"
    referrerpolicy="no-referrer"
  ></script>
<script> 
		$(document).ready(function(){
			$("[rel=tooltip]").tooltip({ placement: 'top'});
		});
        // START Date Picker
        var today = new Date();  // get current date
        var oneYearAgo = new Date();  // create new date object
        oneYearAgo.setFullYear(today.getFullYear() - 1);  // set year to previous year

        if($.datepicker.regional['<?php echo Core_Model_Language::getCurrentLanguageDatepicker(); ?>']) {
            $.datepicker.setDefaults($.datepicker.regional['<?php echo Core_Model_Language::getCurrentLanguageDatepicker(); ?>']);
        } else {
            $.datepicker.setDefaults($.datepicker.regional['en']);
        }

        $("#from").datepicker({
            changeMonth: true,
            changeYear: true,
            numberOfMonths: 3,
            minDate: oneYearAgo,
            onClose: function( selectedDate ) {
                $("#to").datepicker( "option", "minDate", selectedDate );
            }
        });

        $("#to").datepicker({
            changeMonth: true,
            changeYear: true,
            numberOfMonths: 3,
            onClose: function( selectedDate ) {
                $("#from").datepicker( "option", "maxDate", selectedDate );
            }
        });        
        $("#to").datepicker('setDate', new Date());
        $("#from").datepicker('setDate', -30);        
        function computeDateRange() {
                var start_timestamp = parseInt($.datepicker.formatDate( "@", $("#from").datepicker("getDate"))/1000);
                var end_timestamp = parseInt($.datepicker.formatDate( "@", $("#to").datepicker("getDate"))/1000);
                //We go to 23:59
                end_timestamp = end_timestamp + (60*60*24) - 60;
                date_range = {
                    "start": start_timestamp,
                    "end": end_timestamp
                };
                return date_range;

            }    
        var date_range_params='';
        function filterStats() {
        if($("#from").val() && $("#to").val()) {
            date_range_params = computeDateRange();
            if(date_range_params.start <= date_range_params.end) {                
                console.log("Called");             
            } else {
                var page_message = new AlertMessage("<?php echo __("Start date must be lower than end date."); ?>");
                page_message.addButton(true);
                page_message.setTimer(false);
                page_message.isError(true);
                page_message.show();
            }
        } else {
            var page_message = new AlertMessage("<?php echo __("You have to chose a start and an end date."); ?>");
            page_message.addButton(true);
            page_message.setTimer(false);
            page_message.isError(true);
            page_message.show();
        }
    }
        // END Date Picker
        $(".default-hide").hide();            
        var total_referrers_ctx = $("#total_referrers");
        //var total_reports_ctx   = $("#total_reports");
        var range_reports_ctx   = $("#range_reports");
        var total_reminders_ctx = $("#total_reminders");
        var range_reminders_ctx = $("#range_reminders");
        var no_data="<p style='font-weight:700;padding:10px;'>No Data Found!</p>";
        // Bar Chart Configrations                       
        var datasetMeta=[
                {
                    label: 'Current',
                    backgroundColor: "#fbb862",
                    borderColor: "#f59b56",
                    borderWidth: 1,
                    hoverBackgroundColor: "#f59b56",
                    hoverBorderColor: "#fbb862",
                    data: []
                },
                {
                    label: 'Previous',
                    backgroundColor: "#64ad73",
                    borderColor: "#3d9a70",
                    borderWidth: 1,
                    hoverBackgroundColor: "#3d9a70",
                    hoverBorderColor: "#64ad73",
                    data: []
                }
            ];        
        var lineChartConfig={
                type: 'line',
                data: {
                        labels: [],
                        datasets: datasetMeta
                    },
                options: {
                        "responsive":true,
                        maintainAspectRatio: false,
                        scales: {
                            y: {
                                min: 0,
                                ticks:{
                                    precision:0
                                }                        
                            }
                        },
                        plugins:{
                        tooltip: {
                            callbacks: {
                                title: function(context) {                                
                                    if (context[0].datasetIndex===1) {
                                        return prev_total_ref_labels[context[0].dataIndex];
                                    }
                                }
                            }
                        }
                    }
                }
        };                                             
        // END line Chart Configrations
        // Bar Chart Configrations
        var barChartOptions={
                "responsive":true,
                maintainAspectRatio: false,
                scales: {
                    y: {
                        min: 0,
                        ticks:{
                            precision:0
                        }                        
                    }
                }
            };                
        var datasetMeta=[
                {
                    label: '<?php echo __("Total Reports"); ?>',
                    backgroundColor: "#fbb862",
                    borderColor: "#f59b56",
                    borderWidth: 1,
                    hoverBackgroundColor: "#f59b56",
                    hoverBorderColor: "#fbb862",
                    data: []
                },
                {
                    label: '<?php echo __("Deal Closed"); ?>',
                    backgroundColor: "#64ad73",
                    borderColor: "#3d9a70",
                    borderWidth: 1,
                    hoverBackgroundColor: "#3d9a70",
                    hoverBorderColor: "#64ad73",
                    data: []
                }
            ];        
        var totalDatasetMetaRem=[
                {
                    label: '<?php echo __("Total Reminders"); ?>',
                    backgroundColor: "#fbb862",
                    borderColor: "#f59b56",
                    borderWidth: 1,
                    hoverBackgroundColor: "#f59b56",
                    hoverBorderColor: "#fbb862",
                    data: []
                },
                {
                    label: '<?php echo __("Rem. Postponed"); ?>',
                    backgroundColor: "#64ad73",
                    borderColor: "#3d9a70",
                    borderWidth: 1,
                    hoverBackgroundColor: "#3d9a70",
                    hoverBorderColor: "#64ad73",
                    data: []
                },
                {
                    label: '<?php echo __("Total Warnings"); ?>',
                    backgroundColor: "#f44336",
                    borderColor: "#c31407",
                    borderWidth: 1,
                    hoverBackgroundColor: "#c31407",
                    hoverBorderColor: "#f44336",
                    data: []
                }
            ];        
        var rangeDatasetMetaRem=[
                {
                    label: '<?php echo __("Total Reminders"); ?>',
                    backgroundColor: "#fbb862",
                    borderColor: "#f59b56",
                    borderWidth: 1,
                    hoverBackgroundColor: "#f59b56",
                    hoverBorderColor: "#fbb862",
                    data: []
                },
                {
                    label: '<?php echo __("Rem. Postponed"); ?>',
                    backgroundColor: "#64ad73",
                    borderColor: "#3d9a70",
                    borderWidth: 1,
                    hoverBackgroundColor: "#3d9a70",
                    hoverBorderColor: "#64ad73",
                    data: []
                },
                {
                    label: '<?php echo __("Total Warnings"); ?>',
                    backgroundColor: "#f44336",
                    borderColor: "#c31407",
                    borderWidth: 1,
                    hoverBackgroundColor: "#c31407",
                    hoverBorderColor: "#f44336",
                    data: []
                }
            ];        
        var barChartConfig0={
                type: 'bar',
                data: {
                        labels: [],
                        datasets: datasetMeta
                    },
                options: barChartOptions
        };                                             
        var barChartConfig1={
                type: 'bar',
                data: {
                        labels: [],
                        datasets: datasetMeta
                    },
                options: barChartOptions
        };                                             
        var barChartConfig2={
                type: 'bar',
                data: {
                        labels: [],
                        datasets: totalDatasetMetaRem
                    },
                options: barChartOptions
        };                                             
        var barChartConfig3={
                type: 'bar',
                data: {
                        labels: [],
                        datasets: rangeDatasetMetaRem
                    },
                options: barChartOptions
        };                                             
        // END bar Chart Configrations
        // START PIE Chart Configrations
        var pieColorPlate=[
                            '#f44336',
                            '#e91e63',
                            '#3f51b5',
                            '#2196f3',
                            '#9c27b0',
                            '#009688',
                            '#cddc39',
                            '#ffeb3b',
                            '#ff5722',
                            '#9e9e9e'
                        ];
        var pieConfig0={
            type: 'pie',
            data: {
                    labels: [],
                    datasets: [{  
                        label: [],                      
                        data: [],
                        backgroundColor:pieColorPlate ,
                        hoverOffset: 10
                    }]
                },
            options: {
                responsive:true,
                plugins:{
                    legend: {
                    display: false
                    }   
                }                               
            }            
        }; 
        var pieConfig1={
            type: 'pie',
            data: {
                    labels: [],
                    datasets: [{  
                        label: [],                      
                        data: [],
                        backgroundColor: pieColorPlate,
                        hoverOffset: 10
                    }]
                },
            options: {
                responsive:true,
                plugins:{
                    legend: {
                    display: false
                    }   
                }                               
            }            
        }; 
        var pieConfig2={
            type: 'pie',
            data: {
                    labels: [],
                    datasets: [{  
                        label: [],                      
                        data: [],
                        backgroundColor: pieColorPlate,
                        hoverOffset: 10
                    }]
                },
            options: {
                responsive:true,
                plugins:{
                    legend: {
                    display: false
                    }   
                }                               
            }            
        }; 
        var pieConfig3={
            type: 'pie',
            data: {
                    labels: [],
                    datasets: [{  
                        label: [],                      
                        data: [],
                        backgroundColor: pieColorPlate,
                        hoverOffset: 10
                    }]
                },
            options: {
                responsive:true,
                plugins:{
                    legend: {
                    display: false
                    }   
                }                               
            }            
        }; 
		var pieConfigSectors={
            type: 'pie',
            data: {
                    labels: [],
                    datasets: [{  
                        label: [],                      
                        data: [],
                        backgroundColor: pieColorPlate,
                        hoverOffset: 10
                    }]
                },
            options: {
                responsive:true,
                plugins:{
                    legend: {
                    display: false
                    }   
                }                               
            }            
        }; 
        var pieConfig4={
            type: 'pie',
            data: {
                    labels: [],
                    datasets: [{  
                        label: [],                      
                        data: [],
                        backgroundColor: pieColorPlate,
                        hoverOffset: 10
                    }]
                },
            options: {
                responsive:true,
                plugins:{
                    legend: {
                    display: false
                    }   
                }                               
            }            
        }; 
        var pieConfig5={
            type: 'pie',
            data: {
                    labels: [],
                    datasets: [{  
                        label: [],                      
                        data: [],
                        backgroundColor: pieColorPlate,
                        hoverOffset: 10
                    }]
                },
            options: {
                responsive:true,
                plugins:{
                    legend: {
                    display: false
                    }   
                }                               
            }            
        }; 
        // END PIE Chart Configrations
        // Report Range Section
        var prev_total_ref_labels = [];
        var newElement;
        var total_referrers = new Chart(total_referrers_ctx, lineChartConfig);
        //var total_ref_reports = new Chart(total_reports_ctx, barChartConfig0);
        //var range_ref_reports = new Chart(range_reports_ctx, barChartConfig1);
        //var total_ref_reminders = new Chart(total_reminders_ctx, barChartConfig2);
        //var range_ref_reminders = new Chart(range_reminders_ctx, barChartConfig3);
        //  PIE Charts

        // Range Jobs        
        var range_jobs_ctx = $("#range_referrer_jobs");        
        var range_jobs = new Chart(range_jobs_ctx, pieConfig3);
		// Range Sectors        
        var range_sectors_ctx = $("#range_referrer_sectors");        
        var range_sectors = new Chart(range_sectors_ctx, pieConfigSectors);
        // Range age        
        var range_age_ctx = $("#range_referrer_age");        
        var range_age = new Chart(range_age_ctx, pieConfig4);                
        // Range region        
        var range_region_ctx = $("#range_referrer_region");        
        var range_region = new Chart(range_region_ctx, pieConfig5);
        // Empty No Graph
        loadReferrerStats();  
        var is_custome_date_filter=0;
        function filterType() {
            range_filter=$("#range_filter").val();                 
            if (range_filter==100) {
                is_custome_date_filter=1;
                $("#custom_date_filter_container").show();
            }else{
                is_custome_date_filter=0;
                $("#custom_date_filter_container").hide();
            }  
        }
        function loadReferrerStats() {    
			$('#total_referrers_loader').show();   
            range_filter=$("#range_filter").val();                 
            filterStats();                       
            $(".dfault-0").text(0); //Reset count values to 0                   
            $.ajax({
                method: "POST",
                dataType: 'json',
                url: "/migareference/generalstats/referrerstats",
                data: { app_id: '<?php echo $app_id; ?>', range_filter: range_filter,date_range_params:date_range_params,is_custome_date_filter:is_custome_date_filter}
            }).done(function( data ) {                            
						var from_date_param = parseInt(range_filter) == 6 ? '<?php echo __("START") ?>' : data.params.from_date;
						var to_date_param = parseInt(range_filter) == 6 ? '<?php echo __("END") ?>' : data.params.to_date;
						$(".filter-time-stamp").text(" ("+'<?php echo __("From") ?>'+": "+from_date_param+" "+'<?php echo __("To") ?>'+": "+to_date_param+")");
                    
                    // **********START SECTION 2  (Range Refrrers)*******//
                    if (range_filter != '6') {// SubSection 2.1 (Range Line Chart)                                
                        var total_ref_labels = [];
                         prev_total_ref_labels = [];
                        var total_ref = [];
                        var success_ref = [];
                        $.each(data.range_graph_ref, function(ind, elem) {
                            total_ref_labels.push(elem.labels);
                            prev_total_ref_labels.push(elem.prev_labels);
                            total_ref.push(elem.total_ref);
                            success_ref.push(elem.prev_ref);
                        });
                        total_referrers.data.datasets[0].data = total_ref;
                        total_referrers.data.datasets[1].data = success_ref;
                        total_referrers.data.labels           = total_ref_labels;                        
                        total_referrers.update();
                    } else {
						total_referrers.data.datasets[0].data = [];
                        total_referrers.data.datasets[1].data = [];
                        total_referrers.data.labels           = [];                        
                        total_referrers.update();
					}
                    if(true) { // SubSection 2.2 (Range Referrers count)            
                        if (data.range_count_ref[0].all_ref!==null) {
                            $("#gen_stats_count_range_referrer").text(data.range_count_ref[0].all_ref);                                                                
                        }
                        $("#var_gen_stats_count_range_referrer").html("").append(data.var_range_count_ref[0].var_all_ref);
                        if (data.range_count_ref[0].five_star!==null) {
                            $("#gen_stats_count_range_5s_referrer").text(data.range_count_ref[0].five_star);                    
                        }
                        $("#var_gen_stats_count_range_5s_referrer").html("").append(data.var_range_count_ref[0].var_five_star);
                        if (data.range_count_ref[0].four_star!==null) {
                            $("#gen_stats_count_range_4s_referrer").text(data.range_count_ref[0].four_star);                    
                        }
                        $("#var_gen_stats_count_range_4s_referrer").html("").append(data.var_range_count_ref[0].var_four_star);                        
                        if (data.range_count_ref[0].three_star!==null) {
                            $("#gen_stats_count_range_3s_referrer").text(data.range_count_ref[0].three_star);                    
                        }
                        $("#var_gen_stats_count_range_3s_referrer").html("").append(data.var_range_count_ref[0].var_three_star);                        
                        if (data.range_count_ref[0].kpi!==null) {
                            $("#gen_stats_count_range_referrer_45_kpi").text(data.range_count_ref[0].kpi);       
                        }       
						toggleColor('#gen_stats_count_range_referrer_45_kpi', data.range_count_reports[0].kpi, 0.15); 
                        $("#var_gen_stats_count_range_referrer_45_kpi").html("").append(data.var_range_count_ref[0].var_kpi);                                                                        
                    }   
                    if (true) { // SubSection 2.3 (Range Pie Charts)                                                                                            
                        // 2.3.1 Ref. PIE Chart (Range)->JOBS                                                                
                        var range_ref_labels = [];
                        var range_ref_values = [];                        
                        $.each(data.range_ref_jobs, function(ind, elem) {
                            if (elem.labels!==null) {
                                range_ref_labels.push(elem.labels);
                                range_ref_values.push(elem.job_count);                            
                            }
                        });
                        range_jobs.data.datasets[0].data = range_ref_values;                        
                        range_jobs.data.labels = range_ref_labels;
                        $("#range_referrer_region_label").html("").html(data.range_region_label);
                        range_jobs.update();   
                        if (data.range_ref_jobs.length) {
                            generateLedgends("#range_referrer_jobs_legends",'rangejobscustomLegend',range_jobs);                                                                                                
                        }else{
                            $("#range_referrer_jobs_legends").html(no_data);                                
                        }
						// 2.3.1.2 Ref. PIE Chart (Range)->SECTORS                                                                
                        var range_ref_labels = [];
                        var range_ref_values = [];                        
                        $.each(data.range_ref_sectors, function(ind, elem) {
                            if (elem.labels!==null) {
                                range_ref_labels.push(elem.labels);
                                range_ref_values.push(elem.profession_count);                            
                            }
                        });
                        range_sectors.data.datasets[0].data = range_ref_values;                        
                        range_sectors.data.labels = range_ref_labels;
                        range_sectors.update();   
                        if (data.range_ref_sectors.length) {
                            generateLedgends("#range_referrer_sectors_legends",'rangesectorscustomLegend',range_sectors);                                                                                                
                        } else {
                            $("#range_referrer_sectors_legends").html(no_data);                                
                        }
                        // 2.3.2 Ref. PIE Chart (Range)->age                                                                
                        var range_ref_labels = [];
                        var range_ref_values = [];                                                
                        var count_age_temp   = 0;                                                
                        $.each(data.range_ref_age, function(ind, elem) {
                            if (elem.labels!==null,elem.age_count!=0) {
                                count_age_temp++;
                                range_ref_labels.push(elem.labels);
                                range_ref_values.push(elem.age_count);     
                            }                       
                        });
                        range_age.data.datasets[0].data = range_ref_values;                        
                        range_age.data.labels = range_ref_labels;
                        range_age.update(); 
                        if (count_age_temp>0) {
                            generateLedgends("#range_referrer_age_legends",'rangeagecustomLegend',range_age);                                               
                        }else{                            
                            $("#range_referrer_age_legends").html(no_data);                                
                        }                        
                        // 2.3.3 Ref. PIE Chart (Range)->Region                                                                                        
                        var range_ref_labels = [];
                        var range_ref_values = [];  
                        $.each(data.range_ref_region, function(ind, elem) {
                            if (elem.labels!==null) {
                                range_ref_labels.push(elem.labels);
                                range_ref_values.push(elem.country_count);                            
                            }
                        });
                        range_region.data.datasets[0].data = range_ref_values;                        
                        range_region.data.labels = range_ref_labels;
                        range_region.update();                                                  
                        if (data.range_ref_region.length) {                          
                            generateLedgends("#range_referrer_region_legends",'rangeregioncustomLegend',range_region);                            
                        }else{                                
                            $("#range_referrer_region_legends").html(no_data);                                
                        }                            
                    }
                    // **********END SECTION 2  (Range Refrrers)*******//                           
                    // **********START SECTION 4  (Range Report)*******//
                    if (true) { // SubSection 4.2 (Range Reports COUNT)                                
                        $("#ref_stat_count_range_reports_all").text(data.range_count_reports[0].total_reports);                                                                
                        $("#var_ref_stat_count_range_reports_all").html("").append(data.var_range_count_reports[0].var_total_reports);

                        $("#ref_stat_count_range_reports_success").text(data.range_count_reports[0].success_reports);                    
                        $("#var_ref_stat_count_range_reports_success").html("").append(data.var_range_count_reports[0].var_success_reports);

                        /* $("#ref_stat_count_range_reports_incubation").text(data.range_count_reports[0].incubation);                    
                        $("#var_ref_stat_count_range_reports_incubation").html("").append(data.var_range_count_reports[0].var_incub_reports); */

						/* $("#ref_stat_count_range_reports_deals_closed").text((parseFloat(data.range_count_reports[0].total_deal_closed_amount).toFixed(2)).toString().replace(/\B(?<!\.\d*)(?=(\d{3})+(?!\d))/g, ","));                    
                        $("#var_ref_stat_count_range_reports_deals_closed").html("").append(data.var_range_count_reports[0].var_ref_stat_count_range_reports_deals_closed); */

						if (data.range_count_reports[0].total_deal_closed_amount!==null) {
							$("#ref_stat_count_range_reports_deals_closed").text((parseFloat(data.range_count_reports[0].total_deal_closed_amount).toFixed(2)).toString().replace(/\B(?<!\.\d*)(?=(\d{3})+(?!\d))/g, ","));                    
						}
						$("#var_ref_stat_count_range_reports_deals_closed").html("").append(data.var_range_count_reports[0].var_ref_stat_count_range_reports_deals_closed);

						if (data.range_count_reports[0].total_commissions_paid!==null) {
							$("#rps_stats_total_commissions_paid").text((parseFloat(data.range_count_reports[0].total_commissions_paid).toFixed(2)).toString().replace(/\B(?<!\.\d*)(?=(\d{3})+(?!\d))/g, ","));                    
						}
						$("#var_rps_stats_total_commissions_paid").html("").append(data.var_range_count_reports[0].var_rps_stats_total_commissions_paid);

                        
                        $("#ref_stat_count_range_reports_commission_label").text(data.range_count_reports[0].earn_lable);                    
                        $("#ref_stat_count_range_reports_commission").text(data.range_count_reports[0].earn_amount);                    
                        $("#var_ref_stat_count_range_reports_commission").html("").append(data.var_range_count_reports[0].var_earn_reports);                        
                        
                        /* $("#ref_stat_count_range_reports_kpi").text(data.range_count_reports[0].kpi);  
						toggleColor('#ref_stat_count_range_reports_kpi', data.range_count_reports[0].kpi, 0.20);                     
                        $("#var_ref_stat_count_range_reports_kpi").html("").append(data.var_range_count_reports[0].var_kpi_reports); */  
						
						var total_reports_avg = 0;
						if ((data.range_count_reports[0].total_reports!==null && data.range_count_reports[0].total_reports!=="0") && (data.range_count_reports[0].total_success_reports!==null && data.range_count_reports[0].total_success_reports!='0')) {
							total_reports_avg = (parseFloat(data.range_count_reports[0].total_success_reports).toFixed(2)/parseFloat(data.range_count_reports[0].total_reports).toFixed(2)).toFixed(2);
							$("#rps_stats_total_success_reports_avg").text(total_reports_avg).toString().replace(/\B(?<!\.\d*)(?=(\d{3})+(?!\d))/g, ",");                   
						}
						toggleColor('#rps_stats_total_success_reports_avg', total_reports_avg, 0.20); 
						$("#var_rps_stats_total_success_reports_avg").html("").append(data.var_range_count_reports[0].var_rps_stats_total_success_reports_avg);
                    }
                    // **********END SECTION 4  (Range Report)*******//                                                          
                                                                                                           
                    // Background Print WOrk
                    const divElement = document.getElementById('pagecontainer');
                    // Get the innerHTML of the div element
                    const htmlContent = divElement.innerHTML;
                    $("#newcontent").remove();
                    // Create a new element to pass the same data
                    newElement = document.createElement('div');
                    newElement.setAttribute('id', 'newcontent');
                    newElement.style.width = '1284px';
                    newElement.style.marginLeft = '200px';
                    newElement.style.position = "absolute";
                    newElement.style.bottom = "100%";
                    newElement.innerHTML = htmlContent;
                    
                    duplicateChartCanvas = newElement.querySelector('#range_referrer_jobs');
                    duplicateChart = new Chart(duplicateChartCanvas, {
                        type: range_jobs.config.type,
                        data: range_jobs.config.data,
                        options: range_jobs.config.options
                    });
					duplicateChartCanvas = newElement.querySelector('#range_referrer_sectors');
                    duplicateChart = new Chart(duplicateChartCanvas, {
                        type: range_sectors.config.type,
                        data: range_sectors.config.data,
                        options: range_sectors.config.options
                    });
                    duplicateChartCanvas = newElement.querySelector('#range_referrer_age');
                    duplicateChart = new Chart(duplicateChartCanvas, {
                        type: range_age.config.type,
                        data: range_age.config.data,
                        options: range_age.config.options
                    });
                    duplicateChartCanvas = newElement.querySelector('#range_referrer_region');
                    duplicateChart = new Chart(duplicateChartCanvas, {
                        type: range_region.config.type,
                        data: range_region.config.data,
                        options: range_region.config.options
                    });
                    duplicateChartCanvas = newElement.querySelector('#total_referrers');
                    duplicateChart = new Chart(duplicateChartCanvas, {
                        type: total_referrers.config.type,
                        data: total_referrers.config.data,
                        options: total_referrers.config.options
                    });
                    duplicateChartCanvas.style.height='348px';
                    from_date=$("#from").val();
                    to_date=$("#to").val();    
                    myDropdown = newElement.querySelector('#range_filter');
                    optionWithValue100 = myDropdown.querySelector(`option[value="${range_filter}"]`);
                    optionWithValue100.selected = true;
                    fromInput = newElement.querySelector('#from');
                    console.log(fromInput);
                    fromInput.setAttribute('value', from_date);
                    toInput = newElement.querySelector('#to');
                    toInput.setAttribute('value', to_date);     
                    document.body.appendChild(newElement);
					loadRangeAgentReferrers(range_filter);
					laodAgentsChartTable(range_filter);
					$('#total_referrers_loader').hide(); 
            }).error(function() {            
               // $("#range_reports_loader").hide();
			   $('#total_referrers_loader').hide(); 
            });
        }      
        
        // START: Bind PIE Chart legend events
        function generateLedgends(chartBoxID,childBoxId,chrtobj) {        
        $(chartBoxID).html("");
        const chartBox = document.querySelector(chartBoxID);        
        const div = document.createElement("DIV");
        div.setAttribute("id", childBoxId);
        const ul = document.createElement("UL");        
        chrtobj.legend.legendItems.forEach((dataset, index) => {            
          const text = dataset.text;
          const datasetIndex = dataset.datasetIndex;
          const bgColor = dataset.fillStyle;
          const bColor = dataset.strokeStyle;
          const fontColor = dataset.fontColor;
          const li = document.createElement("LI");
          const spanBox = document.createElement("SPAN");
          const spanBoxx = document.createElement("P");
          ul.style.padding='5px';
          li.style.marginRight='4px';
          spanBox.style.borderColor = bColor;
          spanBox.style.backgroundColor = bgColor;
          spanBox.style.width = '12px';
          spanBox.style.borderRadius = '0px';          
          spanBoxx.style.margin = '0px';          
          const textNode = document.createTextNode(text);          
          li.onclick = (click) => {                                  
            chrtobj.toggleDataVisibility(dataset.index);            
            updateLegend(click,chrtobj);
          };
          ul.appendChild(li);
          li.appendChild(spanBoxx);          
          spanBoxx.appendChild(spanBox);          
          spanBoxx.appendChild(textNode);
        });
        function updateLegend(click,chrtobj) {
          const element = click.target.parentNode;
          element.classList.toggle("hidden-pie-label");
          chrtobj.update();
        }
        // Append in DIV
        chartBox.appendChild(div);
        div.appendChild(ul);
      }  
        
    
	function printPdf() {     
      $("#pdf_download_loader").show();   
      const doc = new jsPDF();            
      html2canvas(newElement.querySelector("#content")).then((canvas) => {
        var imgData    = canvas.toDataURL();
        var imgWidth   = 210; 
        var pageHeight = 295;  
        var imgHeight  = canvas.height * imgWidth / canvas.width;
        var heightLeft = imgHeight;        
        var doc        = new jsPDF('p', 'mm');
        var position   = 3; // give some top padding to first page
        doc.addImage(imgData, 'JPEG', 0, position, imgWidth, imgHeight);
        heightLeft -= pageHeight;        
        while (heightLeft >= 0) {
        position = heightLeft - imgHeight; // top padding for other pages        
        doc.addPage();
        doc.addImage(imgData, 'JPEG', 0, position, imgWidth, imgHeight);
        heightLeft -= pageHeight;
        }
        doc.save('General Stats.pdf');
        $("#pdf_download_loader").hide();
      });
    }

	var dataTableLanguage = {
		"decimal": "",
		"emptyTable": "<?php echo __js("No data found") ?>",
		"info": "<?php echo __js("Showing _START_ to _END_ of _TOTAL_ entries") ?>",
		"infoEmpty": "<?php echo __js("Showing 0 to 0 of 0 entries") ?>",
		"infoFiltered": "<?php echo __js("(filtered from _MAX_ total entries)") ?>",
		"infoPostFix": "",
		"thousands": ",",
		"loadingRecords": "<?php echo __js("Loading...") ?>",
		"processing": "<?php echo __js("Processing...") ?>",
		"search": "<?php echo __js("Search: ") ?>",
		"zeroRecords": "<?php echo __js("No matching records found") ?>",
		"paginate": {
			"first": "<?php echo __js("First") ?>",
			"last": "<?php echo __js("Last") ?>",
			"next": "<?php echo __js("Next") ?>",
			"previous": "<?php echo __js("Previous") ?>"
		},
		"aria": {
			"sortAscending": "<?php echo __js(": activate to sort column ascending") ?>",
			"sortDescending": "<?php echo __js(": activate to sort column descending") ?>"
		}
	}; 
	function laodAgentsChartTable(range_filter) {  
		$("#range_agent_charts").DataTable().destroy();   
		$('#range_agent_charts:eq(1)').DataTable().destroy();           
		$('#range_agent_charts').dataTable({
			order: [[2, 'desc']],
			language: dataTableLanguage,
			bLengthChange: false,
			bFilter: true,
			sPaginationType: "full_numbers",
			fnDrawCallback: function (nRow, aData, iDisplayIndex, iDisplayIndexFull) {
				$.each(nRow.aoData, function (i, el) {
					var tr = $(el.nTr);
					tr.unbind('click');
				}.bind(this));
				$('.paginate_button').addClass('btn color-blue').attr('data-html2canvas-ignore','true');
				$('.dataTables_filter').attr('data-html2canvas-ignore','true');
				$('.dataTables_info').attr('data-html2canvas-ignore','true');
				$('span a.paginate_button').addClass('btn btn-grey');
			},
			dom: 'Bfrtip',
				buttons: {
				buttons: [
					{ 
						extend: 'csv',
						className: 'btn btn-lg btn-xs btn-success right-side btn-table-download',
						text: '<i class="fa fa-download" aria-hidden="true"></i> CSV',
						attr:{
							'data-html2canvas-ignore':'true'
						} 
					},                                
					]
			},
			ajax : '<?php echo $this->getUrl('migareference/generalstats/agentrangereports?app_id='.$app_id.'&range_filter='); ?>'+range_filter,                
       });
	}
	function loadRangeAgentReferrers(range_filter) {                
		$("#range_agent_referrer_charts").DataTable().destroy();   
		$('#range_agent_referrer_charts:eq(1)').DataTable().destroy();             
		$('#range_agent_referrer_charts').dataTable({
			order: [[2, 'desc']],
			language: dataTableLanguage,
			bLengthChange: false,
			bFilter: true,
			sPaginationType: "full_numbers",
			fnDrawCallback: function (nRow, aData, iDisplayIndex, iDisplayIndexFull) {
				$.each(nRow.aoData, function (i, el) {
					var tr = $(el.nTr);
					tr.unbind('click');
				}.bind(this));
				$('.paginate_button').addClass('btn color-blue').attr('data-html2canvas-ignore','true');
				$('.dataTables_filter').attr('data-html2canvas-ignore','true');
				$('.dataTables_info').attr('data-html2canvas-ignore','true');
			},
			dom: 'Bfrtip',
			buttons: {
				buttons: [
					{ extend: 'csv',
							className: 'btn btn-lg btn-xs btn-success right-side',
							text: '<i class="fa fa-download" aria-hidden="true"></i> CSV', 
						attr:{
							'data-html2canvas-ignore':'true'
						} 
					},                                
					]
			},
			ajax : '<?php echo $this->getUrl('migareference/adminstats/agentrangereports?tab=general&app_id='.$app_id.'&range_filter='); ?>'+range_filter+"&agent_id=0&date_range_start="+date_range_params.start+"&date_range_end="+date_range_params.end,                
	 	});            
	}

	function toggleColor(elem, current_value, limit_value) {
		if (parseFloat(current_value) < limit_value) {
			$(elem).addClass('text-red');
		} else {
			$(elem).removeClass('text-red');
		}
	}
</script>
<style>
/* Stat CSS */
.stat-calculate{
    padding-top: 8px;
    padding-bottom: 8px;
    border-radius: 7px;
    background: #f7f7f7;
    text-align: center;
    transition: transform .7s;
}
.stat-calculate:hover {      
    -webkit-transform: scale(1.2);
    -moz-transform: scale(1.2);
    -ms-transform: scale(1.2);
    -o-transform: scale(1.2);
    transform: scale(1.2);    
    background: #9797974a;
}
.stat-calculate h1{
    font-weight:700;
    margin-top:18px;
    margin-bottom:21px;
    line-height:40px;

}
.stat-calculate p{
    font-weight:700;
    font-size:small;
    line-height:20px;
    overflow:hidden;
}
.count_veriation{
    font-size:small;
}
.count_veriation span{
    font-size:small;    
}
.var-positive {
    background: #87d82757;
    padding: 2px;
    border-radius: 10px;
    color: green;
    font-weight: 700;
}
.var-negative {
    background: #d827272e;
    padding: 2px;
    border-radius: 10px;
    color: #e91e63;
    font-weight: 700;
}
.var-nochange {
    background: #0000003d;
    padding: 2px;
    border-radius: 10px;
    font-weight: 700;
}
.stat-headings{
    color: white;
    background-color: #0099C7;
    padding: 9px;
    margin-top: 14px;
    margin-bottom: 14px;
    margin-left: 20px;
    margin-right: 20px;
}
.stat-count-container{
    border: 1px solid #d0cfcf;
    margin-left: 20px;
    margin-right: 20px;
    padding-bottom: 15px;
    padding-top: 15px;
}
/* Pie CHart */
.pie-chart-legend ul>li span{
    display: inline-block;    
    width: 12px;
    height: 12px;
    margin-right: 5px;
}
.pie-chart-legend ul>li {
    display: inline-block;  
    margin: 4px;  
}

.pie-chart-legend{
  height:150px;
  
}
.hidden-pie-label {
  text-decoration: line-through;
}
/* START Data Table  style*/
.sub_heading{
        border-bottom: 2px solid #0099c7;
        padding-bottom: 13px;
    }
    .remove_btn{
        background-color: red;
    }
    .emptydataset{
        text-align: center;
    }
table{
    background-color: white;
}
     table.dataTable {
                margin: 20px 0 10px;
                width: 100% !important;
            }

            table.dataTable th {
                text-align: left;
            }
            table.dataTable tbody tr.edit_product {
                cursor: pointer;
            }

            .dataTables_info {
                float: left;
                padding: 10px;
            }

            .dataTables_paginate {
                float: right;
            }

            .dataTables_paginate a {
                display: block;
                float: left;
                margin-left: 4px;
                padding: 6px;
            }

            .dataTables_paginate a.paginate_button_disabled {
                opacity: 0.3
            }

            .dataTable tbody tr:last-of-type {
                border-bottom: 0;
            }

            #migasms {
                overflow: auto;
            }
            #contantcontainer {
                border-radius: 0px !important;
            }
            #contentheader{
              background-color: #f3f3f3 !important;
              padding: 8px !important;
            }
            #contentfooter{
              padding: 5px !important;
            }
            .right-side{
              float: right;
              margin-right: 5px;
            }
            #delbtn{
              float: right;
            }
            #delbtner{
              float: right;
            }
/* END Data Table  style*/
#row_filter_metrics label{line-height:29px}
.text-red {
	color: red !important;
}

</style>