<?php
$application = $this->getApplication();
$app_id      = $application->getId();
$migareference  = new Migareference_Model_Migareference();    
$referral_usrs  = $migareference->get_referral_users($app_id);
$agent_report_count  = $migareference->count_agent_reports($app_id,0);
$agents         = $migareference->get_customer_agents($app_id);
$admins         = $migareference->getAdminCustomers($app_id);
$admins_and_agents = [];
if (count($agents)) {
	foreach ($agents as $key => $agent) {
		$admins_and_agents[$agent['user_id']] = $agent['firstname'] . ' ' . $agent['lastname'] . ' (' . __("agent") . ')';
	}
}
if (count($admins)) {
	foreach ($admins as $key => $admin) {
		$admins_and_agents[$admin['customer_id']] = $admin['firstname'] . ' ' . $admin['lastname'] . ' (' . __("admin") . ')';
	}
}
$pre_settings = $migareference->preReportsettigns($app_id);
$default        = new Core_Model_Default();
$base_url       = $default->getBaseUrl();
?>
<script type="text/javascript" language="javascript" src="https://cdn.datatables.net/1.10.19/js/jquery.dataTables.min.js"></script>
<script type="text/javascript" language="javascript" src="https://cdn.datatables.net/buttons/1.5.2/js/dataTables.buttons.min.js"></script>
<script type="text/javascript" language="javascript" src="https://cdn.datatables.net/buttons/1.5.2/js/buttons.flash.min.js"></script>
<script type="text/javascript" language="javascript" src="https://cdnjs.cloudflare.com/ajax/libs/jszip/3.1.3/jszip.min.js"></script>
<script type="text/javascript" language="javascript" src="https://cdnjs.cloudflare.com/ajax/libs/pdfmake/0.1.36/pdfmake.min.js"></script>
<script type="text/javascript" language="javascript" src="https://cdnjs.cloudflare.com/ajax/libs/pdfmake/0.1.36/vfs_fonts.js"></script>
<script type="text/javascript" language="javascript" src="https://cdn.datatables.net/buttons/1.5.2/js/buttons.html5.min.js"></script>
<script type="text/javascript" language="javascript" src="https://cdn.datatables.net/buttons/1.5.2/js/buttons.print.min.js"></script>
<div id="pagecontainer">
    <div class="application_analytics application content" id="content">
        <h3 class="title-editor border-blue text-center"><?php echo __("Migareference Prospecting Stats") ?><span class='filter-time-stamp'></span></h3>
        <div class="container-fluid subcontent content-color"  >        
		<ul class="nav nav-tabs" role="tablist" data-html2canvas-ignore="true" style="margin-bottom:10px;">
				<li role="presentation">
                    <a href="<?=$base_url."/migareference/generalstats/general"?>">
                        <?php echo __("General") ?>
                    </a>
                </li>
				<li role="presentation" class="active">
					<a href="<?=$base_url."/migareference/prospectstats/prospect" ?>">
                        <?php echo __("Prospecting") ?>
                    </a>
                </li>
				<li role="presentation">
                    <a href="<?=$base_url."/migareference/reportstats/report" ?>">
                        <?php echo __("Reports") ?>
                    </a>
                </li>
				<li role="presentation" >
                    <a href="<?=$base_url."/migareference/followupstats/followup" ?>">
                        <?php echo __("Followup") ?>
                    </a>
                </li>
				<li role="presentation" >
                    <a href="<?=$base_url."/migareference/referrerstats/referrer" ?>">
                        <?php echo __("Referrers") ?>
                    </a>
                </li>
                <!-- <li role="presentation" >
                    <a href="<?=$base_url."/migareference/adminstats/admin" ?>">
                        <?php echo __("Agent") ?>
                    </a>
                </li>
                <li role="presentation" >
                    <a href="<?=$base_url."/migareference/referrerstats/referrer" ?>">
                        <?php echo __("Referrers") ?>
                    </a>
                </li>      -->
                <li style="float:right;">
                    <button class="btn color-blue" onclick="printPdf()">
                        <i class="fa fa-download"></i>
                        <?php echo __("PDF") ?>
                        <span style="display:none;" id="pdf_download_loader"><i class="fa fa-circle-o-notch fa-spin fa-fw"></i></span>
                    </button>
                </li>               
            </ul>  
            <!-- Filter Start -->
            <div class="row">
                <div class="col-md-2">
                    <select onChange="filterType()" id="range_filter" class="input-flat" name="">
						<option value="6"><?php echo __("ALL") ?></option> 
						<option value="8"><?php echo __("Past Week") ?></option> 
                        <option selected value="1"><?php echo __("Last 30 Days") ?></option> 
						<option value="7"><?php echo __("Past Month") ?></option>                           
                        <option value="2"><?php echo __("Last 3 Months") ?></option>                            
                        <option value="3"><?php echo __("Last 6 Months") ?></option>                            
                        <option value="4"><?php echo __("Current Year") ?></option>                            
                        <option value="5"><?php echo __("Last Year") ?></option>                               
                        <option style="font-weight:600" value="100"><?php echo __("Custom Range") ?></option>                            
                    </select>
                </div> 
                <div class="col-md-2">
					<select id="sponsor_filter" class="input-flat" name="">                        
                        <option value="0"><?php echo __("ALL") ?></option>                                                                              
                        <?php foreach ($admins_and_agents as $key => $value): ?>
                        <option value="<?=$key ?>"><?=$value ?>
                        </option>
                        <?php endforeach; ?>
                    </select>  
                </div>
                <div class="col-md-4" id="custom_date_filter_container" style="display:none;">                
                    <div id="row_filter_metrics" class="row sb-tour">
                        <div class="col-md-2 col-sm-6 col-xs-6" style="padding:0">
                            <label for="from"><?php echo __("From"); ?></label>
                        </div>
                        <div class="col-md-4 col-sm-6 col-xs-6" style="padding:0">
                            <input type="text" id="from" name="from" class="input-flat sb-tour">
                        </div>
                        <div class="col-md-2 col-sm-6 col-xs-6" style="padding-right:0">
                            <label for="to"><?php echo __("To"); ?></label>
                        </div>
                        <div class="col-md-4 col-sm-6 col-xs-6"  style="padding:0">
                            <input type="text" id="to" name="to" class="input-flat sb-tour">
                        </div>                    
                    </div>
                </div>                             
                <div class="col-md-2">
                    <button data-html2canvas-ignore="true" class="btn color-blue" onclick="loadReferrerStats()">                    
                        <?php echo __("Filter Stats") ?>                    
                    </button>
                </div>                    
            </div>        
            <!-- Filter End -->
            <?php  if (count($referral_usrs)) { ?>        
            <!-- Range Referers -->
            <div class="row first-row-feature" style="padding-top:0px;">
                <h3 class="fs-titel stat-headings"><?php echo __("Prospecting Quality") ?></h3>  
				<div style="margin-left:49%;" id="total_referrers_loader" class="loader_metrics"><i class="fa fa-circle-o-notch fa-spin fa-3x fa-fw"></i><br/><?php echo __("Loading..."); ?></div>                                    
                <div class="row stat-count-container">
                    <div class="col-md-1">                                    
                    </div>               
                    <div class="col-md-2">
                        <div class="stat-calculate" style="">
                            <p><i class="fa fa-clock-o" aria-hidden="true" style="padding-right: 2px;"></i>
                            <?php echo __("No. Referrers") ?></p>
                            <h1 class="dfault-0" id="gen_stats_count_range_referrer"></h1>
                            <p class="count_veriation" id="var_gen_stats_count_range_referrer">                                            
                            </p>
                        </div>
                    </div>                        
                    <div class="col-md-2">
                        <div class="stat-calculate" style="">
                            <p><i class="fa fa-clock-o" aria-hidden="true" style="padding-right: 2px;"></i>
                            <?php echo __("5 Stars Referrers") ?></p>
                            <h1 class="dfault-0" id="gen_stats_count_range_5s_referrer"></h1>
                            <p class="count_veriation" id="var_gen_stats_count_range_5s_referrer">                                             
                            </p>
                        </div>
                    </div>                        
                    <div class="col-md-2">
                        <div class="stat-calculate" style="">
                            <p><i class="fa fa-clock-o" aria-hidden="true" style="padding-right: 2px;"></i>
                            <?php echo __("4 Stars Referrers") ?></p>
                            <h1 class="dfault-0" id="gen_stats_count_range_4s_referrer"></h1>
                            <p class="count_veriation" id="var_gen_stats_count_range_4s_referrer">                                            
                            </p>
                        </div>
                    </div>                                                                
                    <div class="col-md-2">
                        <div class="stat-calculate" style="">
                            <p><i class="fa fa-clock-o" aria-hidden="true" style="padding-right: 2px;"></i>
                            <?php echo __("3 Stars Referrers") ?></p>
                            <h1 class="dfault-0" id="gen_stats_count_range_3s_referrer"></h1>
                            <p class="count_veriation" id="var_gen_stats_count_range_3s_referrer">                                            
                            </p>
                        </div>
                    </div>                                                                
                    <div class="col-md-2">
                        <div class="stat-calculate" style="background-color:#f8eabb;cursor:pointer;" rel="tooltip" title="<?php echo __('Recruitment quality indicator. Good recruitment must produce at least 0.15 (15%) good Referrers.') ?>">
                            <p><i class="fa fa-clock-o" aria-hidden="true" style="padding-right: 2px;"></i>
                            <?php echo __("3/4/5 Star KPI") ?> <i class="fa fa-info-circle" aria-hidden="true" style="padding-left: 2px; color: rgb(129, 133, 137, 0.2);" ></i></p>
                            <h1 class="dfault-0" id="gen_stats_count_range_referrer_45_kpi"></h1>
                            <p class="count_veriation" id="var_gen_stats_count_range_referrer_45_kpi">                                            
                            </p>
                        </div>
                    </div>                                        
                    <div class="col-md-1">                                    
                    </div>                                                        
                </div>
            </div>  
			<div class="row first-row-feature" style="padding-top:0px;">
				<h3 class="fs-titel stat-headings"><?php echo __("Qualifying Performance") ?></h3>
				<div style="margin-left:49%;" id="total_referrers_loader" class="loader_metrics"><i class="fa fa-circle-o-notch fa-spin fa-3x fa-fw"></i><br/><?php echo __("Loading..."); ?></div>
				<div class="row stat-count-container">
                    <div class="col-md-2">                                    
                    </div>               
                    <div class="col-md-2">
                        <div class="stat-calculate" style="">
                            <p><i class="fa fa-clock-o" aria-hidden="true" style="padding-right: 2px;"></i>
                            <?php echo __("No. Referrers") ?></p>
                            <h1 class="dfault-0" id="gen_stats_count_range_referrer_qp"></h1>
                            <p class="count_veriation" id="var_gen_stats_count_range_referrer_qp">                                            
                            </p>
                        </div>
                    </div> 
					<div class="col-md-2">
                        <div class="stat-calculate" style="">
                            <p><i class="fa fa-clock-o" aria-hidden="true" style="padding-right: 2px;"></i>
                            <?php echo __("1st Time Proc.") ?></p>
                            <h1 class="dfault-0" id="prospecting_stats_count_1st_time_processed"></h1>
                            <p class="count_veriation" id="var_prospecting_stats_count_1st_time_processed">                                             
                            </p>
                        </div>
                    </div>  
					<div class="col-md-2">
                        <div class="stat-calculate" style="background-color:#f8eabb;cursor:pointer;" rel="tooltip" title="<?php echo __('Qualifying and knowing potential referrers is very important. The minimum average daily number must not fall below 2.') ?>">
                            <p><i class="fa fa-clock-o" aria-hidden="true" style="padding-right: 2px;"></i>
                            <?php echo __("Avg.Processed/Day") ?> <i class="fa fa-info-circle" aria-hidden="true" style="padding-left: 2px; color: rgb(129, 133, 137, 0.2);" ></i></p>
                            <h1 class="dfault-0" id="prospecting_stats_average_processed"></h1>
                            <p class="count_veriation" id="var_prospecting_stats_average_processed">                                             
                            </p>
                        </div>
                    </div>      
					<div class="col-md-2">
                        <div class="stat-calculate" style="background-color:#f8eabb;cursor:pointer;" rel="tooltip" title="<?php echo __('Knowing and qualifying your referrers is essential. This KPI tells you how many people in your club you managed to get to know and profile.') ?>">
                            <p><i class="fa fa-clock-o" aria-hidden="true" style="padding-right: 2px;"></i>
                            <?php echo __("1st Time Proc. KPI") ?> <i class="fa fa-info-circle" aria-hidden="true" style="padding-left: 2px; color: rgb(129, 133, 137, 0.2);" ></i></p>
                            <h1 class="dfault-0" id="prospecting_stats_count_1st_time_processed_kpi"></h1>
                            <p class="count_veriation" id="var_prospecting_stats_count_1st_time_processed_kpi">                                             
                            </p>
                        </div>
                    </div>                                                        
                    <div class="col-md-2">                                    
                    </div>                                                        
                </div>
				<div class="row" style="padding:20px;">
                    <div class="col-md-12 col-xs-12" style="max-height:350px">
						<div style="margin-left:49%;" id="total_referrers_loader" class="loader_metrics"><i class="fa fa-circle-o-notch fa-spin fa-3x fa-fw"></i><br/><?php echo __("Loading..."); ?></div>
                        <canvas style="border:1px solid #dedddd" id="chart_1st_time_processed_vs_var" class="content-white-bkg sb-tour" width="400" height="350"></canvas>
                    </div>
                </div>
			</div>          
            <?php } else { ?>
			<div class="row">
				<div class="col-sm-12" style="text-align:center;" >
					<strong ><?php echo __("No Referrers Found")."!"; ?></strong> 
				</div>
			</div>
            <?php } ?>                             
        </div>
    </div>
</div>
<script
      type="text/javascript"
      src="https://cdn.jsdelivr.net/npm/chart.js"
    ></script>
    <script
    src="https://cdnjs.cloudflare.com/ajax/libs/pdf.js/2.6.347/pdf.min.js"
    integrity="sha512-Z8CqofpIcnJN80feS2uccz+pXWgZzeKxDsDNMD/dJ6997/LSRY+W4NmEt9acwR+Gt9OHN0kkI1CTianCwoqcjQ=="
    crossorigin="anonymous"
    referrerpolicy="no-referrer"
  ></script>
  <script
    type="text/javascript"
    src="https://cdnjs.cloudflare.com/ajax/libs/jspdf/1.5.3/jspdf.debug.js"
  ></script>
  <script
    src="https://cdnjs.cloudflare.com/ajax/libs/html2canvas/1.4.1/html2canvas.min.js"
    integrity="sha512-BNaRQnYJYiPSqHHDb58B0yaPfCu+Wgds8Gp/gU33kqBtgNS4tSPHuGibyoeqMV/TJlSKda6FXzoEyYGjTe+vXA=="
    crossorigin="anonymous"
    referrerpolicy="no-referrer"
  ></script>
<script>  
	$(document).ready(function(){
		$("[rel=tooltip]").tooltip({ placement: 'top'});
	}); 
	// START Date Picker
	var today = new Date();  // get current date
	var oneYearAgo = new Date();  // create new date object
	oneYearAgo.setFullYear(today.getFullYear() - 1);  // set year to previous year

	if ($.datepicker.regional['<?php echo Core_Model_Language::getCurrentLanguageDatepicker(); ?>']) {
		$.datepicker.setDefaults($.datepicker.regional['<?php echo Core_Model_Language::getCurrentLanguageDatepicker(); ?>']);
	} else {
		$.datepicker.setDefaults($.datepicker.regional['en']);
	}

	$("#from").datepicker({
		changeMonth: true,
		changeYear: true,
		numberOfMonths: 3,
		minDate: oneYearAgo,
		onClose: function( selectedDate ) {
			$("#to").datepicker( "option", "minDate", selectedDate );
		}
	});

	$("#to").datepicker({
		changeMonth: true,
		changeYear: true,
		numberOfMonths: 3,
		onClose: function( selectedDate ) {
			$("#from").datepicker( "option", "maxDate", selectedDate );
		}
	});        
	$("#to").datepicker('setDate', new Date());
	$("#from").datepicker('setDate', -30);        
	function computeDateRange() {
		var start_timestamp = parseInt($.datepicker.formatDate( "@", $("#from").datepicker("getDate"))/1000);
		var end_timestamp = parseInt($.datepicker.formatDate( "@", $("#to").datepicker("getDate"))/1000);
		//We go to 23:59
		end_timestamp = end_timestamp + (60*60*24) - 60;
		date_range = {
			"start": start_timestamp,
			"end": end_timestamp
		};
		return date_range;
	} 

	var date_range_params='';
	function filterStats() {
		if($("#from").val() && $("#to").val()) {
			date_range_params = computeDateRange();
			if(date_range_params.start <= date_range_params.end) {                
				console.log("Done");             
			} else {
				var page_message = new AlertMessage("<?php echo __("Start date must be lower than end date."); ?>");
				page_message.addButton(true);
				page_message.setTimer(false);
				page_message.isError(true);
				page_message.show();
			}
		} else {
			var page_message = new AlertMessage("<?php echo __("You have to chose a start and an end date."); ?>");
			page_message.addButton(true);
			page_message.setTimer(false);
			page_message.isError(true);
			page_message.show();
		}
	}
	// END Date Picker
	$(".default-hide").hide();  
	var chart_1st_time_processed_vs_var;
    var chart_1st_time_processed_vs_var_labels = [];
	var chart_1st_time_processed_vs_var_values = [];  
	var chart_1st_time_processed_vs_var_ctx = $("#chart_1st_time_processed_vs_var");
	var data = {
		labels: chart_1st_time_processed_vs_var_labels,
		datasets: [
			{
				label: '<?php echo __("Current 1st Time Proc."); ?>',
				backgroundColor: "#fbb862",
				borderColor: "#f59b56",
				borderWidth: 1,
				hoverBackgroundColor: "#f59b56",
				hoverBorderColor: "#fbb862",
				data: chart_1st_time_processed_vs_var_values
			},
			{
				label: '<?php echo __("Previous 1st Time Proc."); ?>',
				backgroundColor: "#64ad73",
				borderColor: "#3d9a70",
				borderWidth: 1,
				hoverBackgroundColor: "#3d9a70",
				hoverBorderColor: "#64ad73",
				data: chart_1st_time_processed_vs_var_values
			}
		]
	};
	chart_1st_time_processed_vs_var = new Chart(chart_1st_time_processed_vs_var_ctx, {
		type: 'bar',
		data: data,
		options: {
			"responsive":true,
			maintainAspectRatio: false,
			scales: {
				y: {
					min: 0,
					ticks:{
						precision:0
					}                        
				}
			}
		}
	});

	loadReferrerStats();  
	var is_custome_date_filter = 0;
	function filterType() {
		range_filter=$("#range_filter").val();                 
		if (range_filter==100) {
			is_custome_date_filter=1;
			$("#custom_date_filter_container").show();
		}else{
			is_custome_date_filter=0;
			$("#custom_date_filter_container").hide();
		}  
	} 

	function loadReferrerStats() {  
		$(".loader_metrics").show();            
        range_filter = $("#range_filter").val();                 
        agent_id = $("#sponsor_filter").val();
		filterStats();          
        $(".dfault-0").text(0); //Reset count values to 0   
		$.ajax({
			method: "POST",
			dataType: 'json',
			url: "/migareference/prospectstats/prospectstats",
			data: { app_id: '<?php echo $app_id; ?>', range_filter: range_filter,agent_id:agent_id,date_range_params:date_range_params,is_custome_date_filter:is_custome_date_filter}
        }).done(function( data ) { 
			$(".filter-time-stamp").text(" ("+'<?php echo __("From") ?>'+": "+data.params.from_date+" "+'<?php echo __("To") ?>'+": "+data.params.to_date+")");
			if(true) { // SubSection 2.2 (Range Referrers count)
				if (data.range_count_ref[0].all_ref!==null) {
					$("#gen_stats_count_range_referrer, #gen_stats_count_range_referrer_qp").text(data.range_count_ref[0].all_ref);                                                                
				}            
				$("#var_gen_stats_count_range_referrer, #var_gen_stats_count_range_referrer_qp").html("").append(data.var_range_count_ref[0].var_all_ref);
				if (data.range_count_ref[0].five_star!==null) {
					$("#gen_stats_count_range_5s_referrer").text(data.range_count_ref[0].five_star);                    
				}
				$("#var_gen_stats_count_range_5s_referrer").html("").append(data.var_range_count_ref[0].var_five_star);
				if (data.range_count_ref[0].four_star!==null) {
					$("#gen_stats_count_range_4s_referrer").text(data.range_count_ref[0].four_star);                    
				}
				$("#var_gen_stats_count_range_4s_referrer").html("").append(data.var_range_count_ref[0].var_four_star);                        
				if (data.range_count_ref[0].three_star!==null) {
					$("#gen_stats_count_range_3s_referrer").text(data.range_count_ref[0].three_star);                    
				}
				$("#var_gen_stats_count_range_3s_referrer").html("").append(data.var_range_count_ref[0].var_three_star);                        
				
				$("#gen_stats_count_range_referrer_45_kpi").text(data.range_count_ref[0].kpi); 
				toggleColor('#gen_stats_count_range_referrer_45_kpi', data.range_count_ref[0].kpi, 0.15);                   
				$("#var_gen_stats_count_range_referrer_45_kpi").html("").append(data.var_range_count_ref[0].var_kpi);                                                                        
			} 
			//Qualifying Performance START
			if (true) {
				if (data.range_count_qp_processed_referrers[0].total_processed_referrers!==null) {
					$("#prospecting_stats_count_1st_time_processed").text(data.range_count_qp_processed_referrers[0].total_processed_referrers);                                                     
				}  
				$("#var_prospecting_stats_count_1st_time_processed").html("").append(data.var_range_count_qp_processed_referrers[0].var_qp_processed_referrers);

				$("#prospecting_stats_average_processed").html("").append(data.prospecting_stats_average_processed);
				$("#var_prospecting_stats_average_processed").html("").append(data.var_prospecting_stats_average_processed);

				$("#prospecting_stats_count_1st_time_processed_kpi").html("").append(data.prospecting_stats_count_1st_time_processed_kpi);
				$("#var_prospecting_stats_count_1st_time_processed_kpi").html("").append(data.var_prospecting_stats_count_1st_time_processed_kpi);

				if (data.arr_chart_1st_time_processed.length > 0) {
					var arr_chart_1st_time_processed_vs_var_labels = [];
					var arr_chart_1st_time_processed = [];
					var arr_chart_1st_time_processed_var = [];
					$.each(data.arr_chart_1st_time_processed, function(ind, elem) {
						arr_chart_1st_time_processed_vs_var_labels.push(elem.label);
						arr_chart_1st_time_processed.push(elem.total_processed_referrers);
					});
					if (data.arr_chart_1st_time_processed_var.length > 0) {
						$.each(data.arr_chart_1st_time_processed_var, function(ind, elem) {
							arr_chart_1st_time_processed_var.push(elem.total_processed_referrers);
						});
					}
					chart_1st_time_processed_vs_var.data.datasets[0].data = arr_chart_1st_time_processed;
					chart_1st_time_processed_vs_var.data.datasets[1].data = arr_chart_1st_time_processed_var;
					chart_1st_time_processed_vs_var.data.labels = arr_chart_1st_time_processed_vs_var_labels;
					chart_1st_time_processed_vs_var.update();
				} else {
					chart_1st_time_processed_vs_var.data.datasets[0].data = [];
					chart_1st_time_processed_vs_var.data.datasets[1].data = [];
					chart_1st_time_processed_vs_var.data.labels = [];
					chart_1st_time_processed_vs_var.update();
				}
			}
			//Qualifying Performance END
			
			$(".loader_metrics").hide();

			// Background Print WOrk
			const divElement = document.getElementById('pagecontainer');
			console.log("Element is here");
			console.log(divElement);
			// Get the innerHTML of the div element
			const htmlContent = divElement.innerHTML;
			$("#newcontent").remove();
			// Create a new element to pass the same data
			newElement = document.createElement('div');
			newElement.setAttribute('id', 'newcontent');
			newElement.style.width = '1284px';
			newElement.style.marginLeft = '200px';
			newElement.style.position = "absolute";
			newElement.style.bottom = "100%";
			newElement.innerHTML = htmlContent;
			duplicateChartCanvas = newElement.querySelector('#chart_1st_time_processed_vs_var');
			duplicateChart = new Chart(duplicateChartCanvas, {
				type: chart_1st_time_processed_vs_var.config.type,
				data: chart_1st_time_processed_vs_var.config.data,
				options: chart_1st_time_processed_vs_var.config.options
			});
			duplicateChartCanvas.style.height='348px';
			range_filter=$("#range_filter").val();
			sponsor_filter=$("#sponsor_filter").val();
			//referrer_filter=$("#referrer_filter").val();
			from_date=$("#from").val();
			to_date=$("#to").val();                                            
			myDropdown = newElement.querySelector('#range_filter');                                                            
			optionWithValue100 = myDropdown.querySelector(`option[value="${range_filter}"]`);                    
			optionWithValue100.selected = true;
			myDropdown = newElement.querySelector('#sponsor_filter');                                                            
			optionWithValue100 = myDropdown.querySelector(`option[value="${sponsor_filter}"]`);                    
			optionWithValue100.selected = true;
			//myDropdown = newElement.querySelector('#referrer_filter');                                                            
			//optionWithValue100 = myDropdown.querySelector(`option[value="${referrer_filter}"]`);                    
			//optionWithValue100.selected = true;
			fromInput = newElement.querySelector('#from');
			console.log(fromInput);
			fromInput.setAttribute('value', from_date);
			toInput = newElement.querySelector('#to');
			toInput.setAttribute('value', to_date);     
			document.body.appendChild(newElement);
		}).error(function() {            
            $(".loader_metrics").hide();
        });
	}

	function printPdf() {     
		$("#pdf_download_loader").show();   
		const doc = new jsPDF();            
		html2canvas(newElement.querySelector("#content")).then((canvas) => {
			var imgData    = canvas.toDataURL();
			var imgWidth   = 210; 
			var pageHeight = 295;  
			var imgHeight  = canvas.height * imgWidth / canvas.width;
			var heightLeft = imgHeight;        
			var doc        = new jsPDF('p', 'mm');
			var position   = 3; // give some top padding to first page
			doc.addImage(imgData, 'JPEG', 0, position, imgWidth, imgHeight);
			heightLeft -= pageHeight;        
			while (heightLeft >= 0) {
			position = heightLeft - imgHeight; // top padding for other pages        
			doc.addPage();
			doc.addImage(imgData, 'JPEG', 0, position, imgWidth, imgHeight);
			heightLeft -= pageHeight;
			}
			doc.save('PROSPECTING_STATS.pdf');
			$("#pdf_download_loader").hide();
		});
	}
	function toggleColor(elem, current_value, limit_value) {
		if (parseFloat(current_value) < limit_value) {
			$(elem).addClass('text-red');
		} else {
			$(elem).removeClass('text-red');
		}
	}
</script>
<style>
/* Stat CSS */
.stat-calculate{
    padding-top: 8px;
    padding-bottom: 8px;
    border-radius: 7px;
    background: #f7f7f7;
    text-align: center;
    transition: transform .7s;
}
.stat-calculate:hover {      
    -webkit-transform: scale(1.2);
    -moz-transform: scale(1.2);
    -ms-transform: scale(1.2);
    -o-transform: scale(1.2);
    transform: scale(1.2);    
    background: #9797974a;
}
.stat-calculate h1{
    font-weight:700;
    margin-top:18px;
    margin-bottom:21px;
    line-height:40px;

}
.stat-calculate p{
    font-weight:700;
    /* font-size:1vw; */
    line-height:20px;
    overflow:hidden;
}
.count_veriation{
    font-size:small;
}
.count_veriation span{
    font-size:small;
    /* font-size:1vw; */
}
.var-positive {
    background: #87d82757;
    padding: 2px;
    border-radius: 10px;
    color: green;
    font-weight: 700;
}
.var-negative {
    background: #d827272e;
    padding: 2px;
    border-radius: 10px;
    color: #e91e63;
    font-weight: 700;
}
.var-nochange {
    background: #0000003d;
    padding: 2px;
    border-radius: 10px;
    font-weight: 700;
}
.stat-headings{
    color: white;
    background-color: #0099C7;
    padding: 9px;
    margin-top: 14px;
    margin-bottom: 14px;
    margin-left: 20px;
    margin-right: 20px;
}
.stat-count-container{
    border: 1px solid #d0cfcf;
    margin-left: 20px;
    margin-right: 20px;
    padding-bottom: 15px;
    padding-top: 15px;
}
/* Pie CHart */
.pie-chart-legend ul>li span{
    display: inline-block;    
    width: 12px;
    height: 12px;
    margin-right: 5px;
}
.pie-chart-legend ul>li {
    display: inline-block;  
    margin: 4px;  
}

.pie-chart-legend{
  height:115px;
  
}
.hidden-pie-label {
  text-decoration: line-through;
}
/* START Data Table  style*/
.sub_heading{
        border-bottom: 2px solid #0099c7;
        padding-bottom: 13px;
    }
    .remove_btn{
        background-color: red;
    }
    .emptydataset{
        text-align: center;
    }
table{
    background-color: white;
}
     table.dataTable {
                margin: 20px 0 10px;
                width: 100% !important;
            }

            table.dataTable th {
                text-align: left;
            }
            table.dataTable tbody tr.edit_product {
                cursor: pointer;
            }

            .dataTables_info {
                float: left;
                padding: 10px;
            }

            .dataTables_paginate {
                float: right;
            }

            .dataTables_paginate a {
                display: block;
                float: left;
                margin-left: 4px;
                padding: 6px;
            }

            .dataTables_paginate a.paginate_button_disabled {
                opacity: 0.3
            }

            .dataTable tbody tr:last-of-type {
                border-bottom: 0;
            }

            #migasms {
                overflow: auto;
            }
            #contantcontainer {
                border-radius: 0px !important;
            }
            #contentheader{
              background-color: #f3f3f3 !important;
              padding: 8px !important;
            }
            #contentfooter{
              padding: 5px !important;
            }
            .right-side{
              float: right;
              margin-right: 5px;
            }
            #delbtn{
              float: right;
            }
            #delbtner{
              float: right;
            }
/* END Data Table  style*/
#row_filter_metrics label{line-height:29px}
.text-red {
	color: red !important;
}
</style>