<?php
$application = $this->getApplication();
$app_id      = $application->getId();
$migareference  = new Migareference_Model_Migareference();    
$referral_usrs  = $migareference->get_referral_users($app_id);
$agent_report_count  = $migareference->count_agent_reports($app_id,0);
$agents         = $migareference->get_customer_agents($app_id);
$pre_settings = $migareference->preReportsettigns($app_id);
$default        = new Core_Model_Default();
$base_url       = $default->getBaseUrl();
?>
<script type="text/javascript" language="javascript" src="https://cdn.datatables.net/1.10.19/js/jquery.dataTables.min.js"></script>
<script type="text/javascript" language="javascript" src="https://cdn.datatables.net/buttons/1.5.2/js/dataTables.buttons.min.js"></script>
<script type="text/javascript" language="javascript" src="https://cdn.datatables.net/buttons/1.5.2/js/buttons.flash.min.js"></script>
<script type="text/javascript" language="javascript" src="https://cdnjs.cloudflare.com/ajax/libs/jszip/3.1.3/jszip.min.js"></script>
<script type="text/javascript" language="javascript" src="https://cdnjs.cloudflare.com/ajax/libs/pdfmake/0.1.36/pdfmake.min.js"></script>
<script type="text/javascript" language="javascript" src="https://cdnjs.cloudflare.com/ajax/libs/pdfmake/0.1.36/vfs_fonts.js"></script>
<script type="text/javascript" language="javascript" src="https://cdn.datatables.net/buttons/1.5.2/js/buttons.html5.min.js"></script>
<script type="text/javascript" language="javascript" src="https://cdn.datatables.net/buttons/1.5.2/js/buttons.print.min.js"></script>
<div id="pagecontainer">
    <div class="application_analytics application content" id="content">
        <h3 class="title-editor border-blue text-center"><?php echo __("Migareference Report Stats") ?><span class='filter-time-stamp'></span></h3>
        <div class="container-fluid subcontent content-color"  >        
		<ul class="nav nav-tabs" role="tablist" data-html2canvas-ignore="true" style="margin-bottom:10px;">
				<li role="presentation">
                    <a href="<?=$base_url."/migareference/generalstats/general"?>">
                        <?php echo __("General") ?>
                    </a>
                </li>
				<li role="presentation">
					<a href="<?=$base_url."/migareference/prospectstats/prospect" ?>">
                        <?php echo __("Prospecting") ?>
                    </a>
                </li>
				<li role="presentation" class="active">
                    <a href="<?=$base_url."/migareference/reportstats/report" ?>">
                        <?php echo __("Reports") ?>
                    </a>
                </li>
				<li role="presentation" >
                    <a href="<?=$base_url."/migareference/followupstats/followup" ?>">
                        <?php echo __("Followup") ?>
                    </a>
                </li>
				<li role="presentation" >
                    <a href="<?=$base_url."/migareference/referrerstats/referrer" ?>">
                        <?php echo __("Referrers") ?>
                    </a>
                </li>
                <!-- <li role="presentation" >
                    <a href="<?=$base_url."/migareference/adminstats/admin" ?>">
                        <?php echo __("Agent") ?>
                    </a>
                </li>
                <li role="presentation" >
                    <a href="<?=$base_url."/migareference/referrerstats/referrer" ?>">
                        <?php echo __("Referrers") ?>
                    </a>
                </li>      -->
                <li style="float:right;">
                    <button class="btn color-blue" onclick="printPdf()">
                        <i class="fa fa-download"></i>
                        <?php echo __("PDF") ?>
                        <span style="display:none;" id="pdf_download_loader"><i class="fa fa-circle-o-notch fa-spin fa-fw"></i></span>
                    </button>
                </li>               
            </ul>    
            <!-- Filter Start -->
            <div class="row">
                <div class="col-md-2">
                    <select onChange="filterType()" id="range_filter" class="input-flat" name="">
						<option value="6"><?php echo __("ALL") ?></option> 
						<option value="8"><?php echo __("Past Week") ?></option> 
                        <option selected value="1"><?php echo __("Last 30 Days") ?></option> 
						<option value="7"><?php echo __("Past Month") ?></option>                           
                        <option value="2"><?php echo __("Last 3 Months") ?></option>                            
                        <option value="3"><?php echo __("Last 6 Months") ?></option>                            
                        <option value="4"><?php echo __("Current Year") ?></option>                            
                        <option value="5"><?php echo __("Last Year") ?></option>                               
                        <option style="font-weight:600" value="100"><?php echo __("Custom Range") ?></option>                            
                    </select>
                </div> 
                <div class="col-md-2">
					<select id="sponsor_filter" class="input-flat" name="">
                        <?php if ($pre_settings[0]['enable_mandatory_agent_selection']==2) { ?>
                        <option value="0"><?php echo __("I dont know") ?></option>
                        <?php } ?>                                                       
                        <?php foreach ($agents as $key => $value): ?>
                        <option value="<?=$value['user_id'] ?>"><?=$value['firstname']." ".$value['lastname'] ?>
                        </option>
                        <?php endforeach; ?>
                    </select>  
                </div>
                <div class="col-md-4" id="custom_date_filter_container" style="display:none;">                
                    <div id="row_filter_metrics" class="row sb-tour">
                        <div class="col-md-2 col-sm-6 col-xs-6" style="padding:0">
                            <label for="from"><?php echo __("From"); ?></label>
                        </div>
                        <div class="col-md-4 col-sm-6 col-xs-6" style="padding:0">
                            <input type="text" id="from" name="from" class="input-flat sb-tour">
                        </div>
                        <div class="col-md-2 col-sm-6 col-xs-6" style="padding-right:0">
                            <label for="to"><?php echo __("To"); ?></label>
                        </div>
                        <div class="col-md-4 col-sm-6 col-xs-6"  style="padding:0">
                            <input type="text" id="to" name="to" class="input-flat sb-tour">
                        </div>                    
                    </div>
                </div>                             
                <div class="col-md-2">
                    <button data-html2canvas-ignore="true" class="btn color-blue" onclick="loadReferrerReportStats()">                    
                        <?php echo __("Filter Stats") ?>                    
                    </button>
                </div>                    
            </div>        
            <!-- Filter End -->
            <?php  if (count($referral_usrs)) { ?>        
            <!-- Range Referers -->
            <div class="row first-row-feature" style="padding-top:0px;">
                <h3 class="fs-titel stat-headings"><?php echo __("Referrers Report Statistics & Prediction") ?></h3>  
				<div style="margin-left:49%;" id="total_referrers_loader" class="loader_metrics"><i class="fa fa-circle-o-notch fa-spin fa-3x fa-fw"></i><br/><?php echo __("Loading..."); ?></div>                                    
            </div>   
			<div class="row" style="padding: 20px;">
				<div class="col-md-3">
					<h3 class="text-center"><?php echo __("3 STARS STATISTICS") ?></h3>
					<div class="stat-calculate">
						<p><i class="fa fa-clock-o" aria-hidden="true" style="padding-right: 2px;"></i>
						<?php echo __("Total Referrers 3*") ?></p>
						<h1 class="dfault-0" id="gen_stats_count_range_3s_referrer"></h1>
						<p class="count_veriation" id="var_gen_stats_count_range_3s_referrer">                                            
						</p>
					</div>    
					<div class="stat-calculate" style="margin-top: 15px;">
						<p><i class="fa fa-clock-o" aria-hidden="true" style="padding-right: 2px;"></i>
						<?php echo __("Total Reports 3*") ?></p>
						<h1 class="dfault-0" id="rep_stats_count_range_3s_reports"></h1>
						<p class="count_veriation" id="var_rep_stats_count_range_3s_reports">                                            
						</p>
					</div>   
					<div class="stat-calculate" style="background-color:#f8eabb;margin-top: 15px;">
						<p><i class="fa fa-clock-o" aria-hidden="true" style="padding-right: 1px;"></i>
						<?php echo __("Incubation Days") ?></p>
						<h1 class="dfault-0" id="rep_stats_range_3s_ids"></h1>
						<p class="count_veriation" id="var_rep_stats_range_3s_ids">                                            
						</p>
					</div>    
					<div class="stat-calculate" style="background-color:#f8eabb;margin-top: 15px;">
						<p><i class="fa fa-clock-o" aria-hidden="true" style="padding-right: 1px;"></i>
						<?php echo __("KPI Report Conv.") ?></p>
						<h1 class="dfault-0" id="rep_stats_range_3s_conv_kpi"></h1>
						<p class="count_veriation" id="var_rep_stats_range_3s_conv_kpi">                                            
						</p>
					</div>
					<div class="stat-calculate" style="background-color:#f8eabb;margin-top: 15px;">
						<p><i class="fa fa-clock-o" aria-hidden="true" style="padding-right: 1px;"></i>
						<?php echo __("Avg Rep. x Active Ref.") ?></p>
						<h1 class="dfault-0" id="rep_stats_range_avg_rep_x_active_ref_3s_kpi"></h1>
						<p class="count_veriation" id="var_rep_stats_range_avg_rep_x_active_ref_3s_kpi">                                            
						</p>
					</div> 
					<div class="stat-calculate" style="background-color:#f8eabb;margin-top: 15px;">
						<p><i class="fa fa-clock-o" aria-hidden="true" style="padding-right: 1px;"></i>
						<?php echo __("Expected Reports") ?></p>
						<h1 class="dfault-0" id="rep_stats_range_expected_reports_3s_kpi"></h1>
					</div>                        	
				</div>
				<div class="col-md-3"> 
					<h3 class="text-center"><?php echo __("4 STARS STATISTICS") ?></h3>
					<div class="stat-calculate">
						<p><i class="fa fa-clock-o" aria-hidden="true" style="padding-right: 2px;"></i>
						<?php echo __("Total Referrers 4*") ?></p>
						<h1 class="dfault-0" id="gen_stats_count_range_4s_referrer"></h1>
						<p class="count_veriation" id="var_gen_stats_count_range_4s_referrer">                                            
						</p>
					</div>  
					<div class="stat-calculate" style="margin-top: 15px;">
						<p><i class="fa fa-clock-o" aria-hidden="true" style="padding-right: 2px;"></i>
						<?php echo __("Total Reports 4*") ?></p>
						<h1 class="dfault-0" id="rep_stats_count_range_4s_reports"></h1>
						<p class="count_veriation" id="var_rep_stats_count_range_4s_reports">                                            
						</p>
					</div>  
					<div class="stat-calculate" style="background-color:#f8eabb;margin-top: 15px;">
						<p><i class="fa fa-clock-o" aria-hidden="true" style="padding-right: 1px;"></i>
						<?php echo __("Incubation Days") ?></p>
						<h1 class="dfault-0" id="rep_stats_range_4s_ids"></h1>
						<p class="count_veriation" id="var_rep_stats_range_4s_ids">                                            
						</p>
					</div>      
					<div class="stat-calculate" style="background-color:#f8eabb;margin-top: 15px;">
						<p><i class="fa fa-clock-o" aria-hidden="true" style="padding-right: 1px;"></i>
						<?php echo __("KPI Report Conv.") ?></p>
						<h1 class="dfault-0" id="rep_stats_range_4s_conv_kpi"></h1>
						<p class="count_veriation" id="var_rep_stats_range_4s_conv_kpi">                                            
						</p>
					</div>            
					<div class="stat-calculate" style="background-color:#f8eabb;margin-top: 15px;">
						<p><i class="fa fa-clock-o" aria-hidden="true" style="padding-right: 1px;"></i>
						<?php echo __("Avg Rep. x Active Ref.") ?></p>
						<h1 class="dfault-0" id="rep_stats_range_avg_rep_x_active_ref_4s_kpi"></h1>
						<p class="count_veriation" id="var_rep_stats_range_avg_rep_x_active_ref_4s_kpi">                                            
						</p>
					</div> 
					<div class="stat-calculate" style="background-color:#f8eabb;margin-top: 15px;">
						<p><i class="fa fa-clock-o" aria-hidden="true" style="padding-right: 1px;"></i>
						<?php echo __("Expected Reports") ?></p>
						<h1 class="dfault-0" id="rep_stats_range_expected_reports_4s_kpi"></h1>
					</div>                     
				</div>
				<div class="col-md-3">
					<h3 class="text-center"><?php echo __("5 STARS STATISTICS") ?></h3>  
					<div class="stat-calculate">
						<p><i class="fa fa-clock-o" aria-hidden="true" style="padding-right: 2px;"></i>
						<?php echo __("Total Referrers 5*") ?></p>
						<h1 class="dfault-0" id="gen_stats_count_range_5s_referrer"></h1>
						<p class="count_veriation" id="var_gen_stats_count_range_5s_referrer">                                             
						</p>
					</div>    
					<div class="stat-calculate" style="margin-top: 15px;">
						<p><i class="fa fa-clock-o" aria-hidden="true" style="padding-right: 2px;"></i>
						<?php echo __("Total Reports 5*") ?></p>
						<h1 class="dfault-0" id="rep_stats_count_range_5s_reports"></h1>
						<p class="count_veriation" id="var_rep_stats_count_range_5s_reports">                                            
						</p>
					</div>   
					<div class="stat-calculate" style="background-color:#f8eabb;margin-top: 15px;">
						<p><i class="fa fa-clock-o" aria-hidden="true" style="padding-right: 1px;"></i>
						<?php echo __("Incubation Days") ?></p>
						<h1 class="dfault-0" id="rep_stats_range_5s_ids"></h1>
						<p class="count_veriation" id="var_rep_stats_range_5s_ids">                                            
						</p>
					</div>   
					<div class="stat-calculate" style="background-color:#f8eabb;margin-top: 15px;">
						<p><i class="fa fa-clock-o" aria-hidden="true" style="padding-right: 1px;"></i>
						<?php echo __("KPI Report Conv.") ?></p>
						<h1 class="dfault-0" id="rep_stats_range_5s_conv_kpi"></h1>
						<p class="count_veriation" id="var_rep_stats_range_5s_conv_kpi">                                            
						</p>
					</div>     
					<div class="stat-calculate" style="background-color:#f8eabb;margin-top: 15px;">
						<p><i class="fa fa-clock-o" aria-hidden="true" style="padding-right: 1px;"></i>
						<?php echo __("Avg Rep. x Active Ref.") ?></p>
						<h1 class="dfault-0" id="rep_stats_range_avg_rep_x_active_ref_5s_kpi"></h1>
						<p class="count_veriation" id="var_rep_stats_range_avg_rep_x_active_ref_5s_kpi">                                            
						</p>
					</div>   
					<div class="stat-calculate" style="background-color:#f8eabb;margin-top: 15px;">
						<p><i class="fa fa-clock-o" aria-hidden="true" style="padding-right: 1px;"></i>
						<?php echo __("Expected Reports") ?></p>
						<h1 class="dfault-0" id="rep_stats_range_expected_reports_5s_kpi"></h1>
					</div>                
				</div>
				<div class="col-md-3">   
					<h3 class="text-center"><?php echo __("ALL REFERRERS") ?></h3>
					<div class="stat-calculate" style="">
						<p><i class="fa fa-clock-o" aria-hidden="true" style="padding-right: 2px;"></i>
						<?php echo __("All Referrers") ?></p>
						<h1 class="dfault-0" id="gen_stats_count_range_referrer"></h1>
						<p class="count_veriation" id="var_gen_stats_count_range_referrer">                                            
						</p>
					</div>    
					<div class="stat-calculate" style="margin-top: 15px;">
						<p><i class="fa fa-clock-o" aria-hidden="true" style="padding-right: 2px;"></i>
						<?php echo __("Total Reports") ?></p>
						<h1 class="dfault-0" id="rep_stats_count_range_total_reports"></h1>
						<p class="count_veriation" id="var_rep_stats_count_range_total_reports">                                            
						</p>
					</div>
					<div class="stat-calculate" style="background-color:#f8eabb;cursor:pointer; margin-top: 15px;" rel="tooltip" title="<?php echo __('Average number of days between the registration of a Referrer and the sending of the first report. This KPI measures the effectiveness of training and quality of Referrers.') ?>">
						<p><i class="fa fa-clock-o" aria-hidden="true" style="padding-right: 1px;"></i>
						<?php echo __("Incubation Days") ?> <i class="fa fa-info-circle" aria-hidden="true" style="padding-left: 1px; color: rgb(129, 133, 137, 0.2);" ></i></p>
						<h1 class="dfault-0" id="rep_stats_range_total_incubation_ids"></h1>
						<p class="count_veriation" id="var_rep_stats_range_total_incubation_ids">                                            
						</p>
					</div>        
					<div class="stat-calculate" style="background-color:#f8eabb;cursor:pointer; margin-top: 15px;" rel="tooltip" title="<?php echo __('This KPI measures how many of our Referrers make a first-time report. The value should always be greater than 0.15. This KPI measures the e! effectiveness of training and the quality of Referrers.') ?>">
						<p><i class="fa fa-clock-o" aria-hidden="true" style="padding-right: 1px;"></i>
						<?php echo __("KPI Active Ref.") ?> <i class="fa fa-info-circle" aria-hidden="true" style="padding-left: 1px; color: rgb(129, 133, 137, 0.2);" ></i></p>
						<h1 class="dfault-0" id="rep_stats_range_total_conv_kpi"></h1>
						<p class="count_veriation" id="var_rep_stats_range_total_conv_kpi">                                            
						</p>
					</div> 
					<div class="stat-calculate" style="background-color:#f8eabb;cursor:pointer; margin-top: 15px;" rel="tooltip" title="<?php echo __('This KPI measures the total number of reports received from referrers in the same group, divided by the total number of reporters who have made at least one report. The KPI measures how active the reporters are over time and therefore the effectiveness of the follow-up.') ?>">
						<p><i class="fa fa-clock-o" aria-hidden="true" style="padding-right: 1px;"></i>
						<?php echo __("Avg Rep. x Active Ref.") ?> <i class="fa fa-info-circle" aria-hidden="true" style="padding-left: 1px; color: rgb(129, 133, 137, 0.2);" ></i></p>
						<h1 class="dfault-0" id="rep_stats_range_avg_rep_x_active_ref_all_kpi"></h1>
						<p class="count_veriation" id="var_rep_stats_range_avg_rep_x_active_ref_all_kpi">                                            
						</p>
					</div> 
					<div class="stat-calculate" style="background-color:#f8eabb;cursor:pointer; margin-top: 15px;" rel="tooltip" title="<?php echo __('This KPI tries to predict how many reports we will owe in the near future. The calculation takes into consideration the percentage of Referrers that will be activated, therefore Total referrers are not yet active x the KPI Active Referrers. The calculation only takes into account alerters created between today and twice the average incubation time.') ?>">
						<p><i class="fa fa-clock-o" aria-hidden="true" style="padding-right: 1px;"></i>
						<?php echo __("Expected Reports") ?> <i class="fa fa-info-circle" aria-hidden="true" style="padding-left: 1px; color: rgb(129, 133, 137, 0.2);" ></i></p>
						<h1 class="dfault-0" id="rep_stats_range_expected_reports_all_kpi"></h1>
					</div>                               
				</div>
			</div>      
			<div class="row first-row-feature" style="padding-top:0px;">
                <h3 class="fs-titel stat-headings"><?php echo __("Report Performances Statistics") ?></h3>  
				<div style="margin-left:49%;" class="loader_metrics"><i class="fa fa-circle-o-notch fa-spin fa-3x fa-fw"></i><br/><?php echo __("Loading..."); ?></div>                                    
            </div> 
			<div class="row" style="padding: 20px;">
				<div class="col-md-3">
					<h3 class="text-center"><?php echo __("3 STARS STATISTICS") ?></h3>

					<div class="stat-calculate">
						<p><i class="fa fa-clock-o" aria-hidden="true" style="padding-right: 2px;"></i>
						<?php echo __("No. Reports") ?></p>
						<h1 class="dfault-0" id="rps_stats_3s_report"></h1>
						<p class="count_veriation" id="var_rps_stats_3s_report">                                            
						</p>
					</div>  
					<div class="stat-calculate" style="margin-top: 15px;">
						<p><i class="fa fa-clock-o" aria-hidden="true" style="padding-right: 2px;"></i>
						<?php echo __("No. Deals Closed") ?></p>
						<h1 class="dfault-0" id="rps_stats_three_star_total_no_of_deal_closed"></h1>
						<p class="count_veriation" id="var_rps_stats_three_star_total_no_of_deal_closed">                                            
						</p>
					</div>
					<div class="stat-calculate" style="margin-top: 15px;">
						<p><i class="fa fa-clock-o" aria-hidden="true" style="padding-right: 2px;"></i>
						<?php echo __("Deals Closed") ?></p>
						<h1 class="dfault-0" id="rps_stats_three_star_total_no_of_deal_closed_amount"></h1>
						<p class="count_veriation" id="var_rps_stats_three_star_total_no_of_deal_closed_amount">                                            
						</p>
					</div>
					<div class="stat-calculate" style="margin-top: 15px;">
						<p><i class="fa fa-clock-o" aria-hidden="true" style="padding-right: 2px;"></i>
						<?php echo __("Commissions Paid") ?></p>
						<h1 class="dfault-0" id="rps_stats_three_star_total_commissions_paid"></h1>
						<p class="count_veriation" id="var_rps_stats_three_star_total_commissions_paid">                                            
						</p>
					</div>
					<div class="stat-calculate" style="background-color:#f8eabb;cursor:pointer; margin-top: 15px;">
						<p><i class="fa fa-clock-o" aria-hidden="true" style="padding-right: 1px;"></i>
						<?php echo __("Rep. Succ./Total") ?></p>
						<h1 class="dfault-0" id="rps_stats_total_success_reports_3s_avg"></h1>
						<p class="count_veriation" id="var_rps_stats_total_success_reports_3s_avg">                                            
						</p>
					</div>
					<div class="stat-calculate" style="background-color:#f8eabb;cursor:pointer; margin-top: 15px;">
						<p><i class="fa fa-clock-o" aria-hidden="true" style="padding-right: 1px;"></i>
						<?php echo __("Incubation Days") ?></p>
						<h1 class="dfault-0" id="rps_stats_3s_incubation_days"></h1>
					</div>
				</div>
				<div class="col-md-3">
					<h3 class="text-center"><?php echo __("4 STARS STATISTICS") ?></h3>

					<div class="stat-calculate">
						<p><i class="fa fa-clock-o" aria-hidden="true" style="padding-right: 2px;"></i>
						<?php echo __("No. Reports") ?></p>
						<h1 class="dfault-0" id="rps_stats_4s_report"></h1>
						<p class="count_veriation" id="var_rps_stats_4s_report">                                            
						</p>
					</div>  
					<div class="stat-calculate" style="margin-top: 15px;">
						<p><i class="fa fa-clock-o" aria-hidden="true" style="padding-right: 2px;"></i>
						<?php echo __("No. Deals Closed") ?></p>
						<h1 class="dfault-0" id="rps_stats_four_star_total_no_of_deal_closed"></h1>
						<p class="count_veriation" id="var_rps_stats_four_star_total_no_of_deal_closed">                                            
						</p>
					</div>
					<div class="stat-calculate" style="margin-top: 15px;">
						<p><i class="fa fa-clock-o" aria-hidden="true" style="padding-right: 2px;"></i>
						<?php echo __("Deals Closed") ?></p>
						<h1 class="dfault-0" id="rps_stats_four_star_total_no_of_deal_closed_amount"></h1>
						<p class="count_veriation" id="var_rps_stats_four_star_total_no_of_deal_closed_amount">                                            
						</p>
					</div>
					<div class="stat-calculate" style="margin-top: 15px;">
						<p><i class="fa fa-clock-o" aria-hidden="true" style="padding-right: 2px;"></i>
						<?php echo __("Commissions Paid") ?></p>
						<h1 class="dfault-0" id="rps_stats_four_star_total_commissions_paid"></h1>
						<p class="count_veriation" id="var_rps_stats_four_star_total_commissions_paid">                                            
						</p>
					</div>
					<div class="stat-calculate" style="background-color:#f8eabb;cursor:pointer; margin-top: 15px;">
						<p><i class="fa fa-clock-o" aria-hidden="true" style="padding-right: 1px;"></i>
						<?php echo __("Rep. Succ./Total") ?></p>
						<h1 class="dfault-0" id="rps_stats_total_success_reports_4s_avg"></h1>
						<p class="count_veriation" id="var_rps_stats_total_success_reports_4s_avg">                                            
						</p>
					</div>
					<div class="stat-calculate" style="background-color:#f8eabb;cursor:pointer; margin-top: 15px;">
						<p><i class="fa fa-clock-o" aria-hidden="true" style="padding-right: 1px;"></i>
						<?php echo __("Incubation Days") ?></p>
						<h1 class="dfault-0" id="rps_stats_4s_incubation_days"></h1>
					</div>
				</div>
				<div class="col-md-3">
					<h3 class="text-center"><?php echo __("5 STARS STATISTICS") ?></h3>

					<div class="stat-calculate">
						<p><i class="fa fa-clock-o" aria-hidden="true" style="padding-right: 2px;"></i>
						<?php echo __("No. Reports") ?></p>
						<h1 class="dfault-0" id="rps_stats_5s_report"></h1>
						<p class="count_veriation" id="var_rps_stats_5s_report">                                            
						</p>
					</div>
					<div class="stat-calculate" style="margin-top: 15px;">
						<p><i class="fa fa-clock-o" aria-hidden="true" style="padding-right: 2px;"></i>
						<?php echo __("No. Deals Closed") ?></p>
						<h1 class="dfault-0" id="rps_stats_five_star_total_no_of_deal_closed"></h1>
						<p class="count_veriation" id="var_rps_stats_five_star_total_no_of_deal_closed">                                            
						</p>
					</div>
					<div class="stat-calculate" style="margin-top: 15px;">
						<p><i class="fa fa-clock-o" aria-hidden="true" style="padding-right: 2px;"></i>
						<?php echo __("Deals Closed") ?></p>
						<h1 class="dfault-0" id="rps_stats_five_star_total_no_of_deal_closed_amount"></h1>
						<p class="count_veriation" id="var_rps_stats_five_star_total_no_of_deal_closed_amount">                                            
						</p>
					</div>
					<div class="stat-calculate" style="margin-top: 15px;">
						<p><i class="fa fa-clock-o" aria-hidden="true" style="padding-right: 2px;"></i>
						<?php echo __("Commissions Paid") ?></p>
						<h1 class="dfault-0" id="rps_stats_five_star_total_commissions_paid"></h1>
						<p class="count_veriation" id="var_rps_stats_five_star_total_commissions_paid">                                            
						</p>
					</div>
					<div class="stat-calculate" style="background-color:#f8eabb;cursor:pointer; margin-top: 15px;">
						<p><i class="fa fa-clock-o" aria-hidden="true" style="padding-right: 1px;"></i>
						<?php echo __("Rep. Succ./Total") ?></p>
						<h1 class="dfault-0" id="rps_stats_total_success_reports_5s_avg"></h1>
						<p class="count_veriation" id="var_rps_stats_total_success_reports_5s_avg">                                            
						</p>
					</div>
					<div class="stat-calculate" style="background-color:#f8eabb;cursor:pointer; margin-top: 15px;">
						<p><i class="fa fa-clock-o" aria-hidden="true" style="padding-right: 1px;"></i>
						<?php echo __("Incubation Days") ?></p>
						<h1 class="dfault-0" id="rps_stats_5s_incubation_days"></h1>
					</div>
				</div>
				<div class="col-md-3">
					<h3 class="text-center"><?php echo __("TOTAL REPORTS") ?></h3>

					<div class="stat-calculate">
						<p><i class="fa fa-clock-o" aria-hidden="true" style="padding-right: 2px;"></i>
						<?php echo __("No. Reports") ?></p>
						<h1 class="dfault-0" id="rps_stats_total_report"></h1>
						<p class="count_veriation" id="var_rps_stats_total_report">                                            
						</p>
					</div>
					<div class="stat-calculate" style="margin-top: 15px;">
						<p><i class="fa fa-clock-o" aria-hidden="true" style="padding-right: 2px;"></i>
						<?php echo __("No. Deals Closed") ?></p>
						<h1 class="dfault-0" id="rps_stats_total_no_of_deal_closed"></h1>
						<p class="count_veriation" id="var_rps_stats_total_no_of_deal_closed">                                            
						</p>
					</div>
					<div class="stat-calculate" style="margin-top: 15px;">
						<p><i class="fa fa-clock-o" aria-hidden="true" style="padding-right: 2px;"></i>
						<?php echo __("Deals Closed") ?></p>
						<h1 class="dfault-0" id="rps_stats_total_no_of_deal_closed_amount"></h1>
						<p class="count_veriation" id="var_rps_stats_total_no_of_deal_closed_amount">                                            
						</p>
					</div>
					<div class="stat-calculate" style="margin-top: 15px;">
						<p><i class="fa fa-clock-o" aria-hidden="true" style="padding-right: 2px;"></i>
						<?php echo __("Commissions Paid") ?></p>
						<h1 class="dfault-0" id="rps_stats_total_commissions_paid"></h1>
						<p class="count_veriation" id="var_rps_stats_total_commissions_paid">                                            
						</p>
					</div>
					<div class="stat-calculate" style="background-color:#f8eabb;cursor:pointer; margin-top: 15px;" rel="tooltip" title="<?php echo __('Report quality indicator. If the conversion into sales falls below 0.20 (20%) it means that the Referrers are not referring target people.') ?>">
						<p><i class="fa fa-clock-o" aria-hidden="true" style="padding-right: 1px;"></i>
						<?php echo __("Rep. Succ./Total") ?> <i class="fa fa-info-circle" aria-hidden="true" style="padding-left: 1px; color: rgb(129, 133, 137, 0.2);" ></i></p>
						<h1 class="dfault-0" id="rps_stats_total_success_reports_avg"></h1>
						<p class="count_veriation" id="var_rps_stats_total_success_reports_avg">                                            
						</p>
					</div>
					<div class="stat-calculate" style="background-color:#f8eabb;cursor:pointer; margin-top: 15px;" rel="tooltip" title="<?php echo __('The incubation time tells us how long on average a report takes to conclude with a sale.') ?>">
						<p><i class="fa fa-clock-o" aria-hidden="true" style="padding-right: 1px;"></i>
						<?php echo __("Incubation Days") ?>  <i class="fa fa-info-circle" aria-hidden="true" style="padding-left: 1px; color: rgb(129, 133, 137, 0.2);" ></i></p>
						<h1 class="dfault-0" id="rps_stats_total_incubation_days"></h1>
					</div>
				</div>
			</div>
			<div class="row first-row-feature" style="padding-top:0px;">
                <h3 class="fs-titel stat-headings"><?php echo __("Reports Trend") ?></h3>  
				<div class="row" style="padding:0 20px 0 20px;">
					<div class="col-md-2">
						<select onChange="filterStar()" id="star_filter" class="input-flat">
							<option value="0"><?php echo __("ALL") ?></option> 
							<option value="1">1 <?php echo __("Star") ?></option> 
							<option value="2">2 <?php echo __("Stars") ?></option>  
							<option value="3">3 <?php echo __("Stars") ?></option> 
							<option value="4">4 <?php echo __("Stars") ?></option> 
							<option value="5">5 <?php echo __("Stars") ?></option>                    
						</select>
					</div> 
				</div>
				<div class="row" style="padding:20px;">
                    <div class="col-md-12 col-xs-12" style="max-height:350px">
						<div style="margin-left:49%;" id="reports_trend_loader" class="loader_metrics"><i class="fa fa-circle-o-notch fa-spin fa-3x fa-fw"></i><br/><?php echo __("Loading..."); ?></div>
                        <canvas style="border:1px solid #dedddd" id="chart_reports_trend" class="content-white-bkg sb-tour" width="400" height="350"></canvas>
                    </div>
                </div>                                 
            </div>
            <?php } else { ?>
			<div class="row">
				<div class="col-sm-12" style="text-align:center;" >
					<strong ><?php echo __("No Referrers Found")."!"; ?></strong> 
				</div>
			</div>
            <?php } ?>                             
        </div>
    </div>
</div>
<script
      type="text/javascript"
      src="https://cdn.jsdelivr.net/npm/chart.js"
    ></script>
    <script
    src="https://cdnjs.cloudflare.com/ajax/libs/pdf.js/2.6.347/pdf.min.js"
    integrity="sha512-Z8CqofpIcnJN80feS2uccz+pXWgZzeKxDsDNMD/dJ6997/LSRY+W4NmEt9acwR+Gt9OHN0kkI1CTianCwoqcjQ=="
    crossorigin="anonymous"
    referrerpolicy="no-referrer"
  ></script>
  <script
    type="text/javascript"
    src="https://cdnjs.cloudflare.com/ajax/libs/jspdf/1.5.3/jspdf.debug.js"
  ></script>
  <script
    src="https://cdnjs.cloudflare.com/ajax/libs/html2canvas/1.4.1/html2canvas.min.js"
    integrity="sha512-BNaRQnYJYiPSqHHDb58B0yaPfCu+Wgds8Gp/gU33kqBtgNS4tSPHuGibyoeqMV/TJlSKda6FXzoEyYGjTe+vXA=="
    crossorigin="anonymous"
    referrerpolicy="no-referrer"
  ></script>
<script>  
	$(document).ready(function(){
		$("[rel=tooltip]").tooltip({ placement: 'top'});
	}); 
	// START Date Picker
	var today = new Date();  // get current date
	var oneYearAgo = new Date();  // create new date object
	oneYearAgo.setFullYear(today.getFullYear() - 1);  // set year to previous year

	if ($.datepicker.regional['<?php echo Core_Model_Language::getCurrentLanguageDatepicker(); ?>']) {
		$.datepicker.setDefaults($.datepicker.regional['<?php echo Core_Model_Language::getCurrentLanguageDatepicker(); ?>']);
	} else {
		$.datepicker.setDefaults($.datepicker.regional['en']);
	}

	$("#from").datepicker({
		changeMonth: true,
		changeYear: true,
		numberOfMonths: 3,
		minDate: oneYearAgo,
		onClose: function( selectedDate ) {
			$("#to").datepicker( "option", "minDate", selectedDate );
		}
	});

	$("#to").datepicker({
		changeMonth: true,
		changeYear: true,
		numberOfMonths: 3,
		onClose: function( selectedDate ) {
			$("#from").datepicker( "option", "maxDate", selectedDate );
		}
	});        
	$("#to").datepicker('setDate', new Date());
	$("#from").datepicker('setDate', -30);        
	function computeDateRange() {
		var start_timestamp = parseInt($.datepicker.formatDate( "@", $("#from").datepicker("getDate"))/1000);
		var end_timestamp = parseInt($.datepicker.formatDate( "@", $("#to").datepicker("getDate"))/1000);
		//We go to 23:59
		end_timestamp = end_timestamp + (60*60*24) - 60;
		date_range = {
			"start": start_timestamp,
			"end": end_timestamp
		};
		return date_range;
	} 

	var date_range_params = '';
	function filterStats() {
		if($("#from").val() && $("#to").val()) {
			date_range_params = computeDateRange();
			if(date_range_params.start <= date_range_params.end) {                
				console.log("Done");             
			} else {
				var page_message = new AlertMessage("<?php echo __("Start date must be lower than end date."); ?>");
				page_message.addButton(true);
				page_message.setTimer(false);
				page_message.isError(true);
				page_message.show();
			}
		} else {
			var page_message = new AlertMessage("<?php echo __("You have to chose a start and an end date."); ?>");
			page_message.addButton(true);
			page_message.setTimer(false);
			page_message.isError(true);
			page_message.show();
		}
	}
	// END Date Picker

	// START Chart chart_reports_trend 
	var chart_reports_trend;
	var total_referrers_values = [];
    var chart_reports_trend_labels = [];
	var chart_reports_trend_values = [];  
    var chart_reports_trend_colors = []; 
	var range_ctx = $("#chart_reports_trend");
	var data = {
		labels: chart_reports_trend_labels,
		datasets: [
			{
				label: '<?php echo __("Total Reports"); ?>',
				backgroundColor: "#fbb862",
				borderColor: "#f59b56",
				borderWidth: 1,
				hoverBackgroundColor: "#f59b56",
				hoverBorderColor: "#fbb862",
				data: chart_reports_trend_values
			},
			{
				label: '<?php echo __("Total Deal Closed"); ?>',
				backgroundColor: "#64ad73",
				borderColor: "#3d9a70",
				borderWidth: 1,
				hoverBackgroundColor: "#3d9a70",
				hoverBorderColor: "#64ad73",
				data: total_referrers_values
			}
		]
	};
	chart_reports_trend = new Chart(range_ctx, {
		type: 'bar',
		data: data,
		options: {
			"responsive":true,
			maintainAspectRatio: false,
			scales: {
				y: {
					min: 0,
					ticks:{
						precision:0
					}                        
				}
			}
		}
	});        
	// END Chart chart_reports_trend
	
	loadReferrerReportStats();  
	var is_custome_date_filter = 0;
	function filterType() {
		range_filter=$("#range_filter").val();                 
		if (range_filter==100) {
			is_custome_date_filter=1;
			$("#custom_date_filter_container").show();
		}else{
			is_custome_date_filter=0;
			$("#custom_date_filter_container").hide();
		}  
	} 
	var star_filter = 0;
	function filterStar() {
		star_filter = parseInt($("#star_filter").val());                 
		loadReferrerReportStats();  
	}

	function loadReferrerReportStats() {  
		$(".loader_metrics").show();            
        range_filter = $("#range_filter").val();                 
        agent_id = $("#sponsor_filter").val();
		filterStats();          
        $(".dfault-0").text(0); //Reset count values to 0   
		$.ajax({
			method: "POST",
			dataType: 'json',
			url: "/migareference/reportstats/reportstats",
			data: { app_id: '<?php echo $app_id; ?>', range_filter: range_filter,agent_id:agent_id,date_range_params:date_range_params,is_custome_date_filter:is_custome_date_filter, star_filter:star_filter}
        }).done(function( data ) { 
			var from_date_param = parseInt(range_filter) == 6 ? '<?php echo __("START") ?>' : data.params.from_date;
			var to_date_param = parseInt(range_filter) == 6 ? '<?php echo __("END") ?>' : data.params.to_date;
			$(".filter-time-stamp").text(" ("+'<?php echo __("From") ?>'+": "+from_date_param+" "+'<?php echo __("To") ?>'+": "+to_date_param+")");

			if(true) { //1. Total Referrers by stars   
				if (data.range_count_ref[0].all_ref!==null) {
					$("#gen_stats_count_range_referrer").text(data.range_count_ref[0].all_ref);                                                                
				}            
				$("#var_gen_stats_count_range_referrer").html("").append(data.var_range_count_ref[0].var_all_ref);
				if (data.range_count_ref[0].five_star!==null) {
					$("#gen_stats_count_range_5s_referrer").text(data.range_count_ref[0].five_star);                    
				}
				$("#var_gen_stats_count_range_5s_referrer").html("").append(data.var_range_count_ref[0].var_five_star);
				if (data.range_count_ref[0].four_star!==null) {
					$("#gen_stats_count_range_4s_referrer").text(data.range_count_ref[0].four_star);                    
				}
				$("#var_gen_stats_count_range_4s_referrer").html("").append(data.var_range_count_ref[0].var_four_star);                        
				if (data.range_count_ref[0].three_star!==null) {
					$("#gen_stats_count_range_3s_referrer").text(data.range_count_ref[0].three_star);                    
				}
				$("#var_gen_stats_count_range_3s_referrer").html("").append(data.var_range_count_ref[0].var_three_star);                                                                                               
			} 
			
			if (true) {//2. Total Reports by stars  
				if (data.range_count_report[0].three_star_total_reports!==null) {
					$("#rep_stats_count_range_3s_reports").text(data.range_count_report[0].three_star_total_reports);                    
				}
				$("#var_rep_stats_count_range_3s_reports").html("").append(data.var_range_count_report[0].var_rep_stats_count_range_3s_reports);
				if (data.range_count_report[0].four_star_total_reports!==null) {
					$("#rep_stats_count_range_4s_reports").text(data.range_count_report[0].four_star_total_reports);                    
				}
				$("#var_rep_stats_count_range_4s_reports").html("").append(data.var_range_count_report[0].var_rep_stats_count_range_4s_reports);
				if (data.range_count_report[0].five_star_total_reports!==null) {
					$("#rep_stats_count_range_5s_reports").text(data.range_count_report[0].five_star_total_reports);                    
				}
				$("#var_rep_stats_count_range_5s_reports").html("").append(data.var_range_count_report[0].var_rep_stats_count_range_5s_reports);
				if (data.range_count_report[0].total_reports!==null) {
					$("#rep_stats_count_range_total_reports").text(data.range_count_report[0].total_reports);                    
				}
				$("#var_rep_stats_count_range_total_reports").html("").append(data.var_range_count_report[0].var_rep_stats_count_range_total_reports);
				//3. Incubation Days stars
				if (data.range_count_report[0].three_star_incubation!==null) {
					$("#rep_stats_range_3s_ids").text(data.range_count_report[0].three_star_incubation);                    
				}
				$("#var_rep_stats_range_3s_ids").html("").append(data.var_range_count_report[0].three_star_incubation);
				if (data.range_count_report[0].four_star_incubation!==null) {
					$("#rep_stats_range_4s_ids").text(data.range_count_report[0].four_star_incubation);                    
				}
				$("#var_rep_stats_range_4s_ids").html("").append(data.var_range_count_report[0].four_star_incubation);
				if (data.range_count_report[0].five_star_incubation!==null) {
					$("#rep_stats_range_5s_ids").text(data.range_count_report[0].five_star_incubation);                    
				}
				$("#var_rep_stats_range_5s_ids").html("").append(data.var_range_count_report[0].five_star_incubation);
				if (data.range_count_report[0].total_incubation!==null) {
					$("#rep_stats_range_total_incubation_ids").text(data.range_count_report[0].total_incubation);                    
				}
				$("#var_rep_stats_range_total_incubation_ids").html("").append(data.var_range_count_report[0].total_incubation);
				//4. KPI Report Conv.
				if (data.range_count_report[0].three_star_conv_kpi!==null) {
					$("#rep_stats_range_3s_conv_kpi").text(data.range_count_report[0].three_star_conv_kpi);                    
				}
				toggleColor('#rep_stats_range_3s_conv_kpi', data.range_count_report[0].three_star_conv_kpi, 0.15);
				$("#var_rep_stats_range_3s_conv_kpi").html("").append(data.var_range_count_report[0].var_rep_stats_range_3s_conv_kpi);
				if (data.range_count_report[0].four_star_conv_kpi!==null) {
					$("#rep_stats_range_4s_conv_kpi").text(data.range_count_report[0].four_star_conv_kpi);                    
				}
				toggleColor('#rep_stats_range_4s_conv_kpi', data.range_count_report[0].four_star_conv_kpi, 0.15);
				$("#var_rep_stats_range_4s_conv_kpi").html("").append(data.var_range_count_report[0].var_rep_stats_range_4s_conv_kpi);
				if (data.range_count_report[0].five_star_conv_kpi!==null) {
					$("#rep_stats_range_5s_conv_kpi").text(data.range_count_report[0].five_star_conv_kpi);                    
				}
				toggleColor('#rep_stats_range_5s_conv_kpi', data.range_count_report[0].five_star_conv_kpi, 0.15);
				$("#var_rep_stats_range_5s_conv_kpi").html("").append(data.var_range_count_report[0].var_rep_stats_range_5s_conv_kpi);
				if (data.range_count_report[0].total_conv_kpi!==null) {
					$("#rep_stats_range_total_conv_kpi").text(data.range_count_report[0].total_conv_kpi);                    
				}
				toggleColor('#rep_stats_range_total_conv_kpi', data.range_count_report[0].total_conv_kpi, 0.15);
				$("#var_rep_stats_range_total_conv_kpi").html("").append(data.var_range_count_report[0].var_rep_stats_range_total_conv_kpi);
				//5. Avg Rep. x Active Ref.
				if (data.range_count_report[0].rep_stats_range_avg_rep_x_active_ref_3s_kpi!==null) {
					$("#rep_stats_range_avg_rep_x_active_ref_3s_kpi").text(data.range_count_report[0].rep_stats_range_avg_rep_x_active_ref_3s_kpi);                    
				}
				$("#var_rep_stats_range_avg_rep_x_active_ref_3s_kpi").html("").append(data.var_range_count_report[0].var_rep_stats_range_avg_rep_x_active_ref_3s_kpi);
				if (data.range_count_report[0].rep_stats_range_avg_rep_x_active_ref_4s_kpi!==null) {
					$("#rep_stats_range_avg_rep_x_active_ref_4s_kpi").text(data.range_count_report[0].rep_stats_range_avg_rep_x_active_ref_4s_kpi);                    
				}
				$("#var_rep_stats_range_avg_rep_x_active_ref_4s_kpi").html("").append(data.var_range_count_report[0].var_rep_stats_range_avg_rep_x_active_ref_4s_kpi);
				if (data.range_count_report[0].rep_stats_range_avg_rep_x_active_ref_5s_kpi!==null) {
					$("#rep_stats_range_avg_rep_x_active_ref_5s_kpi").text(data.range_count_report[0].rep_stats_range_avg_rep_x_active_ref_5s_kpi);                    
				}
				$("#var_rep_stats_range_avg_rep_x_active_ref_5s_kpi").html("").append(data.var_range_count_report[0].var_rep_stats_range_avg_rep_x_active_ref_5s_kpi);
				if (data.range_count_report[0].rep_stats_range_avg_rep_x_active_ref_all_kpi!==null) {
					$("#rep_stats_range_avg_rep_x_active_ref_all_kpi").text(data.range_count_report[0].rep_stats_range_avg_rep_x_active_ref_all_kpi);                    
				}
				$("#var_rep_stats_range_avg_rep_x_active_ref_all_kpi").html("").append(data.var_range_count_report[0].var_rep_stats_range_avg_rep_x_active_ref_all_kpi);
				//6. Expected Reports
				if (data.range_count_report[0].rep_stats_range_expected_reports_3s_kpi!==null) {
					$("#rep_stats_range_expected_reports_3s_kpi").text(data.range_count_report[0].rep_stats_range_expected_reports_3s_kpi);                    
				}
				if (data.range_count_report[0].rep_stats_range_expected_reports_4s_kpi!==null) {
					$("#rep_stats_range_expected_reports_4s_kpi").text(data.range_count_report[0].rep_stats_range_expected_reports_4s_kpi);                    
				}
				if (data.range_count_report[0].rep_stats_range_expected_reports_5s_kpi!==null) {
					$("#rep_stats_range_expected_reports_5s_kpi").text(data.range_count_report[0].rep_stats_range_expected_reports_5s_kpi);                    
				}
				if (data.range_count_report[0].rep_stats_range_expected_reports_all_kpi!==null) {
					$("#rep_stats_range_expected_reports_all_kpi").text(data.range_count_report[0].rep_stats_range_expected_reports_all_kpi);                    
				}
			}

			//Report Performances Statistics (START)
			if (true) {
				if (data.range_count_report[0].three_star_total_reports!==null) {
					$("#rps_stats_3s_report").text(data.range_count_report[0].three_star_total_reports);                    
				}
				$("#var_rps_stats_3s_report").html("").append(data.var_range_count_report[0].var_rps_stats_3s_report);
				if (data.range_count_report[0].four_star_total_reports!==null) {
					$("#rps_stats_4s_report").text(data.range_count_report[0].four_star_total_reports);                    
				}
				$("#var_rps_stats_4s_report").html("").append(data.var_range_count_report[0].var_rps_stats_4s_report);
				if (data.range_count_report[0].five_star_total_reports!==null) {
					$("#rps_stats_5s_report").text(data.range_count_report[0].five_star_total_reports);                    
				}
				$("#var_rps_stats_5s_report").html("").append(data.var_range_count_report[0].var_rps_stats_5s_report);
				if (data.range_count_report[0].total_reports!==null) {
					$("#rps_stats_total_report").text(data.range_count_report[0].total_reports);                    
				}
				$("#var_rps_stats_total_report").html("").append(data.var_range_count_report[0].var_rps_stats_total_report);
			}

			if (true) { 
				if (data.range_count_deal_closed[0].total_deal_closed!==null) {
					$("#rps_stats_total_no_of_deal_closed").text(data.range_count_deal_closed[0].total_deal_closed);                    
				}
				$("#var_rps_stats_total_no_of_deal_closed").html("").append(data.var_range_count_deal_closed[0].var_rps_stats_total_no_of_deal_closed);
				if (data.range_count_deal_closed[0].five_star_total_deal_closed!==null) {
					$("#rps_stats_five_star_total_no_of_deal_closed").text(data.range_count_deal_closed[0].five_star_total_deal_closed);                    
				}
				$("#var_rps_stats_five_star_total_no_of_deal_closed").html("").append(data.var_range_count_deal_closed[0].var_rps_stats_five_star_total_no_of_deal_closed);
				if (data.range_count_deal_closed[0].four_star_total_deal_closed!==null) {
					$("#rps_stats_four_star_total_no_of_deal_closed").text(data.range_count_deal_closed[0].four_star_total_deal_closed);                    
				}
				$("#var_rps_stats_four_star_total_no_of_deal_closed").html("").append(data.var_range_count_deal_closed[0].var_rps_stats_four_star_total_no_of_deal_closed);
				if (data.range_count_deal_closed[0].three_star_total_deal_closed!==null) {
					$("#rps_stats_three_star_total_no_of_deal_closed").text(data.range_count_deal_closed[0].three_star_total_deal_closed);                    
				}
				$("#var_rps_stats_three_star_total_no_of_deal_closed").html("").append(data.var_range_count_deal_closed[0].var_rps_stats_three_star_total_no_of_deal_closed);

				if (data.range_count_deal_closed[0].total_deal_closed_amount!==null) {
					$("#rps_stats_total_no_of_deal_closed_amount").text((parseFloat(data.range_count_deal_closed[0].total_deal_closed_amount).toFixed(2)).toString().replace(/\B(?<!\.\d*)(?=(\d{3})+(?!\d))/g, ","));                    
				}
				$("#var_rps_stats_total_no_of_deal_closed_amount").html("").append(data.var_range_count_deal_closed[0].var_rps_stats_total_no_of_deal_closed_amount);
				if (data.range_count_deal_closed[0].five_star_total_deal_closed_amount!==null) {
					$("#rps_stats_five_star_total_no_of_deal_closed_amount").text((parseFloat(data.range_count_deal_closed[0].five_star_total_deal_closed_amount).toFixed(2)).toString().replace(/\B(?<!\.\d*)(?=(\d{3})+(?!\d))/g, ","));                    
				}
				$("#var_rps_stats_five_star_total_no_of_deal_closed_amount").html("").append(data.var_range_count_deal_closed[0].var_rps_stats_five_star_total_no_of_deal_closed_amount);
				if (data.range_count_deal_closed[0].four_star_total_deal_closed_amount!==null) {
					$("#rps_stats_four_star_total_no_of_deal_closed_amount").text((parseFloat(data.range_count_deal_closed[0].four_star_total_deal_closed_amount).toFixed(2)).toString().replace(/\B(?<!\.\d*)(?=(\d{3})+(?!\d))/g, ","));                    
				}
				$("#var_rps_stats_four_star_total_no_of_deal_closed_amount").html("").append(data.var_range_count_deal_closed[0].var_rps_stats_four_star_total_no_of_deal_closed_amount);
				if (data.range_count_deal_closed[0].three_star_total_deal_closed_amount!==null) {
					$("#rps_stats_three_star_total_no_of_deal_closed_amount").text((parseFloat(data.range_count_deal_closed[0].three_star_total_deal_closed_amount).toFixed(2)).toString().replace(/\B(?<!\.\d*)(?=(\d{3})+(?!\d))/g, ","));                    
				}
				$("#var_rps_stats_three_star_total_no_of_deal_closed_amount").html("").append(data.var_range_count_deal_closed[0].var_rps_stats_three_star_total_no_of_deal_closed_amount);

				if (data.range_count_deal_closed[0].total_commissions_paid!==null) {
					$("#rps_stats_total_commissions_paid").text((parseFloat(data.range_count_deal_closed[0].total_commissions_paid).toFixed(2)).toString().replace(/\B(?<!\.\d*)(?=(\d{3})+(?!\d))/g, ","));                    
				}
				$("#var_rps_stats_total_commissions_paid").html("").append(data.var_range_count_deal_closed[0].var_rps_stats_total_commissions_paid);
				if (data.range_count_deal_closed[0].five_star_total_commissions_paid!==null) {
					$("#rps_stats_five_star_total_commissions_paid").text((parseFloat(data.range_count_deal_closed[0].five_star_total_commissions_paid).toFixed(2)).toString().replace(/\B(?<!\.\d*)(?=(\d{3})+(?!\d))/g, ","));                    
				}
				$("#var_rps_stats_five_star_total_commissions_paid").html("").append(data.var_range_count_deal_closed[0].var_rps_stats_five_star_total_commissions_paid);
				if (data.range_count_deal_closed[0].four_star_total_commissions_paid!==null) {
					$("#rps_stats_four_star_total_commissions_paid").text((parseFloat(data.range_count_deal_closed[0].four_star_total_commissions_paid).toFixed(2)).toString().replace(/\B(?<!\.\d*)(?=(\d{3})+(?!\d))/g, ","));                    
				}
				$("#var_rps_stats_four_star_total_commissions_paid").html("").append(data.var_range_count_deal_closed[0].var_rps_stats_four_star_total_commissions_paid);
				if (data.range_count_deal_closed[0].three_star_total_commissions_paid!==null) {
					$("#rps_stats_three_star_total_commissions_paid").text((parseFloat(data.range_count_deal_closed[0].three_star_total_commissions_paid).toFixed(2)).toString().replace(/\B(?<!\.\d*)(?=(\d{3})+(?!\d))/g, ","));                    
				}
				$("#var_rps_stats_three_star_total_commissions_paid").html("").append(data.var_range_count_deal_closed[0].var_rps_stats_three_star_total_commissions_paid);

				// Rep. Succ./Total
				var total_reports_avg = 0;				
				if ((data.range_count_deal_closed[0].total_deal_closed!==null && data.range_count_deal_closed[0].total_deal_closed!='0') || (data.range_count_deal_closed[0].total_success_reports!==null && data.range_count_deal_closed[0].total_success_reports!='0')) {
					total_reports_avg = ((parseFloat(data.range_count_deal_closed[0].total_success_reports) +parseFloat(data.range_count_deal_closed[0].total_deal_closed)) /parseFloat(data.range_count_deal_closed[0].total_reports)).toFixed(2);
					$("#rps_stats_total_success_reports_avg").text(total_reports_avg).toString().replace(/\B(?<!\.\d*)(?=(\d{3})+(?!\d))/g, ",");                   
				}
				toggleColor('#rps_stats_total_success_reports_avg', total_reports_avg, 0.20); 				
				$("#var_rps_stats_total_success_reports_avg").html("").append(data.var_range_count_deal_closed[0].var_rps_stats_total_success_reports_avg);

				//  Rep. Succ./Total 5 Stars
				var total_reports_5s_avg = 0;
				if ((data.range_count_deal_closed[0].five_star_total_deal_closed!==null && data.range_count_deal_closed[0].five_star_total_deal_closed!='0') || (data.range_count_deal_closed[0].total_success_reports_5s!==null && data.range_count_deal_closed[0].total_success_reports_5s!='0')) {					
					total_reports_5s_avg = ((parseFloat(data.range_count_deal_closed[0].total_success_reports_5s) +parseFloat(data.range_count_deal_closed[0].five_star_total_deal_closed)) /parseFloat(data.range_count_deal_closed[0].total_reports_5s)).toFixed(2);
					$("#rps_stats_total_success_reports_5s_avg").text(total_reports_5s_avg).toString().replace(/\B(?<!\.\d*)(?=(\d{3})+(?!\d))/g, ",");                    
				}				
				toggleColor('#rps_stats_total_success_reports_5s_avg', total_reports_5s_avg, 0.20);				
				$("#var_rps_stats_total_success_reports_5s_avg").html("").append(data.var_range_count_deal_closed[0].var_rps_stats_total_success_reports_5s_avg);
				
				//  Rep. Succ./Total 4 Stars
				var total_reports_4s_avg = 0;
				if ((data.range_count_deal_closed[0].four_star_total_deal_closed!==null && data.range_count_deal_closed[0].four_star_total_deal_closed!='0') || (data.range_count_deal_closed[0].total_success_reports_4s!==null && data.range_count_deal_closed[0].total_success_reports_4s!='0')) {					
					total_reports_4s_avg = ((parseFloat(data.range_count_deal_closed[0].total_success_reports_4s) +parseFloat(data.range_count_deal_closed[0].four_star_total_deal_closed)) /parseFloat(data.range_count_deal_closed[0].total_reports_4s)).toFixed(2);
					$("#rps_stats_total_success_reports_4s_avg").text(total_reports_4s_avg).toString().replace(/\B(?<!\.\d*)(?=(\d{3})+(?!\d))/g, ",");                    
				}				
				toggleColor('#rps_stats_total_success_reports_4s_avg', total_reports_4s_avg, 0.20);				
				$("#var_rps_stats_total_success_reports_4s_avg").html("").append(data.var_range_count_deal_closed[0].var_rps_stats_total_success_reports_4s_avg);

				// Rep. Succ./Total 3 Stars
				var total_reports_3s_avg = 0;
				if ((data.range_count_deal_closed[0].three_star_total_deal_closed!==null && data.range_count_deal_closed[0].three_star_total_deal_closed!='0') || (data.range_count_deal_closed[0].total_success_reports_3s!==null && data.range_count_deal_closed[0].total_success_reports_3s!='0')) {					
					total_reports_3s_avg = ((parseFloat(data.range_count_deal_closed[0].total_success_reports_3s) +parseFloat(data.range_count_deal_closed[0].three_star_total_deal_closed)) /parseFloat(data.range_count_deal_closed[0].total_reports_3s)).toFixed(2);
					$("#rps_stats_total_success_reports_3s_avg").text(total_reports_3s_avg).toString().replace(/\B(?<!\.\d*)(?=(\d{3})+(?!\d))/g, ",");                    
				}				
				toggleColor('#rps_stats_total_success_reports_3s_avg', total_reports_3s_avg, 0.20);				
				$("#var_rps_stats_total_success_reports_3s_avg").html("").append(data.var_range_count_deal_closed[0].var_rps_stats_total_success_reports_3s_avg);

				$("#rps_stats_3s_incubation_days").html("").append(data.range_count_deal_closed[0].three_star_total_incubation !== null ? data.range_count_deal_closed[0].three_star_total_incubation : 0);
				$("#rps_stats_4s_incubation_days").html("").append(data.range_count_deal_closed[0].four_star_total_incubation !== null ? data.range_count_deal_closed[0].four_star_total_incubation : 0);
				$("#rps_stats_5s_incubation_days").html("").append(data.range_count_deal_closed[0].five_star_total_incubation !== null ? data.range_count_deal_closed[0].five_star_total_incubation : 0);
				$("#rps_stats_total_incubation_days").html("").append(data.range_count_deal_closed[0].total_incubation !== null ? data.range_count_deal_closed[0].total_incubation : 0);
			}
			//Report Performances Statistics (END)

			//Report Trend Start
			if(data.reports_trend_chart.length > 0) {
				var reports_trend_chart_labels = [];
				var reports_trend_chart_total_reports = [];
				var reports_trend_chart_total_deal_closed = [];
				$.each(data.reports_trend_chart, function(ind, elem) {
					reports_trend_chart_labels.push(elem.labels);
					reports_trend_chart_total_reports.push(elem.total_reports);
					reports_trend_chart_total_deal_closed.push(elem.total_deal_closed);
				});
				chart_reports_trend.data.datasets[0].data = reports_trend_chart_total_reports;
				chart_reports_trend.data.datasets[1].data = reports_trend_chart_total_deal_closed;
				chart_reports_trend.data.labels = reports_trend_chart_labels;
				chart_reports_trend.update();
			} else {
				chart_reports_trend.data.datasets[0].data = [];
				chart_reports_trend.data.datasets[1].data = [];
				chart_reports_trend.data.labels = [];
				chart_reports_trend.update();
			}
			//Report Trend End

			$(".loader_metrics").hide();

			// Background Print WOrk
			const divElement = document.getElementById('pagecontainer');
			console.log("Element is here");
			console.log(divElement);
			// Get the innerHTML of the div element
			const htmlContent = divElement.innerHTML;
			$("#newcontent").remove();
			// Create a new element to pass the same data
			newElement = document.createElement('div');
			newElement.setAttribute('id', 'newcontent');
			newElement.style.width = '1284px';
			newElement.style.marginLeft = '200px';
			newElement.style.position = "absolute";
			newElement.style.bottom = "100%";
			newElement.innerHTML = htmlContent;

			duplicateChartCanvas = newElement.querySelector('#chart_reports_trend');
			duplicateChart = new Chart(duplicateChartCanvas, {
				type: chart_reports_trend.config.type,
				data: chart_reports_trend.config.data,
				options: chart_reports_trend.config.options
			});
			duplicateChartCanvas.style.height='348px';

			range_filter=$("#range_filter").val();
			sponsor_filter=$("#sponsor_filter").val();
			//referrer_filter=$("#referrer_filter").val();
			from_date=$("#from").val();
			to_date=$("#to").val();  
			star_filter_value=$("#star_filter").val();    
			myDropdown = newElement.querySelector('#star_filter');                                                            
			optionWithValue100 = myDropdown.querySelector(`option[value="${star_filter_value}"]`);                    
			optionWithValue100.selected = true;                                      
			myDropdown = newElement.querySelector('#range_filter');                                                            
			optionWithValue100 = myDropdown.querySelector(`option[value="${range_filter}"]`);                    
			optionWithValue100.selected = true;
			myDropdown = newElement.querySelector('#sponsor_filter');                                                            
			optionWithValue100 = myDropdown.querySelector(`option[value="${sponsor_filter}"]`);                    
			optionWithValue100.selected = true;
			fromInput = newElement.querySelector('#from');
			console.log(fromInput);
			fromInput.setAttribute('value', from_date);
			toInput = newElement.querySelector('#to');
			toInput.setAttribute('value', to_date);     
			document.body.appendChild(newElement);
		}).error(function() {            
            $(".loader_metrics").hide();
        });
	}

	function printPdf() {     
		$("#pdf_download_loader").show();   
		const doc = new jsPDF();            
		html2canvas(newElement.querySelector("#content")).then((canvas) => {
			var imgData    = canvas.toDataURL();
			var imgWidth   = 210; 
			var pageHeight = 295;  
			var imgHeight  = canvas.height * imgWidth / canvas.width;
			var heightLeft = imgHeight;        
			var doc        = new jsPDF('p', 'mm');
			var position   = 3; // give some top padding to first page
			doc.addImage(imgData, 'JPEG', 0, position, imgWidth, imgHeight);
			heightLeft -= pageHeight;        
			while (heightLeft >= 0) {
			position = heightLeft - imgHeight; // top padding for other pages        
			doc.addPage();
			doc.addImage(imgData, 'JPEG', 0, position, imgWidth, imgHeight);
			heightLeft -= pageHeight;
			}
			doc.save('REPORT_STATS.pdf');
			$("#pdf_download_loader").hide();
		});
	}
	function toggleColor(elem, current_value, limit_value) {
		if (parseFloat(current_value) < limit_value) {
			$(elem).addClass('text-red');
		} else {
			$(elem).removeClass('text-red');
		}
	}
</script>
<style>
/* Stat CSS */
.stat-calculate{
    padding-top: 8px;
    padding-bottom: 8px;
    border-radius: 7px;
    background: #f7f7f7;
    text-align: center;
    transition: transform .7s;
}
.stat-calculate:hover {      
    -webkit-transform: scale(1.1);
    -moz-transform: scale(1.1);
    -ms-transform: scale(1.1);
    -o-transform: scale(1.1);
    transform: scale(1.1);    
    background: #9797974a;
}
.stat-calculate h1{
    font-weight:700;
    margin-top:18px;
    margin-bottom:21px;
    line-height:40px;

}
.stat-calculate p{
    font-weight:700;
    /* font-size:1vw; */
    line-height:20px;
    overflow:hidden;
}
.count_veriation{
    font-size:small;
}
.count_veriation span{
    font-size:small;
    /* font-size:1vw; */
}
.var-positive {
    background: #87d82757;
    padding: 2px;
    border-radius: 10px;
    color: green;
    font-weight: 700;
}
.var-negative {
    background: #d827272e;
    padding: 2px;
    border-radius: 10px;
    color: #e91e63;
    font-weight: 700;
}
.var-nochange {
    background: #0000003d;
    padding: 2px;
    border-radius: 10px;
    font-weight: 700;
}
.stat-headings{
    color: white;
    background-color: #0099C7;
    padding: 9px;
    margin-top: 14px;
    margin-bottom: 14px;
    margin-left: 20px;
    margin-right: 20px;
}
.stat-count-container{
    border: 1px solid #d0cfcf;
    margin-left: 20px;
    margin-right: 20px;
    padding-bottom: 15px;
    padding-top: 15px;
}
/* Pie CHart */
.pie-chart-legend ul>li span{
    display: inline-block;    
    width: 12px;
    height: 12px;
    margin-right: 5px;
}
.pie-chart-legend ul>li {
    display: inline-block;  
    margin: 4px;  
}

.pie-chart-legend{
  height:115px;
  
}
.hidden-pie-label {
  text-decoration: line-through;
}
/* START Data Table  style*/
.sub_heading{
        border-bottom: 2px solid #0099c7;
        padding-bottom: 13px;
    }
    .remove_btn{
        background-color: red;
    }
    .emptydataset{
        text-align: center;
    }
table{
    background-color: white;
}
     table.dataTable {
                margin: 20px 0 10px;
                width: 100% !important;
            }

            table.dataTable th {
                text-align: left;
            }
            table.dataTable tbody tr.edit_product {
                cursor: pointer;
            }

            .dataTables_info {
                float: left;
                padding: 10px;
            }

            .dataTables_paginate {
                float: right;
            }

            .dataTables_paginate a {
                display: block;
                float: left;
                margin-left: 4px;
                padding: 6px;
            }

            .dataTables_paginate a.paginate_button_disabled {
                opacity: 0.3
            }

            .dataTable tbody tr:last-of-type {
                border-bottom: 0;
            }

            #migasms {
                overflow: auto;
            }
            #contantcontainer {
                border-radius: 0px !important;
            }
            #contentheader{
              background-color: #f3f3f3 !important;
              padding: 8px !important;
            }
            #contentfooter{
              padding: 5px !important;
            }
            .right-side{
              float: right;
              margin-right: 5px;
            }
            #delbtn{
              float: right;
            }
            #delbtner{
              float: right;
            }
/* END Data Table  style*/
#row_filter_metrics label{line-height:29px}
.text-red {
	color: red !important;
}
</style>