<!doctype html>
<html lang="en">
	<head>
		<!-- Required meta tags -->
		<meta charset="utf-8">
		<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

		<!-- Bootstrap CSS -->
		<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css" integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">

		<title><?php echo $this->getTitle(); ?></title>
		</head>
	<body>
		<div class="row mt-3 mb-3">
			<div class="col-lg-6 offset-lg-3">
				<div class="card">
					<div class="card-header"><?php echo $this->getPanelTitle(); ?></div>
					<div class="card-body">
						<?php if ($this->getErrors()) : ?>
					  	<div class="alert alert-danger" role="alert"><?php echo $this->getErrors(); ?></div>
						<?php endif; ?>
						<?php if ($this->getSuccess()) : ?>
						  <div class="alert alert-success" role="alert"><?php echo $this->getSuccess(); ?></div>
						<?php endif; ?>
						<form method="post" enctype="multipart/form-data" action="<?php echo $this->getMainUrl(); ?>/migareference/decryptor">
							<div class="form-group">
								<label for="xml_file"><?php echo $this->getLabelFile(); ?></label>
								<input name="xml_file" type="file" class="form-control-file" id="xml_file" aria-describedby="xml_file_help" required>
								<small id="xml_file_help" class="form-text text-muted"><?php echo $this->getLabelFileHelp(); ?></small>
							</div>
							<div class="form-group">
								<label for="encryption_key"><?php echo $this->getLabelKey(); ?></label>
								<input name="encryption_key" type="text" class="form-control" id="encryption_key" aria-describedby="encryption_key_help" required>
								<small id="encryption_key_help" class="form-text text-muted"><?php echo $this->getLabelKeyHelp(); ?></small>
							</div>
							<button type="submit" class="btn btn-primary btn-block"><?php echo $this->getLabelDecrypt(); ?></button>
							<?php if ($this->getUserXml()) : ?>
							<p>&nbsp;</p>
							<?php if ($this->getSuccess()) : ?>
							<div class="alert alert-success" role="alert"><?php echo $this->getSuccess(); ?></div>
							<?php endif; ?>
							<div class="form-group">
								<label for="user_xml"><?php echo $this->getUserXmlLabel(); ?></label>
								<textarea class="form-control" name="user_xml" rows="10"><?php echo $this->getUserXml(); ?></textarea>
							</div>
							<?php endif; ?>
						</form>
					</div>
				</div>
			</div>
		</div>

		<div class="jumbotron jumbotron-fluid">
			<div class="container">
				<h1 class="display-4"><?php echo $this->getTitle(); ?></h1>
				<p class="lead"><?php echo $this->getDescription(); ?></p>
				<h1 class="display-4"><?php echo $this->getSampleXmlTitle(); ?></h1>
				<p><img src="<?php echo $this->getSampleXmlFile(); ?>" style="width: 70%;" /></p>
				<p>
					<span class="badge badge-info"><?php echo $this->getVersion(); ?></span>
					<a href="https://www.migastone.com/" class="badge badge-primary"><?php echo $this->getVendor(); ?></a>
				</p>
			</div>
		</div>

	<!-- Optional JavaScript; choose one of the two! -->

	<!-- Option 1: jQuery and Bootstrap Bundle (includes Popper) -->
	<script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
	<script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ho+j7jyWK8fNQe+A12Hb8AhRq26LrZ/JpcUGGOn+Y7RsweNrtN/tE3MoK7ZeZDyx" crossorigin="anonymous"></script>

	<!-- Option 2: jQuery, Popper.js, and Bootstrap JS
	<script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
	<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
	<script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.min.js" integrity="sha384-w1Q4orYjBQndcko6MimVbzY0tgp4pWB4lZ7lr30WKz0vr/aWKhXdBNmNb5D92v7s" crossorigin="anonymous"></script>
	-->
	</body>
</html>
