    $show_paid_status_toggle   = (count($pre_report_settings) && intval($pre_report_settings[0]['agent_can_manage']) === 1);
                                <?php if ($show_paid_status_toggle): ?>
                                <th><?php echo __('Paid Status Access'); ?>?</th>
                                <?php endif; ?>
<?php if ($show_paid_status_toggle): ?>
$('#table_appowners').on('change', '.paid_status_access', function(){
  var paid_status_access = $(this).prop('checked') ? 1 : 0;
  var agent_id = $(this).closest('tr').find('td:eq(1)').text();
    if (confirm('<?php echo __("Are you sure you want to update Paid status access?"); ?>')) {
        var url ='<?php echo $this->getUrl('migareference/application/updatepaidstatusaccess'); ?>/app_id/<?php echo $app_id; ?>/agent_id/'+agent_id+'/paid_status_access/'+paid_status_access;
        reload(this, url, true, function(datas) {
            if (datas.success) {
                page.reload();
            }
        });
    }
});
<?php endif; ?>
<?php $admin_non_searchable_columns = $show_paid_status_toggle ? [5,6,7] : [5,6]; ?>
            targets: <?php echo json_encode($admin_non_searchable_columns); ?>, // Columns to exclude from search
